### ISSUE TITLE
Bug: Enchanter not dropping off enchanted items

### ISSUE THREAD

**Issue by binksayres** [TangoTek/TekTopia-Community#102]
**Describe the bug**
While my enchanter is very active with making paper and enchanting items, the enchanter is not dropping off the enchanted items.  They're just accumulating in his inventory, much like the charcoal issue with the blacksmith

**Expected behavior**
Placing the newly enchanted items into the community storage

** Server/Location **
Single player creative.

** Additional Information ** 
All items used in the process were villager items, made from villager items.

**Comment by JohnyDL** [comment]
possibly related to #65

**Comment by tomerorian** [comment]
I can confirm this too
![image](https://user-images.githubusercontent.com/2083414/58507286-12b04780-819a-11e9-90ed-dac89ff85570.png)
(that is about 2 days after he made those)

Main #1 MoleTopia village

**Comment by Sobertron** [comment]
Having the same issue.

**Comment by bhdavies** [comment]
Can confirm on Server 2   x: 6155, z: -8850
![EnchanterInv](https://user-images.githubusercontent.com/10376140/58527994-2a83cd80-8192-11e9-8cff-9fbbf2baa28b.png)

**Comment by SpaceTek75** [comment]
Having the same issue:
Playing single player.
![2019-05-30_20 55 01](https://user-images.githubusercontent.com/51185252/58629150-f5f14c80-831e-11e9-8a48-568199384894.png)


I now find he is not moving anymore just staying in the one house. He does sleep at night but wakes up and just stands there.

**Comment by JohnyDL** [comment]
Okay so I'm not sure if this is going to be enlightening but I did a before and after 1 minecraft day for my village, these are my results for the Enchanter... I'll do another few days if they aren't as enlightening as we hope. I am pretty sure they will deliver one item to storage once they have a hand full of one item but they need to be delivering to storage when they have a hand full of several different items, and/or delivering all their now unusable to them enchanted items when they're in the storage anyway #65

Anyway without further ado 11 enchanters before and after 1 and 2 in game days:

![Day 0 - Enchanter 4 - Ceirren Coyle](https://user-images.githubusercontent.com/5202568/58667884-39ec4d80-832f-11e9-8904-9ee95587916e.png)
![Day 1 - Enchanter 4 - Ceirren Coyle](https://user-images.githubusercontent.com/5202568/58667890-3c4ea780-832f-11e9-9d76-c04b83a0c7af.png)
![Day 2 - Enchanter 4 - Ceirren Coyle](https://user-images.githubusercontent.com/5202568/58671061-2940d500-8339-11e9-9fb8-730b3184f9e5.png)

![Day 0 - Enchanter 6 - Owen Shalabim](https://user-images.githubusercontent.com/5202568/58667905-47093c80-832f-11e9-893e-7d665353fae3.png)
![Day 1 - Enchanter 6 - Owen Shalabim](https://user-images.githubusercontent.com/5202568/58667906-47a1d300-832f-11e9-9f3f-7eea99a4447e.png)
![Day 2 - Enchanter 8 - Owen Shalabim](https://user-images.githubusercontent.com/5202568/58671070-3067e300-8339-11e9-83ee-c09c70b6461b.png)

![Day 0 - Enchanter 7 - Dungarth Feenix](https://user-images.githubusercontent.com/5202568/58667910-4bcdf080-832f-11e9-89e9-f75d0921d74f.png)
![Day 1 - Enchanter 7 - Dungarth Feenix](https://user-images.githubusercontent.com/5202568/58667911-4bcdf080-832f-11e9-9d2f-0ed0b8f67bfb.png)
![Day 2 - Enchanter 8 - Dungarth Feenix](https://user-images.githubusercontent.com/5202568/58671078-3362d380-8339-11e9-8997-bd6e394fc474.png)

![Day 0 - Enchanter 10 - Clotilda Varzand](https://user-images.githubusercontent.com/5202568/58667918-4ffa0e00-832f-11e9-85bd-7652dec85b0c.png)
![Day 1 - Enchanter 10 - Cotilda Varzand](https://user-images.githubusercontent.com/5202568/58667919-4ffa0e00-832f-11e9-97b8-caf4794f44a6.png)
![Day 2 - Enchanter 13 - Clotilda Varzand](https://user-images.githubusercontent.com/5202568/58671092-3d84d200-8339-11e9-9069-68ae3469d6a7.png)

![Day 0 - Enchanter 10 - Daisy Grantham](https://user-images.githubusercontent.com/5202568/58667921-538d9500-832f-11e9-9d88-b94d06025ef0.png)
![Day 1 - Enchanter 11 - Daisy Grantham](https://user-images.githubusercontent.com/5202568/58667922-538d9500-832f-11e9-9b8a-434386101573.png)
![Day 2 - Enchanter 12 - Daisy Grantham](https://user-images.githubusercontent.com/5202568/58671097-407fc280-8339-11e9-8b2c-a4f8cdeab013.png)

![Day 0 - Enchanter 11 - Hanna Van Gandt](https://user-images.githubusercontent.com/5202568/58667927-57211c00-832f-11e9-9345-e83b4503b49c.png)
![Day 1 - Enchanter 11 - Hanna Van Gandt](https://user-images.githubusercontent.com/5202568/58667928-57211c00-832f-11e9-9d5a-0f936b3cb416.png)
![Day 2 - Enchanter 11 - Hannah Van Gandt](https://user-images.githubusercontent.com/5202568/58671104-44134980-8339-11e9-987b-711eaaaf2870.png)

![Day 0 - Enchanter 12 - Caable Rosemourne](https://user-images.githubusercontent.com/5202568/58667931-5a1c0c80-832f-11e9-9d66-e817b19333db.png)
![Day 1 - Enchanter 12 - Caable Rosemourne](https://user-images.githubusercontent.com/5202568/58667932-5a1c0c80-832f-11e9-8a1b-6c01928d6e43.png)
![Day 2 - Enchanter 17 - Caable Rosemourne](https://user-images.githubusercontent.com/5202568/58671116-4aa1c100-8339-11e9-8a42-ee3e144c09d2.png)

![Day 0 - Enchanter 12 - Daylen Mcdonald](https://user-images.githubusercontent.com/5202568/58667937-5d16fd00-832f-11e9-88db-1196245bf66e.png)
![Day 1 - Enchanter 14 - Daylen Mcdonald](https://user-images.githubusercontent.com/5202568/58667938-5d16fd00-832f-11e9-8cef-5ccb9a9e9d11.png)
![Day 2 - Enchanter 15 - Daylen Mcdonald](https://user-images.githubusercontent.com/5202568/58671130-52f9fc00-8339-11e9-83ec-7c2f0e675c19.png)

![Day 0 - Enchanter 12 - Ningyan Rosemourne](https://user-images.githubusercontent.com/5202568/58667947-61dbb100-832f-11e9-92e2-b4d317f67b7e.png)
![Day 1 - Enchanter 13 - Ningyan Rosmourne](https://user-images.githubusercontent.com/5202568/58667948-61dbb100-832f-11e9-9631-7cdd5ad28701.png)
![Day 2 - Enchanter 16 - Ningyan Rosmourne](https://user-images.githubusercontent.com/5202568/58671132-568d8300-8339-11e9-9214-c5d4eda4cd59.png)

![Day 0 - Enchanter 100 - Davaril Blackstrand](https://user-images.githubusercontent.com/5202568/58667949-656f3800-832f-11e9-9d2c-ba4bfabd1ace.png)
![Day 1 - Enchanter 100 - Davaril Blackstrand](https://user-images.githubusercontent.com/5202568/58667951-656f3800-832f-11e9-9a2d-7a61922b081c.png)
![Day 2 - Enchanter 100 - Davaril Blackstand](https://user-images.githubusercontent.com/5202568/58671134-59887380-8339-11e9-806f-e750dcdddeb8.png)

![Day 0 - Enchanter 100 - Xell Rowland](https://user-images.githubusercontent.com/5202568/58667956-67d19200-832f-11e9-9196-31f10f6c54bc.png)
![Day 1 - Enchanter 100 - Xell Rowland](https://user-images.githubusercontent.com/5202568/58667957-67d19200-832f-11e9-9040-9b063958ee39.png)
![Day 2 - Enchanter 100 - Xell Rowland](https://user-images.githubusercontent.com/5202568/58671137-5c836400-8339-11e9-8333-e2287f282da2.png)

**Comment by TangoTek** [comment]
Enchanters will now deliver enchanted gear to storage. I simply forgot one line when I redid the delivery system recently.  Thanks!
