### ISSUE TITLE
Killed by my own guards

### ISSUE THREAD

**Issue by DS9Fireblade** [TangoTek/TekTopia-Community#103]
**Describe the bug**
In creative mode i was trying to relocate my villagers who had fallen into the water as they couldn't get out, i causally hit the one guard to move him up one block, the guards then swarmed my player attacking. To see if they were in fact attacking me I entered survival and was killed.
i don't know if this is a desired feature or not but seems to not be useful in the grand scheme of things

**To Reproduce**
1. go to a villager stuck in water, ones which have a path or are on land don't attack
2. hit the villager until 1.0 damage is produced by player
3. once on dry land villager will begin to attack

**Expected behavior**
If this has been correctly done the villager will begin to swing at you, if in survival mode you will begin to take damage.
![2019-05-27_21 01 48](https://user-images.githubusercontent.com/28073973/58437643-bfb79100-80c2-11e9-869b-dfdb46817459.png)
![2019-05-27_21 02 08](https://user-images.githubusercontent.com/28073973/58437644-bfb79100-80c2-11e9-9a55-95d9b701dc67.png)

** Server/Location **
single player testing world
town hall location 210 65 322

**Comment by TangoTek** [comment]
Guards will no longer attack players in 1.0.18
