### ISSUE TITLE
Game Crashes on Launch

### ISSUE THREAD

**Issue by Skysword5134** [TangoTek/TekTopia-Community#1036]
**Describe the bug**
The Game crashes when I try to launch it with only Tektopia installed

**To Reproduce**
1. Download Tektopia 1.1.0 or 1.0.93
2. Install Forge 1.12.2-14.23.2.2611
3. Crash on Launch

**Expected behavior**
I expected the game to launch. 

**Screenshots**

![Crash Report](https://user-images.githubusercontent.com/57459497/68332559-e45d5f00-008b-11ea-9c44-7c8f5d7adfea.png)

** Server/Location **
Singleplayer, N/A
**Additional Context**
I could be missing something completely, so I apologize if this is just a simple error on my part.

**Comment by smmmadden** [comment]
Hi Skysword5134, the Forge Version that the mod supports is 2768. 
https://sites.google.com/view/tektopia/home/about/installation

**Comment by Skysword5134** [comment]
Yep. That worked. I'm sorry to bother you, but thanks!

**Comment by smmmadden** [comment]
no bother, just helping where I can. :-)  Glad it worked! Enjoy
