### ISSUE TITLE
35 minute item despawn.  Did an experiment and can confirm.

### ISSUE THREAD

**Issue by Nightshae** [TangoTek/TekTopia-Community#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by ThomasBerends** [comment]
Can you add some information? Did this happen on one of the servers? Did it happen in a single player world?

Please answer the questions that are preformatted.

**Comment by Nightshae** [comment]
I am on Server 2, in a town that I have named 'The Northland'.  I had noticed that after I cut down some trees, the saplings falling from the leaves seemed to still be there some time after I had already moved on.  Normally this isn't an issue, thing despawn after 5 minutes, but I was picking stuff up up to 20 minutes later.
So, I did an experiment.  I chopped down a tree, which dropped an apple that I did *not* interact with in any way.  I put down a torch about 5 blocks away, then dropped a sapling beside it so that I had both an object I had interacted with and another that I had not been near in a small area.  I checked the time on my computer, then moved around my village, but kept checking back on the two items every 5 minutes or so.
The apple disappeared after roughly 30-35 minutes, I'm not sure of the exact time.  However, I was there when the sapling despawned, at the 35 minute mark.
I am aware that floating entities can cause lag on servers, and if things are around for this long a length of time, it could explain some of the lagging issues people have been talking about.  Lumberjacks, for instance, don't always pick up the saplings and apples in a quick fashion, leaving them to float until a player comes along to pick them up.
Hope this helps.  Nightshae
    On ‎Monday‎, ‎May‎ ‎27‎, ‎2019‎ ‎10‎:‎52‎:‎33‎ ‎PM‎ ‎AKDT, Thomas Berends <notifications@github.com> wrote:  
 
 
Can you add some information? Did this happen on one of the servers? Did it happen in a single player world?

**Comment by JohnyDL** [comment]
This might be a chicken and egg problem, the entities are surviving 35 minutes because a minecraft day which should be 20 minutes is somehow lasting 140 due to server load.

**Comment by TangoTek** [comment]
Yep. With a super low tick rate like we have on server 2 this is what would happen.

In other news, you should move to server 1 :-)
