### ISSUE TITLE
Give traveling merchant a job

### ISSUE THREAD

**Issue by Tab-160** [TangoTek/TekTopia-Community#112]
**Describe the bug**
You can give the merchant a job.

**To Reproduce**
1. Get a job token
2. Shift right click with it on the merchant

**Expected behavior**
Nothing

**Screenshots**

** Server/Location **
What server were you playing on? Main 2
What are the world coordinates of your town hall marker? 7122 6796

**Additional context**
I didn't have any nomads that day

**Comment by Tab-160** [comment]
In 1.0.15, using a token from creative crashes the game. Using a token from the tradesmen converts the merchant. Both of these are in singleplayer.

**Comment by TangoTek** [comment]
Fixed the crash and the profession assignment.  Thanks!
