### ISSUE TITLE
Dissapearing buckets

### ISSUE THREAD

**Issue by Getraaa** [TangoTek/TekTopia-Community#119]
I dont know if this is a bug but when a chef uses a bucket of milk he doesnt bring back an empty bucket.

**Comment by ThomasBerends** [comment]
Does the bucket stay in his inventory or does it disappear?

**Comment by Getraaa** [comment]
> Does the bucket stay in his inventory or does it disappear?

It just disappears

**Comment by JohnyDL** [comment]
I'd say that was a bug with the way the recipe is handled by the mod since Vanilla would leave the empty bucket in the crafting grid

**Comment by TangoTek** [comment]
Somehow I never considered this. I updated the recipe to return a bucket to the chef.  The chef will now deliver empty buckets to storage for reuse.  This will save a LOT of iron.  Thanks!
