### ISSUE TITLE
Rancher is requesting an untextured item

### ISSUE THREAD

**Issue by LinaBoeckwurm** [TangoTek/TekTopia-Community#121]
My rancher is just standing still, requesting an item, but I don't know what because it doesn't show an icon

![2019-05-28_14 04 21](https://user-images.githubusercontent.com/28556423/58476760-4612b800-8141-11e9-9a6b-5d3e6f608ea9.png)

**Comment by TangoTek** [comment]
chicken_seed.png needed to be chicken_seeds.png

Thanks Lina!
