### ISSUE TITLE
Blacksmith crafts a non-villager item

### ISSUE THREAD

**Issue by Getraaa** [TangoTek/TekTopia-Community#122]
Blacksmith crafts a non-villager item so they still breaks faster then the special villager item.

**Comment by joerkig** [comment]
> 
> 
> Blacksmith crafts a non-villager item so they still breaks faster then the special villager item.

If the blacksmith is using non-villager items to craft the stuff they will count as non villager items.
To get him to craft villager items the ingredients have to be villager items as well.

**Comment by Getraaa** [comment]
> > Blacksmith crafts a non-villager item so they still breaks faster then the special villager item.
> 
> If the blacksmith is using non-villager items to craft the stuff they will count as non villager items.
> To get him to craft villager items the ingredients have to be villager items as well.

Sorry my fault, forgot that i had non-villager iron ingots xD

**Comment by joerkig** [comment]
> > > Blacksmith crafts a non-villager item so they still breaks faster then the special villager item.
> > 
> > 
> > If the blacksmith is using non-villager items to craft the stuff they will count as non villager items.
> > To get him to craft villager items the ingredients have to be villager items as well.
> 
> Sorry my fault, forgot that i had non-villager iron ingots xD

Guess this one can be closed then :P

**Comment by JohnyDL** [comment]
*would close it if I had permissions but only Getraaa and Tango Can I think*
