### ISSUE TITLE
Suggestion: Merchant buys saplings

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#126]
After a while of working the lumberjack will start filling chests with saplings which will have no value or use once village is established.

If the merchant bought them even if a stack for an emerald would prevent overstocking of saplings

**Comment by JohnyDL** [comment]
Or sapplings used as fuels? if more than one stack of each

**Comment by IridescentShadow** [comment]
This would be amazing. I've tossed probably 50 stacks of saplings into lava just to free up space in storage

**Comment by TangoTek** [comment]
I made the lumberjack no longer deliver saplings to storage. He will no longer pick them up if he has 60 of that type.
