### ISSUE TITLE
Female villagers dream about becoming male

### ISSUE THREAD

**Issue by IridescentShadow** [TangoTek/TekTopia-Community#128]
**Describe the bug**
While sleeping, the body texture of certain female villagers switches to the male texture. Arms do not seem to be affected.

**To Reproduce**
1. Watch your villagers while they sleep
2. Observe odd behavior as shown in the screenshots below

**Expected behavior**
Villagers should maintain the correct textures while sleeping

**Screenshots**
![2019-05-27_20 24 06](https://user-images.githubusercontent.com/7838663/58493549-2ed3ca80-8141-11e9-8db5-5247ba8e8eaa.png)
![2019-05-27_20 25 47](https://user-images.githubusercontent.com/7838663/58493551-2ed3ca80-8141-11e9-9ffe-369771465c2f.png)

** Server/Location **
SP, but can share world file if needed

**Additional context**
 I observed this with a miner and a rancher. It's possible that other types do it as well.

**Comment by TangoTek** [comment]
That's not a texture swap, thats two villagers in the same bed.  Not sure on this one yet.

**Comment by IridescentShadow** [comment]
Ahhhh, okay. I wasn't sure exactly what I was looking at

**Comment by IridescentShadow** [comment]
Closing as duplicate of https://github.com/TangoTek/TekTopia-Community/issues/92
