### ISSUE TITLE
Miners are not mining Lapis

### ISSUE THREAD

**Issue by GeneralPatton82** [TangoTek/TekTopia-Community#129]
**Describe the bug**
Myt miner skipped lapis ore in the mineshaft

**To Reproduce**
1. Create a mineshaft that has lapis ore
2. Wait for the miner to mine the mineshaft
3. Observe that the lapis was not mined

**Expected behavior**
Miner should mine the lapis ore

**Screenshots**
![2019-05-28_12 05 33](https://user-images.githubusercontent.com/5290865/58498208-2ed4ca00-8143-11e9-896a-a94dc5d50187.png)

** Server/Location **
Town Hall Marker: -7085 71 9434 (General Cantalompe)
Lapis Ore Location: -7062 11 9449
Survival Server #2

**Comment by JohnyDL** [comment]
yeah that might be useful for enchanters
