### ISSUE TITLE
Suggestion: Merchant Balancing

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#133]
**Describe the bug**
There are certain items that by the nature of the game, are acquired more often then other. like wool. The Merchant should be re-balanced to prioritize these items more often. I believe the Merchant has only offered the Wool trade two or three times.

Casa de Pikachu
![2019-05-28_20 07 35](https://user-images.githubusercontent.com/49371154/58505359-aaa33680-8184-11e9-88d7-2d08aedd1126.png)

** Server/Location **
What If 1

**Comment by Sobertron** [comment]
Addition: Redstone might also be an issue. 
![2019-05-28_20 12 04](https://user-images.githubusercontent.com/49371154/58505459-e807c400-8184-11e9-8eeb-1b6bb9833238.png)

**Comment by IridescentShadow** [comment]
I agree on Redstone since he buys it in stacks of 16

**Comment by JohnyDL** [comment]
Yeah, I have an Egg problem myself....
I'm also thinking the number of trades the merchant can do should be a little more balanced? if you have a large village you might be able to make 80 redstone per day and so you'd need that trade every day to get rid of it all. 

Something that might be cool is if you could buy a marker from a merchant after every 50 trades that you can put on a chest in your town hall where you can put your items in that chest and he then auto trades for you (only to make the player emeralds), again especially useful for large villages.

**Comment by TangoTek** [comment]
I've increased the appearance weight of wool and redstone.

However, I think the real issue here is that you are just getting too much of those items. Even if the merchant was to offer that trade, you'd quickly bottom out his economy on that item and he's stop offering it anyway.  

Regarding Johnny's suggestion of more trades. I have something planned for larger villages.
