### ISSUE TITLE
Blacksmith won't make shears

### ISSUE THREAD

**Issue by IridescentShadow** [TangoTek/TekTopia-Community#134]
**Describe the bug**
My ranchers frequently show icons asking for shears, but the blacksmiths never make shears.

**To Reproduce**
1. Add a rancher and blacksmith
2. Populate sheep pen
3. Notice symbols where ranchers request shears that are never made

**Expected behavior**
Blacksmiths should make the items that villagers want

** Server/Location **
SP, can send world file if needed

**Comment by Hedkracka** [comment]
My smith has made 5 buckets, but no sheers

**Comment by LinaBoeckwurm** [comment]
I haven't seen mine make any shears either, in the .18 version.

**Comment by JohnyDL** [comment]
They are just low in the blacksmith queue, like #149 and #163 it'd be nice if they worked the list either more randomly or with more attention to the village as a whole, we don't need another chest plate of any kind right this second cause every guard has one and/or the enchanters have enchanted chest plates to return to storage, so make something that is in demand.

**Comment by IridescentShadow** [comment]
I've finally seen a bucket but still no shears, so I've modified the title accordingly. 3 blacksmiths working from 4 miners

**Comment by IridescentShadow** [comment]
I'm not sure at what point it was fixed, but the blacksmith now crafts both buckets and shears in the 1.0.51 jar
