### ISSUE TITLE
Balancing: Druid levels

### ISSUE THREAD

**Issue by tomerorian** [TangoTek/TekTopia-Community#136]
The druid seems to level up too fast, it has so much to do and gets levels quickly from those things.
My druid got to level 100 while the rest of my village is only around 20-30.

Suggestion: Decrease the chance of druid leveling up

**Comment by TangoTek** [comment]
Fixed this.

**Comment by JohnyDL** [comment]
I'm not sure I agree druids level up too fast but that might just be my one experience #213 Maybe generally Villagers should level a max of once per day? 100 days is 2000 minutes is 33:40 of gameplay to get level 100 if you're lucky I have made other suggestions about how to balance experience gain too though and I know not all the ideas are compatible
