### ISSUE TITLE
Cook does not deposit cooked chicken

### ISSUE THREAD

**Issue by LOL-Nation** [TangoTek/TekTopia-Community#137]
**Describe the bug**
Chef does not deliver cooked chicken to storage. my chef has delivered everything else so far but is just holding 36 cooked chicken when she has extra food she is eating already,

**To Reproduce**
1. Put chicken in furnace for the chef
2. When chef takes chicken out, it will be cooked villager chicken
3. Chef will not deliver cooked chicken

**Expected behavior**
To deliver chicken

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Tektopia Server 2
What are the world coordinates of your town hall marker? 4500 3500

**Additional context**
I did not put villager chicken in the furnace, but it is villager chicken when she takes it out. I do not think this is the reason she can not deliver it tho because it works with potatoes I give her along with other meats.

**Comment by KeyokeDiacherus** [comment]
Same thing has been happening with our chef as well (Donkey-pichu, (2681, 116, -8673))

**Comment by TangoTek** [comment]
Sure enough I forgot to add it to the list.  Thank you!  Great find!
