### ISSUE TITLE
Butchers may need balancing a bit...

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#140]
**Describe the bug**
Not a bug so much... Our butcher has levelled from 15 to 69 in the space of about 5 MC days..

**To Reproduce**
N/A

**Expected behavior**
I'd expect them to level a LOT slower, in line with the other professions

**Comment by JohnyDL** [comment]
What level is their knowledge stat?
Where are you on the servers so Tango can check it out?

**Comment by TangoTek** [comment]
I cut the level rate by 50%. I'll keep my eye on it.  Thanks!
