### ISSUE TITLE
Library is OP

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#144]
**Describe the bug**
Villagers gain intelligence very, very fast in the library. Causing them to level up very fast. We currently have a butcher who is approaching level 80 and has over 80 intelligence. 

**Expected behavior**
I think the best thing to do is scale the effectiveness of the library. If they have low intelligence they gain it fast by reading books but then it be progressively more and more difficult to gain intelligence.

**Screenshots**
![2019-05-28_22 52 44](https://user-images.githubusercontent.com/49371154/58515843-0cbc6580-819e-11e9-8cd5-39c56c1ea1de.png)

** Server/Location **
What If 1
X: -3716, Y: 72, Z: 2019

**Comment by TangoTek** [comment]
I really appreciate this feedback. Most players would never admit something was OP.  Thanks!
Love the idea of escalating difficulty based on current intelligence.
Now at int 0 the rates will be only slightly higher than they were.  At higher intelligence the rates are MUCH slower.
