### ISSUE TITLE
Merchants can't open doors or gates

### ISSUE THREAD

**Issue by twmeehan** [TangoTek/TekTopia-Community#146]
Minor Bug:
Merchants can't open gates or doors and will continue trying to go through them even though they are not open.

To Reproduce:
1. Wait for the merchant to spawn
2. Watch the merchant as he wanders your village and can't open doors or gates

Expected Behavior:
Merchants can open doors and gates like any other villager

Screenshots:
![2019-05-28_11 27 21](https://user-images.githubusercontent.com/43288159/58518591-c9ea9580-817d-11e9-86e4-13f5d2f4ec76.png)
![2019-05-28_16 32 39](https://user-images.githubusercontent.com/43288159/58518631-e5ee3700-817d-11e9-90a8-cc499e6e973a.png)

Location:
A creative singleplayer world.

Additional Context:
Sometimes the merchant will stop attempting to go through a door or gate and wander off if he has been there long enough. Otherwise, he waits until a player or another villager opens the door.

**Comment by TangoTek** [comment]
I originally did this on purpose to keep the merchant from wandering through the buildings. (He doesn't belong in peoples houses!).  However, this is causing him to get stuck too much. So I'll enable door opening again.  Thank you!

**Comment by EnteredTie581** [comment]
We have observed our merchant, on several occasions, not being able to open fence gates to enter our village.

**Comment by tomerorian** [comment]
@EnteredTie581 If I recall correctly there were no new version releases since this comment. So I assume this will be actually fixed in the next version to come

**Comment by JamesTDue** [comment]
Sorry Boss, but it looks like Merchant is still struggling with doors
![2019-06-07_14 32 00](https://user-images.githubusercontent.com/51033015/59107522-bd5dfe00-8930-11e9-9b36-b7eb37aa6d59.png)
![2019-06-07_12 50 31](https://user-images.githubusercontent.com/51033015/59107535-c51da280-8930-11e9-8cab-4ab73b0b665c.png)

**Comment by mrhyde1st** [comment]
Tango, not sure if as a compromise he could do gates but not doors if you don't want him going in buildings?
