### ISSUE TITLE
Frozen villagers

### ISSUE THREAD

**Issue by twmeehan** [TangoTek/TekTopia-Community#150]
Major Bug:
Villagers seem to often freeze up often and remain this way for quite a while (sometimes for whole days). Although this bug has tapered off recently (odd since I've been playing on 1.0.11 the whole time while testing), there still seem to be cases where the whole village will freeze for like 10 seconds before moving again. When everyone freezes together, they often pick new tasks after unfreezing. For example, a woodcutter may freeze while walking towards a tree, and when unfrozen he may choose to go return his items to the chest instead. 

When a villager freezes by itself it will often remain there for quite a while. (They often don't return to bed, but when the player sleeps they start moving again). I think this may be a separate issue from the whole village freezing. 

To Reproduce:
1. Create a village
2. Watch villagers freeze and unfreeze

Expected behavior:
Villagers will always be doing something and will not randomly freeze.

Screenshots:

![2019-05-28_12 23 01](https://user-images.githubusercontent.com/43288159/58518989-97419c80-817f-11e9-9332-e0b7de5cb304.png)
![2019-05-28_11 52 53](https://user-images.githubusercontent.com/43288159/58518999-a3c5f500-817f-11e9-87fe-3a0808fc6b34.png)
![2019-05-28_13 40 01](https://user-images.githubusercontent.com/43288159/58519024-ba6c4c00-817f-11e9-87e1-40b9728091a0.png)

Location:
Creative singleplayer world.

**Comment by Hedkracka** [comment]
I have noticed similar behaviour in smp too, in my village i currently have 4 villages doing standing in the open at night, while there are beds unslept in(even allowing for the guards beds)

**Comment by TangoTek** [comment]
I'm fairly certain this was related to having chests in storage off the ground. Let me know if you see it any more after 1.0.17

Thanks!
