### ISSUE TITLE
Bug: Lumberjack remote chopping

### ISSUE THREAD

**Issue by tomerorian** [TangoTek/TekTopia-Community#154]
**Describe the bug**
The lumberjack will "keep chopping" at a tree remotely after its been scared by a zombie.

**To Reproduce**
1. Get a lumberjack to start chopping a tree
2. Spawn a zombie
3. Lumberjack runs away
4. Once the lumberjack is far, kill the zombie
5. The tree will suddenly be chopped and replanted without the lumberjack being close to it

**Comment by tomerorian** [comment]
actually. it seems the lumberjack is able to chop from far away regardless of the zombie. I wanted to test some other theory and placed lots of 1 durability axes in the storage for the lumberjack. 
He takes an axe, start walking and the axe breaks. after a few rounds of that the tree just breaks...

**Comment by tomerorian** [comment]
Another thing, if you do the 1 durability test with 2 trees the lumberjack will in 100% of the tests I did do the following:
1. Break the tree remotely
2. Go to the trees
3. Plant a sapling instead of the 2nd tree's base

So it seems the lumberjack has a bug while planting a sapling too, it can be planted in the wrong place

**Comment by TangoTek** [comment]
Finally got this one I think. Its been lurking forever.  Thanks!

**Comment by tomerorian** [comment]
Confirming that all of the above no longer happen since 1.0.18 \o/
