### ISSUE TITLE
Farmers not farming crops

### ISSUE THREAD

**Issue by Galarn20** [TangoTek/TekTopia-Community#159]
**Describe the bug**
I have two farmers and neither of them will farm the crops (carrots and wheat), they farm sugarcane, my first farmer i had when i started had no problem.

**To Reproduce**
1. Get a farmer.
2. plant some crops and wait for them to grow.
3. get angry because your farmers are on a strike or are just lazy.

**Expected behavior**
for the farmers to do there job and collect the crops and replant.

**Screenshots**
NA

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? What if #2
What are the world coordinates of your town hall marker? -5177, 65, 8113

**Additional context**

**Comment by JohnyDL** [comment]
I have the same issue of the farmers not working a field correctly (harvesting plants but not replanting them but I think it's cause my felids are too big
![2019-05-28_23 06 34](https://user-images.githubusercontent.com/5202568/58550170-175e1580-8205-11e9-84a4-16daeda7657b.png)

**Comment by Galarn20** [comment]
Update, it turns out that the villages have trouble parthing over trapdoors and carpet, i had carpet over the water, So new bug for your tango, Villages have trouble parthing over trapdoors and carpet.

**Comment by JohnyDL** [comment]
Galarn Carpets were a known issue in Lets Dev Video 2, and partial block problems are covered in #51 ;)
