### ISSUE TITLE
Blacksmith Keeping Charcoal

### ISSUE THREAD

**Issue by pendl3** [TangoTek/TekTopia-Community#161]
Blacksmith is keeping the logs smelted into charcoal in their inventory and not returning them to storage
What if server 1 

![Blacksmith](https://user-images.githubusercontent.com/50293594/58550782-71130f80-8206-11e9-914e-e729f5e08791.png)

**Comment by JohnyDL** [comment]
this may be related to all the other issues on #65 or may be related to #81 which is now fixed

**Comment by Hedkracka** [comment]
![2019-05-29_17 04 36](https://user-images.githubusercontent.com/20891568/58572716-1c868900-8234-11e9-8d8b-54e1fdf51ebe.png)
nah still keeping charcoal

**Comment by TangoTek** [comment]
Fixed. Thanks.
