### ISSUE TITLE
Lumberjack only chops one tree type

### ISSUE THREAD

**Issue by MilesKid** [TangoTek/TekTopia-Community#162]
**Describe the bug**
When a lumber jack originally selects a tree type, they won't chop down any other tree types.  If you remove all of that type they are stuck and don't know what to do.

**To Reproduce**
Create a lumberjack
They chop down a type of tree (oak)
Remove all of that tree type in an 80 block radius of TH
Lumberjack stops pathfinding even with other trees in the area.

**Expected behavior**
I expect the lumber jacks to chop down any type of tree in the area.

** Server/Location **
What server were you playing on? Server 2
What are the world coordinates of your town hall marker? 3811 x -5175 (MilesVille)

**Comment by JohnyDL** [comment]
They won't chop down 2x2 trees at all or accacia due to the way trees are currently detected but they should work with birch, oak, single, spruce and single jungle (without branches) what trees are you trying to chop?

**Comment by Hedkracka** [comment]
i dont have this issue, my lumberjacks chop oak spruce birch and jungle 1x1s.
server1

**Comment by MilesKid** [comment]
@JohnyDL That must be the problem.  I have "acha-cha" trees.  I will have to go find some other saplings and plant them so I can have variety.  The interesting thing is one or two of them have Acacia saplings and logs in their inventories.

**Comment by Hedkracka** [comment]
the L'jacks will pick logs and saplings if on the floor, just dont expect them to drop them off, one of mine still has a few white logs on him from the first day

**Comment by JohnyDL** [comment]
they also do register the accacia trees with 5 logs and a canopy cause they pass the test but they're like 1/8 accacia trees you eventually don't have any of them anymore
