### ISSUE TITLE
Farmer picking up oak and don't drop it off

### ISSUE THREAD

**Issue by Taggerung179** [TangoTek/TekTopia-Community#181]
**Describe the bug**
Farmer has somehow picked up logs and does not drop them off.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
Whatif Server 1
What are the world coordinates of your town hall marker?

**Additional context**
I've noticed that for quite some time, about 12-18 hrs, one of my farmers has picked up some villager oak logs, which I believe it has no use for. Said oak logs have remained in farmer's invatory and has yet to be dropped into storage.
![2019-05-29_15 24 07](https://user-images.githubusercontent.com/51178873/58595579-0376db80-8226-11e9-82f8-df38f7101467.png)

**Comment by JohnyDL** [comment]
is this a lumberjack that converted to a farmer?
Possibly related to #65

**Comment by draelu** [comment]
they also fill up with saplings now

**Comment by JohnyDL** [comment]
filling up to 60 with sapplings is normal for 1.0.18 but they shouldn't fill more than that if you see it report it as a separate bug

**Comment by TangoTek** [comment]
This will be fixed by the new pick up/drop off system coming.
