### ISSUE TITLE
Bug/Suggestion For /spawn in nether

### ISSUE THREAD

**Issue by LOL-Nation** [TangoTek/TekTopia-Community#196]
**Describe the bug**
If you use /spawn in the nether traps you in a room with unbreakable blocks. You can not break any of the blocks. The only ways to get out would be /tpa and /home, but if you dont have a set home and no one else is on, you will be trapped until you starve.
**To Reproduce**
1. Go to Nether
2. Type "/spawn"

**Expected behavior**
Be able to leave without a command.

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? What If Server 2
What are the world coordinates of your town hall marker? 4500 3500

**Comment by TangoTek** [comment]
This seems to have nothing to do with the TekTopia mod.
