### ISSUE TITLE
Husks

### ISSUE THREAD

**Issue by Hawaiiwong** [TangoTek/TekTopia-Community#198]
**Describe the bug**
Weird Husk issues.

**To Reproduce**
I spawned in a few husks (on dev server). The guards don't seem to agro on the Husks like they used to. Also it takes the husks some time to agro on the guards too. This does not seem to be an issue with regular zombies.

Was not an issue before 1.0.18
Town hall marker - 5579/66/843

**Comment by TangoTek** [comment]
This is fixed. I derped.
