### ISSUE TITLE
Suggestion: Villager Exp bar

### ISSUE THREAD

**Issue by luvzdeidara** [TangoTek/TekTopia-Community#205]
I'd love to possibly see experience bars added to the villager UI. 
I've recently started a new Single player village and have played through 10 in game Days but only 1 of my 3 farmers visibly has leveled up. 

I'd love to be able to interface with them to see how far along they are to leveling up in their current profession.

**Comment by JohnyDL** [comment]
XP to current job level up would be really cool they also need to level up jobs a little more like they level up knowledge, fast low levels slower higher levels, I think level 25-40 should be easy to reach within 10-20 hours of play but 100 should take much much longer.

**Comment by TangoTek** [comment]
There is no progress toward next level.  Leveling up is a weight random chance depending on the task they perform.

**Comment by JohnyDL** [comment]
I did not know this I thought there was a chance to fill an internal exp bar with some exps this might eventually be a source of a few balancing problems, balancing the lengths of bars is easier than probabilities
