### ISSUE TITLE
Villagers in tavern not using chairs at all.

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#211]
**Describe the bug**
Our villagers go into the tavern and sometimes sit on the floor and enjoy a beer, but never use the many chairs around the place. 

**To Reproduce**
1. Go to tavern
2. Click on wait for villagers to come use the tavern
3. Villagers come in, but don't use chairs

**Expected behavior**
Expected the villagers to use the chairs to give it a much nicer 'sitting together' vibe...

**Screenshots**
https://cdn.discordapp.com/attachments/506195290143981581/583762144118702080/2019-05-30_21.58.55.png

** Server/Location **
Main 1
X: -3716, Y: 72, Z: 2019

**Comment by JohnyDL** [comment]
This is a bug introduced in 1.0.18 I think since it did work for me in previous versions and now isn't 
![2019-05-30_23 52 55](https://user-images.githubusercontent.com/5202568/58670206-242e5680-8336-11e9-95c4-9a1cc0b947e6.png)

**Comment by LinaBoeckwurm** [comment]
I think this might be related to bug #194.
In my singleplayer world the villagers wouldn't sit down either, one time one of them even cheered with a mug while standing. 
I've seen one person sit, and that one sat in the ground. 

![2019-05-31_01 27 04](https://user-images.githubusercontent.com/28556423/58671776-538f9400-8333-11e9-9c15-ae84fdb6fdcf.png)

**Comment by JohnyDL** [comment]
Yours relates to 194 but this thead has the bards staying up after 'midnight' when everyone went to sleep 2000 ticks earlier

**Comment by TangoTek** [comment]
Fixed. Thank you

**Comment by RensSwag2001** [comment]
Request to open this one again..
It happened to me today! Tektopia version 1.0.37
My villagers dont use the chairs and some go sit on the ground/table
Screen: 
![2019-06-14_18 50 34](https://user-images.githubusercontent.com/51168774/59524869-39c68300-8ed5-11e9-97e2-1702a097a928.png)
