### ISSUE TITLE
Armor/sword does not show up in guard's inventory

### ISSUE THREAD

**Issue by LinaBoeckwurm** [TangoTek/TekTopia-Community#214]
Unlike miners, lumberjacks and farmers, guards do show the sword they are currently using in their inventory, nor do they show their armor there. 
I get that they've technically got it "equiped" but the other villagers also show their tools even though they're in use. 
I would love to be able to check the durability on those items. 

picture:my iron/diamond clad guard, with non of those items in his inventory.
![2019-05-30_23 36 53](https://user-images.githubusercontent.com/28556423/58667450-934f7f00-8325-11e9-8ef1-68a1ece4c1c6.png)

**Comment by JohnyDL** [comment]
Just like the player the villagers have separate (hidden) slots for them

**Comment by TangoTek** [comment]
Yea, I'd have to make a new armor slot UI for the guards.  This isn't something that will be happening soon unfortunately.
