### ISSUE TITLE
Tokens no longer stack properly

### ISSUE THREAD

**Issue by LinaBoeckwurm** [TangoTek/TekTopia-Community#222]
When I buy multiple tokens, both jobs and buildings, they longer stack with tokens of the same kind. This is especially annoying with stuff like the mine shafts, of which I tend to buy multiple at a time. But it's also for job professions.
Before the update multiple tokens from the same village tended to stack with themselves.

**Comment by LinaBoeckwurm** [comment]
I thought this was a bug, after reading the patch notes I realised that *this* is the intended way it's supposed to work and it previously was a bug.

**Comment by JohnyDL** [comment]
:) wish I could Label these things **Not a bug** but actually good to keep a reference around for future peeps ^_^
