### ISSUE TITLE
Lumberjack inventory jammed with saplings.

### ISSUE THREAD

**Issue by Geex204** [TangoTek/TekTopia-Community#230]
**Describe the bug**
Simply said the lumberjack isn't dropping of any saplings.

**To Reproduce**
1. Let him/her chop down a tree;
2. Follow him/her to the storage to drop off;
3. Check his Inventory after that;
4. Repeat 1-3 and realize that no saplings get to your storage and his/her inventory has several stacks of saplings.

**Expected behavior**
Drop off not needed saplings into storage.

**Screenshots**
![2019-05-31_18 17 32](https://user-images.githubusercontent.com/51030223/58727963-0b7d7980-83e6-11e9-97c2-cadf343939f9.png)

** Server/Location **
Whaf if - Server 1 - Survival
XYZ:  -6875 / 79 / 4389

**Additional context**
They haven't reached a completly filled inventory yet but i fear they become useless if that happens since they can't pick up the wood they chopped.

**Comment by JohnyDL** [comment]
They do not deliver saplings to storage as of 1.0.18 but they should stop collecting them (or maybe should start voiding them if they have >60 of that type see #126 and the patch notes: 
[- Lumberjacks will no longer deliver saplings to storage. They will stop picking them up when they have a good amount.](https://discordapp.com/channels/184801826103754752/581282206425808896/583380320947142772)
if they're still collecting them this is a bug but they might have collected these before the update and are now unable to deliver them and they will slowly run down over time, please keep us informed with more screenshots especially if they pick up even more.

**Comment by MilesKid** [comment]
All my lumberjacks have this problem and it has been since 1.0.18.  It also seems like they don't plant the birch after chopping it down.  They birch saplings and birch logs but I have never gotten a delivery to the storage.
![sapling hoarder](https://user-images.githubusercontent.com/51030776/58740541-f05b3b80-83de-11e9-9cd8-357011c60b0b.PNG)

**Comment by JohnyDL** [comment]
I unfortunately still cannot corroborate this one for myself (yet)

Miles which server are you on and where's your village? it might help Tango

I'm thinking this might be an update bug, it worked fine in 1.0.17 it works fine in 1.0.18 but it didn't like upgrading between the two if your villager had more than the max items already and that's caused an error

or it's two different parts of the code that pick up saplings one is fixed and one is not.

**Comment by MilesKid** [comment]
Sever 2 : MilesVille: 3832 86 -5174

**Comment by TangoTek** [comment]
They now will delete overstock of an individual sapling type over 60.

**Comment by Geex204** [comment]
I just lost a high level lumberjack to starvation because she wasn't able to pick up food since her inventory was full of saplings. Does the change not affect preupdate recruited lumberjacks? Because this is still happening i'm about to lose all my lumberjacks which would be kind of a gamebreaker since they all level up pretty far 'til now.

**Comment by JohnyDL** [comment]
it'll be a 1.0.19 when it gets released there's nothing much you can do before then other than hitting them with healing potions
