### ISSUE TITLE
Guards Don't Sleep Unless 0 Happiness

### ISSUE THREAD

**Issue by blondetheftauto** [TangoTek/TekTopia-Community#234]
The Bug: My guards refuse to go to sleep during the day (I have two guards), even though I have empty beds, and they have beds that are claimed. They will only sleep unless they reach 0 happiness. Because they will not sleep, their happiness levels are very low, compared to the rest of my village.

1. Go to my village (blondeburg, coords on the sign at spawn on the back).
2. Wait until daytime.
3. Watch as neither of my guards go to bed.

Expected Behavior
For them to go to bed in the day.

Server Location: Server 1 (Survival).
What are the world coordinates of your town hall marker? 5,941, 75, 6,707

Additional context
Both the mods and Tango are doing such a fantastic job with this village mod and with all the moving parts! <3

**Comment by JohnyDL** [comment]
is this related to the not having a guard post bug? might be related to #63

**Comment by blondetheftauto** [comment]
I have two guard posts, but it does sound similar.

**Comment by JohnyDL** [comment]
it might be related to the Cleric bug #212 too, does having more guards help? can you do that? if 2 posts maybe you need 3 guards to have one at each post and the third to sleep

**Comment by blondetheftauto** [comment]
I haven't been able to get more guards as of yet--I just got the second guard earlier this morning. Will attempt to update when I get a third guard.

**Comment by JohnyDL** [comment]
or for now 1 post? that would do the same trick one post 1 guard awake 1 sleeping? it's not perfect but it'd let us see if this helps the bug

**Comment by blondetheftauto** [comment]
I got another guard post and the issue seemed to have fixed itself--both guards are back up to nearly 100 happiness again!

**Comment by LinaBoeckwurm** [comment]
that might have solved the issue, but I do think that it's still a problem that should be looked at.
