### ISSUE TITLE
Suggestion: Town Achievements

### ISSUE THREAD

**Issue by Magleose** [TangoTek/TekTopia-Community#236]
I would love to see a achievement tree for your mod, like the existing achievement system that exists in the game. Goals are fun :)

**Comment by JohnyDL** [comment]
You could make your own advancement resource pack you know Magleose ;) if someone made one then I'd probably play it and Tango might include it, [Here's a link to a tutorial](https://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/commands-command-blocks-and/2809368-1-12-custom-advancements-aka-achievements)

**Comment by TangoTek** [comment]
Just don't have time for this, sorry.
