### ISSUE TITLE
Gaurds don't attack Zombie villagers

### ISSUE THREAD

**Issue by Magleose** [TangoTek/TekTopia-Community#238]
**Describe the bug**
Guards do not attack zombie villagers.

**To Reproduce**
1. Obtain Zombie Villager
2. kite past guard
3. See error

**Expected behavior**
I expect the guard to attack and kill the zombie villager

**Screenshots**
![2019-05-31_21 44 21](https://user-images.githubusercontent.com/37353615/58741961-c9583600-83ed-11e9-8dda-1362b32fde73.png)

** Server/Location **
Main(Survival) 2
1357 / 70 / 5261
**Additional context**

**Comment by JohnyDL** [comment]
The zombie might not be in detection range and the Zombie doesn't seem to be attacking the villagers either.

**Comment by TangoTek** [comment]
Fixed. Thank you
