### ISSUE TITLE
Villager hitbox doesn't change on sleep

### ISSUE THREAD

**Issue by tomerorian** [TangoTek/TekTopia-Community#24]
I assume this is probably known, but just in case it isn't

**Describe the bug**
When a villager goes to sleep the hitbox stays as if it is still standing on the bed

**To Reproduce**

**Expected behavior**
If its even possible it would probably be more realistic if the hitbox also become horizontal

**Screenshots**
![image](https://user-images.githubusercontent.com/2083414/58375969-0cd32000-7f68-11e9-9fe2-58decf740912.png)

**Comment by TangoTek** [comment]
as intended for now.  Not sure I'll get the time to change this. Its of little importance.
