### ISSUE TITLE
Guard "Sleepwalking"

### ISSUE THREAD

**Issue by Magleose** [TangoTek/TekTopia-Community#248]
**Describe the bug**
Meet Maya Kelmore. She sleeps on duty. She also displays the wrong animation from time to time while pathing. It appears she is sliding along on her back. She has also been exhibiting some strange behavior. There were 2 of her at one point. One pathing around guarding, and one standing on her claimed bed. I could interact with both, they were identical, save for their different activities.

**To Reproduce**
1. Observe Myra
2. See error

**Expected behavior**
I expected Maya to be one villager, and to appear to stand while on duty, rather than lay down on the job

**Screenshots**

![2019-05-31_23 23 55](https://user-images.githubusercontent.com/37353615/58750253-0b20c500-845e-11e9-8b31-fcbf03177754.png)
![2019-05-31_23 24 05](https://user-images.githubusercontent.com/37353615/58750256-0e1bb580-845e-11e9-90c5-ec242ff12ba9.png)

** Server/Location **
Main(Survival) 2
1357 / 70 / 5261

**Additional context**

**Comment by Magleose** [comment]
Annnd I just caught my nitwit doing it too

![2019-05-31_23 38 41](https://user-images.githubusercontent.com/37353615/58755890-f9b9d600-84ba-11e9-8e8b-081418b503d8.png)
![2019-05-31_23 38 52](https://user-images.githubusercontent.com/37353615/58755891-fc1c3000-84ba-11e9-8e49-545791b7fbe1.png)

**Comment by TangoTek** [comment]
Fixed in 1.0.58
