### ISSUE TITLE
6 person home suddenly stopped being registered

### ISSUE THREAD

**Issue by LinaBoeckwurm** [TangoTek/TekTopia-Community#252]
This home (see picture down) has been my first 6 person home and had already been accepted as such. Multiple villagers have slept in this house, and hearts have spawned in here. 
Suddenly, it stopped being registered, despite me not changing anything except maybe adding a path to the side without a door. But even that path has been there several in game days before it suddenly stopped being registered.
I've tried rebuying the token, but that doesn't seem to work.
I've tried restarting the world, and that doesn't seem to work either. 
this is the 1.0.18 version. 
I know this is quite a unique design of a house (glass floor, no walls. more than two doors next to each other) so if any of those factors are known to  give problems I would like to know as well.

![2019-06-01_21 16 18](https://user-images.githubusercontent.com/28556423/58752704-2235d600-84a3-11e9-8175-023aee8fd19c.png)

**Comment by LinaBoeckwurm** [comment]
Update: when the night fell the home seems to have registered itself again. It did switch a few times between yellow and red beds, so it really does seem to be a bit buggy, but it seems to have settled on being an actual home again. 
I have changed literally nothing since the last screenshot.
![2019-06-01_21 30 55](https://user-images.githubusercontent.com/28556423/58752772-31695380-84a4-11e9-89e7-0ecd52ca46a6.png)

**Comment by JohnyDL** [comment]
This may sound stupid but there's a good chance that happened because of the tree in the first image chopped sown to be a sappling in the second, see #48, with no walls your house suddenly got much bigger when the sky was blocked out by the tree as there's no sanity checks on flooring.

**Comment by LinaBoeckwurm** [comment]
Yeah, that's probably it! and the tree farm that's attached to that tree definitely gives enough sky coverage that it would go over the maximum house size. 

In that case, I would like to add that water sources work as floor for the purpose of house size! 
Part of the reason I didn't think about that being a problem that I assumed that water wouldn't count.
I don't know whether that's intended behavior or not, but this issue is closed. 

![2019-06-02_01 24 33](https://user-images.githubusercontent.com/28556423/58754641-74d3ba00-84c4-11e9-8178-86bb8591a35d.png)
