### ISSUE TITLE
enchanter not dropping off enchanted gear

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#263]
**Describe the bug**
My enchanter has almost a full inventory, mostly of enchanted gear and tools (all low level ones as she is still low skilled herself)
As yet i have not seen her drop off to the chests a single piece of gear or tools that are enchanted, only books!

**Expected behavior**
Expect to see maybe 1 or 2 enchanted items on her that she has not dropped off

**Screenshots**
![2019-06-02_12 01 18](https://user-images.githubusercontent.com/20891568/58760343-51455980-852e-11e9-9392-f01f534564ff.png)

** Server/Location **
tektopia#1 
3826 68 9370

**Comment by Hedkracka** [comment]
duplicate issue, apparently fixed in next patch

**Comment by JohnyDL** [comment]
Duplicate of #186 #171 #102
