### ISSUE TITLE
Butcher has vanilla leather

### ISSUE THREAD

**Issue by ARocketEngineer** [TangoTek/TekTopia-Community#266]
Looking at my Buther's inventory, there are 2 stacks of 4 vanilla leather and 1 stack of TekTopia leather. 
![2019-06-02_11 36 56](https://user-images.githubusercontent.com/51294493/58763654-90be7680-852b-11e9-9315-9539ee0d5693.png)
![2019-06-02_11 36 58](https://user-images.githubusercontent.com/51294493/58763655-90be7680-852b-11e9-816c-b9d5f173e96b.png)

**Comment by JohnyDL** [comment]
Did he slay a vanilla cow rather than a villager cow?

**Comment by ARocketEngineer** [comment]
He had a stack of 4 TekTopia leather as well.

**Comment by JohnyDL** [comment]
If he's ever killed a vanilla cow he might still have vanilla leather, remember the first few cows you add to the village and any you breed rather than the villagers are vanilla cows

**Comment by ARocketEngineer** [comment]
OK. All the sheep and cows in that village died/got killed so not sure what happened. Will keep an eye on it going forward. This may tie in with them emptying their inventory then.

**Comment by JohnyDL** [comment]
Yup you're right might be part of the #65 bug and it might be fixed by Tango's overhaul of the drop system when that happens

**Comment by TangoTek** [comment]
I'm going to assume this was a non-villager cow
