### ISSUE TITLE
Gravestones for villagers

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#270]
**Describe the bug**
Not a bug.. It's a feature request/suggestion.

Gravestones.
We have talked about villager gravestones at length. We think it would be cool if villagers that died dropped a gravestone block. The gravestone would be similar to a sign, with custom written text, but not be editable by the player. Could include a bit about what killed the villager, his name, all sorts... Also the gravestone could be broken and moved, so a graveyard could be built. Functionality-wise, villagers could gain a little happiness from visiting the gravestones (counter intuitive?). You could get really complex and have further increased happiness if the villager visited the gravestone of a family member.

Further suggestions welcomed on the end of this thread.

Sham and Pikachu!

**Comment by JohnyDL** [comment]
They should also drop their items, some might die with stuff, it's still the player's responsibility to find the death spot and collect what they died with but I think they should drop items on death

**Comment by Magleose** [comment]
> They should also drop their items, some might die with stuff, it's still the player's responsibility to find the death spot and collect what they died with but I think they should drop items on death

Especially in the case of guards in early game, when the town isn't getting much iron and the player is also trying to scrape it together, having the possibility to retrieve some of these items would be helpful

**Comment by PunchAndDunk** [comment]
I have also spent a lot of time thinking about how Gravestones would be awesome. Although I think it would be better to build a graveyard that the Cleric would attend to, by weeding and maintaining the gravesites. To solve the Villagers items issues lost on death, having a death  chest in the graveyard may help with that. I think the graves should appear in the graveyard.  Also, my Cleric is always miserable for some reason. I think being able to give the cleric flowers should increase happiness!  The Cleric could then leave the flowers on the grave. One last thought would be to be able to use a "Heart" on a grave to resurrect a favorite villager. Maybe having the villager be fully functional is too OP, so having them start again as a child might be a nice "cooldown" period.

**Comment by Firenzic** [comment]
I absolutely love this idea! Maybe a dead villager item could be bought from the architect and crafted into a gravestone?

**Comment by Konyv** [comment]
This does seem really cool. 

Dropping items at death sounds great. Especially for guards. A lot of investment goes into their gear. 

The grave stone could drop like other items. This would prevent possible issues of the gravestone being placed oddly by the AI. 

If the gravestone does place itself (like many player gravestone mods) I think that an unmoved gravestone would cause a drop in happiness. They died there and you just left them? Depressing thought. 

*Class enhancement*
Giving cleric a graveyard sounds great. It gives them something to do outside fighting the undead. 

Collected gravestones could be placed in the graveyard and they could slowly spawn grass around themselves. 

Unkempt graveyards would reduce happiness, but well tended graveyards would boost happiness. It gives the villagers closure. 

Clerics would tend the graveyard breaking grass around gravestones and if a pot is placed in front of the gravestone they will place flowers. 

Technically, the graveyard wouldn't need a cleric to work, but then the player has to tend to it themselves.

**Comment by JohnyDL** [comment]
Grave stones could be ever lasting items like villager hearts and rather than hearts and chimes they get skulls and a funeral dirge XD this could be a better way to deal with an unmoved grave, and destroying the item would summon a necro for bad karma and well actually I think that the ability to summon the necro would kinda be interesting too.

**Comment by Konyv** [comment]
Haha. I like it. 

Gravestone placed outside graveyard could have a low spawn chance for undead. 

And if graveyards are two unkempt they could do the same. 

I figure the grass (and maybe mushrooms?) spawning would just be in the 3x3 area centered on the gravestone. 

Either the gravestone can check that area and if too many blocks are unkempt then it gets a spawn chance. 

Or the graveyard could check itself for a gravestone vs unkempt ration. If the unkempt gets too high then chance of undead spawning.

**Comment by Konyv** [comment]
For the gravestone in graveyard placement any block that neither grass nor mushrooms could spawn on would be an issue.

**Comment by TangoTek** [comment]
I like these ideas, but honestly it'll never happen. I need to wrap up the mod and this is lower priority
