### ISSUE TITLE
Architect Trade Locking

### ISSUE THREAD

**Issue by LOL-Nation** [TangoTek/TekTopia-Community#276]
**Describe the bug**
Bought 7 mineshaft tokens from the architect at once and the trade locked.

**To Reproduce**
1. Get town hall
2. Buy about 7 of the same tokens at once

**Expected behavior**
It will never lock

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Server 2
What are the world coordinates of your town hall marker? 4530 3500ish

**Additional context**
I noticed someone else reported this, but wrote another because that one said it was fixed.

**Comment by JohnyDL** [comment]
Not a Bug

The other report #52 was that it locked and you could never buy more tokens, the fix is that it never locks so you can always buy more of them for your village

**Comment by JohnyDL** [comment]
Yeah Duplicate of #52, but does the trade unlock when you close and open it? or after 1 minecraft day? the bug was about the trade being locked forever the fix might not be that you can but infinity in one go just that it always unlocks

**Comment by TangoTek** [comment]
Max trades have been bumped to essentially infinite in 1.0.21

**Comment by LOL-Nation** [comment]
It locks until the next day.

**Comment by LOL-Nation** [comment]
Have not tested in 1.0.21 though.
