### ISSUE TITLE
No Nomads or Merchants spawning

### ISSUE THREAD

**Issue by Accommodus** [TangoTek/TekTopia-Community#28]
**Describe the bug**
No merchants or nomads will spawn anywhere in my village. I have 0 villagers. My town hall and all my buildings are glowing. I get no path finding errors in the morning. I have never seen the merchant or the nomads spawn in my village.

**To Reproduce**
I do not believe I did anything specific to cause this to happen.

**Expected behavior**
The nomads should have came directly to my town hall with the merchant. I have 0 villagers so there should have been many nomads.

**Screenshots**

** Server/Location **
I am playing in the second server. My village's name is "Accommodum". It is at the coordinates of 147 64 4828

**Additional context**

**Comment by MilesKid** [comment]
Do you get notices at the beginning of the day that they are unable to locate your village?  I had that but eventually they found me.

**Comment by MilesKid** [comment]
I had one pack of nomads show up but they despawned before I could assign any tasks.  In the dev vids I thought it was said that one would get at least 1 Nomad if one had 0 villagers.  I have had several passes where they can't path find to the village and many minecraft mornings where I get nothing.   Not sure if it is a bug or just a playability issue.  My village name is MilesVille.
(also server 2)

**Comment by Accommodus** [comment]
UPDATE:
I was able to find one nomad just hanging around my village area. There is still no merchant, and the nomads do not come everyday.

**Comment by MilesKid** [comment]
I restarted my client and they started showing up regularly.
