### ISSUE TITLE
Guards don't attack all mobs.

### ISSUE THREAD

**Issue by Konyv** [TangoTek/TekTopia-Community#287]
**Describe the bug**
Guards ignore some mobs. Both of my guards were able to see this Creeper and spider and they walked right past them. 
In the second image the guard and creeper are screen walking past each other. 

**To Reproduce**
1. Have guards
2. Have not undead mobs

**Expected behavior**
Guards should be protecting the village from all mobs. 

![2019-06-03_00 08 19](https://user-images.githubusercontent.com/51104278/58817499-78189400-85f1-11e9-8e6c-454792adc8e9.png)
![2019-06-03_00 08 33](https://user-images.githubusercontent.com/51104278/58817500-78189400-85f1-11e9-92b8-0bc30351c32d.png)

** Server/Location **
what if server 1

**Comment by LinaBoeckwurm** [comment]
I actually am really happy that guards don't agro on creepers.
If you have guards fight creepers, the creepers are going to explode. And exploding creepers are a problem: they can easily destroy important paths/tokens/something else you didn't even realise was actually really important.

**Comment by Konyv** [comment]
Fair point for that. 

Alternative solution to help prevent this:



New Guard Function.

Torch placement. Guards already patrol the village. Adding the ability to detect light levels and place torches would be a huge help to make the village safer.

**Comment by JohnyDL** [comment]
Guards only care about Zombies and Necros at this point I don't think they'll care about Skele's until there's a ranged unit like an archer or there's dogs #265 and I agree with not making creepers explode, spiders/witches would be good if we ever have someone that makes potions, and lastly Endermen which might be a bad idea too

**Comment by SorcerorNobody** [comment]
It makes sense to me that guards only attack things that are a threat to the village. Non-zombie mobs don't attack villagers, so they aren't something that needs protecting against.

Aside from the **very** good reasons not to aggro creepers in particular, it's generally a good idea for them not to pick fights they don't need to. Yes, they might skill up from it, but it's also a needless risk of dying or being already damaged when a real threat arrives.

**Comment by TangoTek** [comment]
Working as it should for now

**Comment by Konyv** [comment]
Except these mobs are still a threat to the player and by proxy the village. 

Even if the player attacks the mobs the guards dont join in. 

Archers would be a good solution to creepers. Give the guard AI a bow and a battle tactic of always staying a certain distance from creepers. 

Cats might be a good village guard for this. Creepers are scared of them so cats plus archers could handle them quite well. 

Guards can handle spiders. Those dont mob up becoming hordes like zombies do. 

Skeleton Archers can be handled by shields.

**Comment by Konyv** [comment]
And Tango posted while I was typing. Ty for the info Tango. :)
