### ISSUE TITLE
Possible bug: Villagers can access the output of a furnace in the storehouse

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#290]
**Describe the bug**
This may be intentional, or not an issue, but if you place a furnace in the storehouse, villagers can pull items from the output (I assume because they are looking to pull from any inventory?).

**To Reproduce**
1. Go to storehouse
2. Add a furnace with logs being turned into charcoal
3. Watch villagers steal the charcoal from it

**Expected behavior**
Villagers only notice chests and crafting benches in the storehouse.

** Server/Location **
Single Player, 1.0.21

**Comment by JohnyDL** [comment]
No this is intended because they use the furnaces to make charcoal if there's no blacksmith
