### ISSUE TITLE
Suggestion: redstone trade increased from 16 to 32

### ISSUE THREAD

**Issue by Tab-160** [TangoTek/TekTopia-Community#301]
Currently the merchant buys 16 redstone. Already the idea for nerfing the Redstone trade has been brought up, I think it should be done by increasing the amount that is needed and not by nerfing the amount of emeralds you get. Storage facilities get very full with redstone after only a little bit of mining.

**Comment by JohnyDL** [comment]
Tango has also talked about nerfing the amount of redstone your miners bring back from surprise ore veins

He's also talked about better trading solutions in #133

**Comment by TangoTek** [comment]
If storage is overflowing with an item type the answer isn't to make it more profitable.
I removed redstone as a "bonus" ore for miners

**Comment by JohnyDL** [comment]
I thought the suggestion was costing more redstone for the same number of emeralds if you're getting stacks and stacks of the stuff (like wood) then the merchant should buy in bigger quantities (and at a lower price)
Removing it as a bonus resource makes it none renewable within the village
