### ISSUE TITLE
Villagers try to path over a wall that is 1.5 tall (they are standing on a half slab)

### ISSUE THREAD

**Issue by andykern12** [TangoTek/TekTopia-Community#302]
Villagers try to path over a wall that is 1.5 tall (they are standing on a half slab)

They should path up the steps/around the wall.

Screenshot bellow,

Server 1, Ice Mountain 3.0, when they walk from the south towards the library. They get stuck on the steps that enter my village. 
Cords are at spawn for my village, I'm currently away from my laptop to know them sorry.

If you push them up 1 step they get moving again, if not they hop forever in place.

![Screenshot_20190604-090342_Video Player](https://user-images.githubusercontent.com/51372466/58886017-d3598d80-86a8-11e9-9499-ed3db3dab830.jpg)

**Comment by JohnyDL** [comment]
related to #51
