### ISSUE TITLE
Villager hearts sometimes stack, sometimes don't

### ISSUE THREAD

**Issue by LinaBoeckwurm** [TangoTek/TekTopia-Community#307]
**Describe the bug**
I assume that hearts aren't supposed to stack, but they sometimes do. 

I am gathering my hearts to spawn them in when I have a school, and I notice that sometimes hearts stack, and sometimes they don't. 

I had another set of hearts not pictured in the screenshot, that I used to test whether or not they would have the same name when spawned (they didn't).

![image](https://user-images.githubusercontent.com/28556423/58907846-9ddf8f00-86fe-11e9-872f-a859889872f2.png)

I found another heart that stacked with the two I already had
![image](https://user-images.githubusercontent.com/28556423/58907899-b8196d00-86fe-11e9-9a65-b42c42a46262.png)

I couldn't remember whether I got the other stacking hearts in the same night, but clearly, since this heart stacked with already existing ones, this doesn't have anything to do with it.

**Comment by JohnyDL** [comment]
I'd guess they stack if they have exactly the same meta-data so same parents and stuff.

**Comment by LinaBoeckwurm** [comment]
Well they don't have the same name, which to me sounded like they didn't have the same meta data? They didn't even have the same last name.

**Comment by JohnyDL** [comment]
They take one of their parents last names if the data is two sets of surnames then you have a 50% chance of getting the same or different with 2, and if it's not 2 parents but all the potential matching parents in the room it might be less than that, see if you can display the NBT data and screenshot it

**Comment by IridescentShadow** [comment]
I have some that stack and they were collected from the same bed, so it seems to be when the same villager creates it, they will stack

**Comment by TangoTek** [comment]
IridescentShadow is correct. They only stack from the same parent. This is because the parent is encoded in the heart for naming purposes.
