### ISSUE TITLE
Merchant issue (Bug)

### ISSUE THREAD

**Issue by arstan1996** [TangoTek/TekTopia-Community#309]
I am playing on server 2 (ign arstan) coords: -1047 70 -1361
Issue: Merchant not spawning at day. Checked 3 days and no merchants spawned, i did also check and multiple nomads spawned for me but no merchant so it is more of a merchant issue than a nomad issue all together.

**Comment by JohnyDL** [comment]
They don't spawn every day but it seems you got unlucky I hope #190 will help you find your merchant when he appears

**Comment by arstan1996** [comment]
I was told it was meant to be every day by mods on the server, pluss i have not seen one in about 8-9 ingame days now

**Comment by arstan1996** [comment]
Actually one just spawned so i guess you was right and it is not daily, weird though.

**Comment by JohnyDL** [comment]
They have a chance to spawn every day but I don't believe that chance is 100% you just got very unlucky
