### ISSUE TITLE
Villagers float in sitting position

### ISSUE THREAD

**Issue by twmeehan** [TangoTek/TekTopia-Community#318]
Bug:
Sometimes when leaving the tavern, a villager will remain in the sitting position instead of standing up and they will float along the street to their home.

To Reproduce:
1. Get a tavern with several chairs
2. Carefully watch any villagers leaving the tavern
3. See error

Expected behavior:
Villagers will stand up when leaving their chair.

Screenshots:
![2019-05-31_21 04 06](https://user-images.githubusercontent.com/43288159/58971964-80f09d80-878a-11e9-8c2d-42f88e9713c0.png)
![2019-06-04_14 25 41](https://user-images.githubusercontent.com/43288159/58972046-a67da700-878a-11e9-80a0-55b83cafa73c.png)

Location:
Singleplayer creative

Additional context:
They will stand up once they begin a new animation such as mining or sleeping

**Comment by JohnyDL** [comment]
This is a visual glitch and to do with the way Vanilla Minecraft works, I'm sure I've seen Tango comment on it but can't find
connected to #248

**Comment by TangoTek** [comment]
Fixed in 1.0.58

**Comment by sarastar868** [comment]
@TangoTek My children are still doing this in 1.0.58 
![2019-07-08_13 33 15](https://user-images.githubusercontent.com/52576104/60831142-d4d61400-a186-11e9-9757-0c454f5d31ef.png)
