### ISSUE TITLE
AI Balancing Issue: Cleric runs into mobs

### ISSUE THREAD

**Issue by tomerorian** [TangoTek/TekTopia-Community#326]
**Describe the bug**
A cleric's AI seems to be to run toward a mob until it gets to it or has something to heal.
This causes cases where the cleric arrives first and just stands there and take damage

**Expected behavior**
I think the cleric should either run to the closes guard or to a specific range away from the mob and retreat when needed

**Comment by TangoTek** [comment]
Cleric AI was redone in 1.0.44.  Should be much better now
