### ISSUE TITLE
Blacksmith taking all the coal

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#330]
**Describe the bug**
As of jar 1.0.24, blacksmiths have removed all the coal from the storage building. THis was not a problem prior to this jar, but i skipped the one before as I was asleep. This may also be happening with other professions that use coal, chef and miner, but i was unable to check before having to leave for work.

**Expected behavior**
blacksmiths only take what they need to smelt items and do not remove excess from storage.

**Screenshots**
![2019-06-07_08 09 24](https://user-images.githubusercontent.com/49371154/59087797-a520bb80-88fd-11e9-974a-5691103b2e06.png)

Only took the one screenshot but it was the same on my other blacksmiths

** Server/Location **
What if 1

**Comment by Shamshalabim** [comment]
Have checked our extensive list of chefs (7?) and miners (8), and they are not taking mass coal.. It's just the blacksmiths

**Comment by Galarn20** [comment]
My blacksmith takes it all, my miners where trying to make torches so i put so coal in there that i mined and he came a got that also.he already had like 4 stacks on him.

**Comment by JohnyDL** [comment]
Yeah they seem to want/need 4 stacks rather than 4 pieces which seems a lot more reasonable, once at that point they do stop hogging the stuff.

**Comment by TangoTek** [comment]
Yep. Typo.  Thanks.
