### ISSUE TITLE
Suggestion: Villagers can make and consume golden apples

### ISSUE THREAD

**Issue by HexFlareheart** [TangoTek/TekTopia-Community#334]
Yeah, two in a row, shush. This occurred to me while poking through other issues.

Basically, villagers (either the blacksmith or the chef, dunno which specifically) should be able to, if there's plenty of excess gold (and apples, of course), make golden apples, which then can be used by Guards for a temporary boost in combat. While not very useful for small villages that don't really have the resources to make golden apples, or big enough of threats to warrant them, it'd be a nice extra boost for especially affluent villages, which likely have to deal with the strongest threats anyway.

Obviously this would not entail making enchanted golden apples. The village would have to be SERIOUSLY rich for that. (Although it could be hilarious to see a Guard basically go super saiyan with one.)

**Comment by JohnyDL** [comment]
Yeah this would be kinda cool and would have to be balanced out with golden carrots that're general food. I'd like to see guards taking potions when they know a necro raid is incoming would require someone to brew the potions though and the fun-guy to farm warts from #113
