### ISSUE TITLE
Merchant and doors  - saga continues

### ISSUE THREAD

**Issue by JamesTDue** [TangoTek/TekTopia-Community#340]
Sorry Boss #146 seems to still be in play
![2019-06-07_12 50 31](https://user-images.githubusercontent.com/51033015/59109178-7ffb6f80-8934-11e9-81f3-34503778fbe3.png)
![2019-06-07_14 32 00](https://user-images.githubusercontent.com/51033015/59109179-7ffb6f80-8934-11e9-954d-f507df112e05.png)

**Comment by Shamshalabim** [comment]
I have the same issues with merchants and fence gates

**Comment by TangoTek** [comment]
Found another thing stopping them from opening doors.  I just watched a merchant and nomad open doors in my world. Fixed now (again).  Thank you!
