### ISSUE TITLE
Miners not sleeping

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#342]
**Describe the bug**
In the middle of the night miners are not going to bed. They seem to be loitering in one area, above out mineshafts.

**Expected behavior**
Miners go to bed like other villagers

**Screenshots**
![2019-06-07_17 22 20](https://user-images.githubusercontent.com/49371154/59119046-aed01080-8949-11e9-9f73-5ab9e2e30e2a.png)

** Server/Location **
What of 1

**Comment by Shamshalabim** [comment]
Problem continues
https://cdn.discordapp.com/attachments/506195290143981581/586662384358260738/2019-06-07_22.06.32.png
https://cdn.discordapp.com/attachments/506195290143981581/586665858936602624/2019-06-07_22.11.01.png

**Comment by Shamshalabim** [comment]
Miners are achieving nothing. 24 mineshafts all regrown fully by druids. Other gathering professions also dramatically reduced in effectiveness I think although not really seen such obviously weird behaviour from farmers or lumberjacks

**Comment by Shamshalabim** [comment]
https://cdn.discordapp.com/attachments/506195290143981581/586669677586153493/2019-06-07_22.35.36.png

**Comment by tomerorian** [comment]
I believe this is related to several other bugs happening all the time especially with miners. 
1. They will (for at least 1 reason) go above ground above their mineshaft
2. They will forever attempt to finish their mining AI and since they are failing they will not eat, sleep, move or do anything else

**Comment by TangoTek** [comment]
Can you correlate the position they are clustering above ground to any mineshaft below ground?  Is it directly above a mineshaft? Be precise here please.

**Comment by TangoTek** [comment]
I've made a few changes to the Miner AI that should fix this.  I can't reproduce this one so I'm hoping it works.  Let me know if you see it after 1.0.30
