### ISSUE TITLE
Cleric is unhappy all of the time

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#343]
**Describe the bug**
My cleric spends all day/night being unhappy, except for right after he sleeps (when it gets up to ~40).  I assumed it was because I didn't have any guards to help him rotate, but I have two now and he is still unhappy all of the time.  He also ignores cakes in the storeroom.

**Expected behavior**
Cleric maintains happiness just like other villagers, through eating cake and sleeping.

**Screenshots**
![2019-06-07_14 20 02](https://user-images.githubusercontent.com/51030004/59128452-b4206180-892f-11e9-947d-08b351f85bda.png)

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Main server 2
What are the world coordinates of your town hall marker? "Enchanter's Grotto" -6039 10 -9530

**Comment by TangoTek** [comment]
After looking through this one my guess is this.... When a villager sees an enemy it flees and loses 2 happiness.  However, Guards and Clerics (classified as Defenders) always run to the fight. Guards however don't flee enemies.  Clerics however do... Clerics need lots of AI improvements. 

So it left the cleric in a weird situation where they must run to the fights, but they also flee from them. This is why they are unhappy more.

A quick fix is to make it so Defenders no longer lose happiness from seeing or fleeing from an enemy.
However, more long term Cleric AI fixes are definitely needed.
