### ISSUE TITLE
Merchant asking for logs when I have no lumberjack

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#344]
**Describe the bug**
My merchant asked for logs even though I have no lumberjack.

**Expected behavior**
Merchant only asks for products related to the villagers I have.

**Screenshots**
![2019-06-07_14 33 45](https://user-images.githubusercontent.com/51030004/59129100-7b818780-8931-11e9-876a-db689ad12747.png)

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Main server 2
What are the world coordinates of your town hall marker? "Enchanter's Grotto" -6039 10 -9530

**Comment by HexFlareheart** [comment]
I've noticed that in general the Merchant's first trade doesn't seem to care what you actually have. I've gotten cooked mutton with no chef or butcher, redstone with no miner, etc. Just seems to be completely random every time.

**Comment by KeyokeDiacherus** [comment]
That's a good point, it does seem to be the first trade that does that.  On a test server with no producing villagers, he had cooked porkchop as his only trade.

**Comment by TangoTek** [comment]
This is correct and intentional. The first trade is always random.  It can be debated if this should stay, but for now its working as intended.
