### ISSUE TITLE
Lumberjack is not making them selves new axes or using Axes that are in Storage. 

### ISSUE THREAD

**Issue by blutmes** [TangoTek/TekTopia-Community#346]
**Describe the bug**
Lumberjack is not making them selves new axes even if there is wood available to make a new one or using Axes that are in Storage at least player made i did not have a black smith to see if they will use villager made items. 

**To Reproduce**

**Expected behavior**
Expected that the lumberjacks would take Axes in storage to use. 

**Screenshots**

** Server/Location **
What if Survival 2

**Additional context**

**Comment by blutmes** [comment]
playing some more it looks like the lumber jack will take an axe at the start of the day however if that axe breaks they will not take another axe till the start of the next day.

**Comment by H3roDude** [comment]
My Lumberjack even asks for an axe after sleeping/on the next day. But yeah, mine is broken as well ^^

**Comment by MommaBear1081** [comment]
I am seeing the same thing.  They both asked for an axe in the morning, and there were 4 in the chest.  Server reset before I could clip.  The reset did the trick. I have also noticed this with my miner.

**Comment by asgasgasg** [comment]
Same for me.

**Comment by Annie8472** [comment]
Ditto for my single player world. I had a few stone axes but these were not good enough after the first one or two. She finally started work again after I gave her a few iron axes.

**Comment by TangoTek** [comment]
This should be fixed by now
