### ISSUE TITLE
Bug: Killed villager drops not being picked up by player.

### ISSUE THREAD

**Issue by ARocketEngineer** [TangoTek/TekTopia-Community#349]
Had two villagers die to a necro attack. I could pick up some of their items but some didn't and there were plenty of spaces in my inventory. 
![2019-06-07_18 59 38](https://user-images.githubusercontent.com/51294493/59137836-aaaaef80-8957-11e9-8af0-0613c32842cf.png)
![2019-06-07_18 59 44](https://user-images.githubusercontent.com/51294493/59137841-ae3e7680-8957-11e9-9f52-1c903ede5206.png)

**Comment by TangoTek** [comment]
Wow. Congrats. You just found a bug in Minecraft.

**Comment by TangoTek** [comment]
If you have green/villager items in your inventory of the items on the ground you can't pick them up it seems?

**Comment by TangoTek** [comment]
OR... I'm just an idiot.  Villagers were dropping a second copy of every item on the client as well as the server. The client items were just 'ghost' items and not really there.  Fixed.  Thank you!
