### ISSUE TITLE
Guards do not do final smash attack

### ISSUE THREAD

**Issue by Darelk0** [TangoTek/TekTopia-Community#351]
**Describe the bug**
Guards do not do their "final smash attack

**To Reproduce**
Go in to creative mode
spawn a guard
spawn alot of zombies

**Expected behavior**
guard should smash the zombies

Guard will not aoe smash the zombies

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? What if server 2
What are the world coordinates of your town hall marker?3333 -8556

3333 -8556

**Additional context**

**Comment by TangoTek** [comment]
Good find. Thank you.  Fixed.
