### ISSUE TITLE
Druids don't regenerate lapis, coal, iron, redstone

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#352]
**Describe the bug**
We have noticed that we're not getting any lapis, coal, or redstone, and very little iron in our mines. We have got them up at Y:58, so one might assume that they shouldn't generate lapis, diamond or redstone there due to Y axis, but we are getting plenty of diamonds. Something doesn't line up.

**To Reproduce**
1. Set up mines at Y:58
2. Have a roughly 2:1 - 3:1 druid to miner ratio
3. Observe..
4. Over time you'll see that the druids continue to regenerate plenty of stone and a few diamonds, but no lapis, coal, natural (as oppose to bonus) iron, redstone.

**Expected behavior**
Originally I'd have thought that what generated depended on Y-level, but then we got diamond up at Y:58 and so we moved our mines up closer to the surface to reduce travel distances. Either the intended behaviour should be that druids can regenerate all resources at any level, or that it is Y-axis specific like natural generation.

**Screenshots**
Not something that screenshots will really help with. I can show diamonds generated at 58, but otherwise it would just be pictures of our coal stores, and so forth..

** Server/Location **
Main 1
X: -3716, Y: 72, Z: 2019

**Additional context**
I think this is linked to druid regeneration rather than anything to do with miners.. The issues we're having with miners are separate in my mind..

**Comment by H3roDude** [comment]
My Druids act the same like given above

**Comment by TangoTek** [comment]
This is me forgetting  to finish writing the Druid's code. I was rushed when I did this originally. Fixed. He should now generate all ores and coal. As he levels he'll generate more diamonds.
