### ISSUE TITLE
Guards do not drop any gear on death

### ISSUE THREAD

**Issue by paspinall42** [TangoTek/TekTopia-Community#360]
**Describe the bug**
Unlike other villagers Guards do not drop gear on death, presumably as it is not held in their inventory ? As they by default get the first diamond gear, and are likely early ones to die,this gets very expensive. 

**To Reproduce**
let a guard die.. 

**Expected behavior**

Guards to drop some/all of their gear

**Screenshots**

** Server/Location **
server 2, Pastoft, 2633 72 4851

**Additional context**

**Comment by TangoTek** [comment]
Fixed. Thanks Pasp
