### ISSUE TITLE
Miners drop things off after colecting 2 things

### ISSUE THREAD

**Issue by jojo12551** [TangoTek/TekTopia-Community#361]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by TangoTek** [comment]
Forgot some things on the new pick up/dropoff system.  Thanks!  Fixed
