### ISSUE TITLE
Villagers in storage room don't do all their storage-related tasks

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#378]
**Describe the bug**
I just watched a miner go and get food but while he was in the stroage room didn't drop off his iron ore

**To Reproduce**
watch a miner get food

**Expected behavior**
Before a villager leaves the storage room they should do all storage-related tasks even if thresholds haven't been met.

**Server/Location**
Offline Creative 1.0.35

**Additional Information**
This should include any crafting that villager needs to do while in the storage and room as well as getting/using any items for their job or depositing items they don't need.

**Comment by JohnyDL** [comment]
I'm still having this issue. My miner visits the storage room for food but doesn't drop off his items
![2019-06-14_10 41 42](https://user-images.githubusercontent.com/5202568/59506365-e6860d80-8e9f-11e9-84c6-8d98c2fcefbe.png)

**Comment by TangoTek** [comment]
Fixed something in item deliver that should address this in 1.0.57
