### ISSUE TITLE
Villagers might gain intelligence a little too fast in the library

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#379]
**Describe the bug**
Villagers seem to gain intelligence a lot faster than they can possibly gain skills,

**To Reproduce**
Level 1 villagers + work to do + library
turn off day-night cycle
watch

**Expected behavior**
Villagers don't gain as much intelligence in a single sitting

**Screenshots**
These villagers all had 1 intelligence half an hour ago
![2019-06-10_10 43 38](https://user-images.githubusercontent.com/5202568/59187561-9fc9a800-8b6d-11e9-95e7-49b9e30665ce.png)
![2019-06-10_10 43 43](https://user-images.githubusercontent.com/5202568/59187562-a0623e80-8b6d-11e9-80cb-a44cf84aab65.png)
![2019-06-10_10 43 53](https://user-images.githubusercontent.com/5202568/59187563-a0623e80-8b6d-11e9-945d-753af873c54f.png)
![2019-06-10_10 44 16](https://user-images.githubusercontent.com/5202568/59187565-a0623e80-8b6d-11e9-8efd-8e8a7d491d03.png)
![2019-06-10_10 44 22](https://user-images.githubusercontent.com/5202568/59187566-a0623e80-8b6d-11e9-9ce1-8720f53049f6.png)
![2019-06-10_10 44 29](https://user-images.githubusercontent.com/5202568/59187567-a0623e80-8b6d-11e9-98be-72377dfe91c1.png)

**Server/Location**
Offline Creative 1.0.35

**Additional context**
I know that it gets much harder as they gain intelligence but I'm going to advocate capping their skill gain or putting some cool-down on progression even if they attempt to, getting more than 1 skill level in any given minecraft day still kind of reduces the feeling of progression, you progress faster sure but having the steps be smaller and spread out over a longer time... well the steps feel the same height once you get used to them. whether a villager gains 1 skill or 10 in a day each step feels like the same amount of progression and if you have more of those steps however big you feel more positive about the game/playthrough.

**Comment by TangoTek** [comment]
I agree library intelligence gains were a bit too fast. I lowered it by 30% and will continue to monitor.
