### ISSUE TITLE
Villagers back to level 1

### ISSUE THREAD

**Issue by JSman95** [TangoTek/TekTopia-Community#384]
**Describe the bug**
So i installed the 1.0.35 update, and for some reason 5 out of my 7 villagers returned to level 1 with there current profession. It did not have any impact on the other skills the villagers have,

**To Reproduce**
Villagers back to level 1 with there current profession

**Expected behavior**

**Screenshots**
![bug](https://user-images.githubusercontent.com/51421568/59195805-335ea100-8b8d-11e9-9ae0-97af311dcf97.png)

** Server/Location **
Singleplayer survival

**Additional context**
The only villagers there are not impacted by the bug is one of my 3 farmers, and the chef that does seam to do anything after he filled his inventory with beetroot soup.

**Comment by ravenclawnc12** [comment]
This most likely has to do with the new changes to the intelligence system, once the villager tries to level up, their skill is set to max at their int. so you will need to get a library to raise their intelligence.

**Comment by JSman95** [comment]
So does that mean that they won't level up without at library, if their intelligence is very low?

**Comment by JSman95** [comment]
nvm found the answer
