### ISSUE TITLE
Suggestion - Location of failed Merchant/Nomad pathing to village

### ISSUE THREAD

**Issue by rdster** [TangoTek/TekTopia-Community#395]
**Describe the suggestion**
When the Merchant/Nomads are unable to path find to the village...please either:

1- spawn them and let them stand there. (So they can be hunted down...)
2- include the coords of where they would have spawned.

This way the player can locate that spot and make sure that there is a clear path to the village for the next time.

Thanks for the amazing mod...

**Comment by iSyriux** [comment]
**THIS FUCKING SHITASS MOD WITH THIS SHITASS BUG AINT FIXED WHAT THE FUCK IS TANGO FUCKING DOIG THIS FUCKING MOD FUCKING SUCKS **

**Comment by rdster** [comment]
Then stop playing it... You act like you're 6 years old anyway... Go play with your Fisher Price toys.

Tango has a life, unlike you.

**Comment by smmmadden** [comment]
Sounds like someone needs to be banned from here as well as discord.

**Comment by smmmadden** [comment]
They all spawn from each of the directions (N, S, W and E).  So it's not one place that can be pointed to.  What I've done to manage this scenario is put up a wall around the 200x200 area.  Once you have the wall up (or even just the corners marked, the Nomads, Necromancer & Merchants come from these areas.  If there is a solid wall up, that doesn't prevent them from coming, they spawn inside the village. I was able to replicate this behavior in many types of villages.

**Comment by rdster** [comment]
That's not really true... For one they spawn in the NE, SE, SW and NW corners... But it would be one point for that spawn attempt. Yes they spawn inside the walls if you don't leave an opening... But for a brand new town... Having the location of the problem would very helpful.

**Comment by iSyriux** [comment]
**ARE YOU FUCKING STUPID YOU FUCKING STUPIDASS FUCKING SHITBAG DO YOU EVEN READ YOU FUCKING BRAINDEAD ASSHOLE WHOREASS DICKBAG FUCKING IDIOT** 
![image](https://user-images.githubusercontent.com/38577487/76876091-cd9ff380-6847-11ea-84ca-c5e12e3cc619.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876265-0f309e80-6848-11ea-8783-dc873b06bcf0.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876326-27a0b900-6848-11ea-939d-3f29826f2e20.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876349-312a2100-6848-11ea-8cfc-5c2e7e17f086.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876388-3dae7980-6848-11ea-8ed9-e96ecc851b23.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876412-47d07800-6848-11ea-8ecd-449e7f234949.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876439-50c14980-6848-11ea-9721-5745dbea2142.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876468-57e85780-6848-11ea-8f5f-9b2f283cf6f7.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876500-66367380-6848-11ea-948a-95036bcd871a.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876525-70f10880-6848-11ea-98b5-0003f2a41e51.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876549-7b130700-6848-11ea-966d-e20ba6bf77b1.png)

**Comment by rdster** [comment]
You really need to be blocked...and none of this really has anything to do with this issue.  But congrats for figuring out how to add pics.  You still need to learn how to watch your language

**Comment by iSyriux** [comment]
**WHY ARE THEY GETTING OUT OF THE TOWN HALL FUCKING IDIOTS**

![image](https://user-images.githubusercontent.com/38577487/76876648-98e06c00-6848-11ea-92ff-78a449f22b00.png)

**Comment by iSyriux** [comment]
THEY ARE LITERALLY STANDING IN THE DOORWAY DOING NOTHING

![image](https://user-images.githubusercontent.com/38577487/76876691-ab5aa580-6848-11ea-817b-8a0b8887c826.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876753-c6c5b080-6848-11ea-8579-e56cafed3102.png)

**Comment by iSyriux** [comment]
![image](https://user-images.githubusercontent.com/38577487/76876795-d218dc00-6848-11ea-9749-b19a7e2c376c.png)

**Comment by rdster** [comment]
Those are nomads moron...they don't do anything until you assign them a profession.

**Comment by rdster** [comment]
Anyone interested can go here to report iSyriux ... https://github.com/contact/report-abuse?report=iSyriux+%28user%29

**Comment by KelliSkellington** [comment]
Thanks, m8. This kid’s getting annoying and the notifications from him are
interrupting my schoolwork.
