### ISSUE TITLE
Necromancer attacks at less than 8 villagers

### ISSUE THREAD

**Issue by paspinall42** [TangoTek/TekTopia-Community#401]
**Describe the bug**
at 4 villager count Necromancer attacked  (JKat also reported an attack with only 2 villagers) 

**To Reproduce**
Have small village, wait for necromancer attack 

**Expected behavior**
No Necromancer below 8 villagers

** Server/Location **
What If 2, 1912 72 4556

**Comment by blackwellj** [comment]
I have had the same issue with only 2 villagers

**Comment by JKatBat** [comment]
Yep as Pasp states I had one attack at 2 villagers and another one at 4.

**Comment by TangoTek** [comment]
This should be fixed as of 10.37. Merchants, Tradesman, and Nomads were unfortunately being counted toward the cap. Sorry about this.
