### ISSUE TITLE
New skill/int system not working properly

### ISSUE THREAD

**Issue by BlackSpider71** [TangoTek/TekTopia-Community#408]
**Describe the bug**
When a villager levels up their skill it still goes down to the same level as the int

**To Reproduce**
1.) Let villagers skill up
2.) Skilling up again takes them down to the int level

**Expected behavior**
Skill level doesn't go down

**Screenshots**
![2019-06-12_22 19 06](https://user-images.githubusercontent.com/51145225/59402088-a40ae680-8d62-11e9-8d07-bbe06b225181.png)
![2019-06-12_22 19 38](https://user-images.githubusercontent.com/51145225/59402097-aec57b80-8d62-11e9-8d44-bd5456d41ab9.png)
![2019-06-12_22 19 42](https://user-images.githubusercontent.com/51145225/59402101-b422c600-8d62-11e9-955a-e520b8771dca.png)
![2019-06-12_22 23 10](https://user-images.githubusercontent.com/51145225/59402170-ea604580-8d62-11e9-90a1-5eb8ce9719b4.jpg)
![2019-06-12_22 23 16](https://user-images.githubusercontent.com/51145225/59402179-efbd9000-8d62-11e9-9526-6a6f5ca17205.png)

** Server/Location **
What server were you playing on? What If 2
What are the world coordinates of your town hall marker? 4500 4500

**Additional context**
Had a new level 11 Nomad>Guard turn from 11>8>9>8, did't get any screenshots for that so went into single player to recreate it

**Comment by TangoTek** [comment]
Ugg. Yep. I derped. Thanks. Fixed.
