### ISSUE TITLE
Suggestion: Necromancer Goals

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#415]
**In a nutshell**
Necromancers should have a goal of how much damage to inflict before they despawn

**Detailed version**
Necromancers should have an aim in their village attack and once they hit it they despawn along with their horde

First, their level should determine how many villagers they can kill, level 1 can kill 1 villager, level 2 can kill 2 villagers etc. This limits the amount of permanent damage a necro can do to a village.

Second, their level should determine how much base damage they and their minions can deal to the town, level 1 can deal 10% of the village health, level 2 deals 20% etc. the total health of the village is the number of hearts every villager has combined, and the amount of damage the necro and horde deal is before armour reduction. This then limits the length/scope of an attack.

A Level 1 necro attacking a village of 10 villagers with 1 guard would be able to kill one villager and do up to 20.5 hearts of damage, this would severely limit the damage the lowest level necro could do to a fledgeling village

While a Level 5 necro attacking a village with 100 villagers including 5 guards would have the ability to kill 5 villagers and deal out 512.5 hearts of damage a much bigger threat but also with damage reducing armour and clerics the 5 guards might be able to tank this and it makes it a little more fun knowing that so long as your 5 guards get to the front line of an attack they're the most you're going to lose.

**Comment by Konyv** [comment]
I love the idea of a more complex goal. Adds lore to the Necro and does give an interesting avenue for more creative limits on the Necro. 

Though I think 1 death per level seems too weak. As much as I have hated losing 50+% of my village in necro attacks I think if the necro has a limit that strict then it will stop being scary. 

Set up a few low level guards to fail and your whole high level village is safe. Sacrifice Villagers to the Necro Overlord in exchange for safety. lol Actually that sounds kinda cool.

**Comment by Konyv** [comment]
Instead of a solid limit the number could be variable. Deal damage or kill villagers based on level, population, and time. 
Necro attacks will never last beyond a certain time limit and that time limit is based on Necro level. 
Kills can be a random number between 1 to pop max with a higher change of lower numbers. 
Damage can be similarly variable. 

Once time, kill, or damage count is reached then the Necro and zombies despawn.

**Comment by JohnyDL** [comment]
in fairness I think limiting the total damage they can do is the key, if you then don't give your guards armour or use clerics you're going to lose more villagers, I only really added the hard limit because it kinda feels right in minecraft ways, if the player dies pretty much an attack on them stops when you go back for your dropped things then the game has probably despawned whatever you were fighting, 90% of the time at least, I figured the same could almost be true of the villages a death or a few deaths buys you reprieves and setting up a few guards to die... that'll get expensive quick with the way token prices go up, not to mention the waste of expansion opportunities

**Comment by Konyv** [comment]
A hard limit of some kind sounds great because things do get pricey. I just think the limit should be a variable min-max. Like some attacks you might get lucky and the necro just hurts a guard, but kills no one. I think that ramps up the excitement more and keeps things from getting stale. 

I say all this as someone who has had terrible luck fighting the necro so maybe my view is tainted. lol

**Comment by JohnyDL** [comment]
I do agree... I'm one of the people who want more challenging necro levels, as well as more balance lower down. More levels and a little randomness to the "hard limit" might help keep the excitement there but I worry people won't understand it. In the end it's upto Tango though

**Comment by TangoTek** [comment]
A recent change should help this out.  If a villager dies with a Necro in town, the necro will no longer use any of his abilities. (Should die quickly)
