### ISSUE TITLE
Guards ignore spiders and skeleton archers, only attack zombies

### ISSUE THREAD

**Issue by asgasgasg** [TangoTek/TekTopia-Community#430]
**Describe the bug**
Guards at night are ignoring skeleton archers and spiders. Skeleton archers and spiders attack me (player, not base) at night, and although there are guards all around me, the guards ignore the mobs.

**To Reproduce**

**Expected behavior**
Guards attack all hostile mobs at night

**Screenshots**

** Server/Location **
Single player, survival mode

**Additional context**

**Comment by TheGreatNaj** [comment]
I dont believe its a bug. The guards are meant to protect the villagers and the only threat to them are zombies/husks. Might be something Tango plans to add down the line though? Unsure

**Comment by Sobertron** [comment]
Was going to agree with the previous comment, then realizied it came from an All Mighty Mod! But i will agree anyway. Guards only attack zombies.

**Comment by TangoTek** [comment]
Working as designed for now.
