### ISSUE TITLE
Butcher not dropping off leather

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#432]
My butchers seems to want to keep leather on them, even tho they cant craft armour as there is not crafting table in the butchery (delibrate)

**Expected behavior**
I would expect them to drop the leather off as they cant make use of it when no crafting table available

**Screenshots**
none available at this time

** Server/Location **
Whatif#1

**Comment by TangoTek** [comment]
The butcher will still hold onto up to 8 leather before dropping it off at storage regardless of having a crafting table or not.

However, next patch leather will no longer be for sale, but leather armor will. So I suspect you'll want this to change anyway.
