### ISSUE TITLE
Feature Request: Vary Druids schedule

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#433]
Druids seems to focus on farms in the morning and mines in the afternoon. This is leading to some of our mineshafts becoming invalid and many druids standing around when there are no crops to grow.

**Expected behavior**
Recommend druids roll a 50/50 dice at the start of the day to determine where they go first. This may limit the amount of minshafts tht become invalid and also prevent them from standing around with nothing to do in the morning.

![2019-06-15_19 00 46](https://user-images.githubusercontent.com/49371154/59554816-37c9f600-8fa1-11e9-9e49-224e8672c47b.png)
Druids standing in the crops doing nothing in the morning.

![2019-06-15_19 02 58](https://user-images.githubusercontent.com/49371154/59554817-38628c80-8fa1-11e9-98d9-b2067ac70d54.png)
All the druids in the mines in the afternoon.

**Comment by TangoTek** [comment]
Done.
