### ISSUE TITLE
100% happiness too easy

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#454]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
Before having a tavern all my villagers were 100% happiness or very close to it. This may be why the tavern is barely visited apart from the bards. Would it be better if the villagers got no happiness from player provided meats as we were feeding them almost exclusively with player meats. I'd much prefer to see happiness harder to achieve and for the tavern to be more relevant.

**Comment by TangoTek** [comment]
This is good feedback most players wouldn't give. I really appreciate it.  And yea I've been thinking happiness is too easy lately myself.  I lowered the amount of happiness villgagers regain automatically when they wake up quite a bit.  We'll see how it changes things.  Keep feedback like this coming!

**Comment by treehugger667** [comment]
1.0.76

I don't have a tavern or bard and have been able to get a heart every night or two. It seems like the boost of happiness from chairs in the house may be too high. I do have a lot of variety of food.

**Comment by MetriCfan** [comment]
I agree happiness is still too easy, perhaps the game needs another nemesis like midnight raiders that fleece the villagers inventory and gives a big dose of sad
