### ISSUE TITLE
Guard duping gear on "fake death"

### ISSUE THREAD

**Issue by ghost** [TangoTek/TekTopia-Community#457]
**Describe the bug**
A Guard was killed by a zombie and dropped gear but continued to work as normal in a constant death animation. Other players didn't see the death animation repeating, just a normal guard. Animation issue was fixed on relog, but guard armor was still duped. No death message in chat.
Guard seemed to have nearly full health when I checked, however, this was 2 minutes after the incident (see video).

**To Reproduce**
Not sure how to reproduce as this was completely normal guard behavior until the incident, however:
- Guard was standing on farmland right next to water (possible that he fell in at the last moment)

**Expected behavior**
Expected the guard to die and drop his gear, not continue on as usual.

**Screenshots**
![2019-06-17_17 24 17](https://user-images.githubusercontent.com/51972293/59719550-eaf25380-921c-11e9-97d4-2b3064b72c10.png)
![2019-06-17_17 31 52](https://user-images.githubusercontent.com/51972293/59719554-f04f9e00-921c-11e9-8a30-9bb2745b4e24.png)

Video 2 minutes after the incident: (He was doing all normal guard activities)
[https://youtu.be/nkr8WFk1mLI](https://youtu.be/nkr8WFk1mLI)

**Server/Location**
I am playing on the "what-if-2" survival server.
- My town hall marker is at 5703, 73, -2300
- The incident happened at 5744, 69, -2352
- Version: 1.0.37

**Additional context**
This was during the night. My guard is still alive with original armor on as of this post and he is my only guard. The duped armor is in the only chest in my town hall. The armor was player made.

**Comment by TangoTek** [comment]
This is fixed in 1.0.38
