### ISSUE TITLE
Big rooms

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#48]
**Describe the bug**
building marker not registering building

**To Reproduce**
Build a valid room (with no walls) off the ground,
Extend ceiling until maximum room size is exceeded

**Expected behavior**
The room should only be as big as valid floor and valid roof but the floor doesn't need to be there.

** Server/Location **
Main(Survival)
Bugsy Towers (5000 ish 3000 ish will correct later)

**Additional context**
We found out why the storage room wasn't registering and added walls to fix the problem

**Comment by JohnyDL** [comment]
Also I've made farms/building that're 30x30 in size and they've stopped working
![2019-05-28_23 06 34](https://user-images.githubusercontent.com/5202568/58519860-3af57180-81ad-11e9-88fa-9a07b82f8471.png)

**Comment by TangoTek** [comment]
I'm not sure I understand what you are reporting here?  The largest a room can be is 500 blocks of floor tiles.  Anything larger than that and the room is invalid.  This is intentional though I agree some way of giving feedback would be nice.  (Eventually there will be a structure overview UI)

**Comment by JohnyDL** [comment]
In the first case, the building marker was registering a room with only 15x8 floor blocks but >500 ceiling spaces as too big

In the second case, the room was 'valid' from a player perspective but it wasn't clear what the limits were, 500 blocks to me feels a little on the small side though, a 2x2chunk building/farm is 1024 blocks minus the walls/fence is 900 this to me seems like a natural way to align buildings.

**Comment by JohnyDL** [comment]
Finally got round to making this on the Dev Server

8150x -8450z

![2019-05-29_16 00 10](https://user-images.githubusercontent.com/5202568/58568080-7afb3980-822b-11e9-90c9-801ee3902555.png)
Regesterts with 4 roof blocks
![2019-05-29_16 00 27](https://user-images.githubusercontent.com/5202568/58568081-7afb3980-822b-11e9-934a-94b48b0e4dab.png)
doesn't register with over a thousand roof blocks
![2019-05-29_16 00 35](https://user-images.githubusercontent.com/5202568/58568082-7afb3980-822b-11e9-8ff7-10784b2ff4b5.png)
but it only has 25 (15 under roof) actual floor blocks
