### ISSUE TITLE
Enchanter Not Consistently Enchanting Tools/Armor Or Not Doing It At All

### ISSUE THREAD

**Issue by ialeed1** [TangoTek/TekTopia-Community#483]
**Describe the bug**
The Enchanter hoards almost all of the villager tools/armor and enchants them rarely. If you have any sugar cane and leather or sugar cane only they keep making books/ paper and with books they enchant them over tools/armor even though it is supposed to be books if there is nothing to enchant. When you take away to source of leather/sugar cane the enchanter stands around doing nothing with their inventories hoarding armor/tools

Quick Summary: Enchanter prioritizing everything else of enchanting armor/tools and doesn't enchant armor/tools when there is no sugar cane or leather or books.

**To Reproduce**
1. Get enchanter
2. Have armor and tools in chest
3. Enchanter picks these up
4. See Enchanter hoard 90% of this and almost never get to enchanting these items

**Expected behavior**
The Enchanter prioritizes armor and tools over making books and enchanting them

**Screenshots**
![2019-06-20_23 12 59](https://user-images.githubusercontent.com/48269628/59895081-2cb40300-93b1-11e9-957b-0f78a65c583a.png)

** Server/Location **
Single player World

**Additional context**
N/A

**Comment by ialeed1** [comment]
UPDATE:
as of 1.0.43 with villager controls, disabling all other functions except enchanting any and all tools and armor still results in the enchanter refusing to enchant armor and tools hoarded in inventory and the enchanter wanders constantly doing nothing else

**Comment by LOL-Nation** [comment]
**See next comment for a more correct answer**

I think I figured out why the enchanter sometimes waits before enchanting. It appears that they will not enchant an item unless there is 2 extra in the storage room unenchanted.

For example. If there is 1 diamond pickaxe in the storage room and 1 in the enchanters inventory then they will not enchant the pick. As soon as there is a second  unenchanted diamond pickaxe in the storage room, they will enchant the one in their inventory and pick up the next pick.


![2019-06-23_13 46 06](https://user-images.githubusercontent.com/51061066/59980637-45453880-95be-11e9-9175-987e5dcc48aa.png)
![2019-06-23_13 46 23](https://user-images.githubusercontent.com/51061066/59980638-45453880-95be-11e9-856d-a7440464a037.png)

**Comment by LOL-Nation** [comment]
Did more testing. Appears that the enchanter will not consistently enchant unless there is 0 enchanted versions of that item in storage.

1. With 2 photos below, enchanter will not enchant the pick in their inventory.

![2019-06-23_21 54 57](https://user-images.githubusercontent.com/51061066/59989069-33d24f80-9603-11e9-8496-891ddfc01dd1.png)
![2019-06-23_21 55 49](https://user-images.githubusercontent.com/51061066/59989080-3e8ce480-9603-11e9-9f24-a03cc4a782f6.png)

2.  Take the enchanted pick out of storage. Enchanter instantly enchants the pick in her inventory.

![2019-06-23_21 58 00](https://user-images.githubusercontent.com/51061066/59989125-6da35600-9603-11e9-8c2d-7165e4b359ad.png)
![2019-06-23_21 57 42](https://user-images.githubusercontent.com/51061066/59989130-772cbe00-9603-11e9-91da-754b4e254ac7.png)

**Comment by LOL-Nation** [comment]
Tried this again with the last 2 picks in there. Took the 2 enchanted ones out and she enchants a 3rd

**Comment by LOL-Nation** [comment]
Can confirm this is how it works. Tried this with 10 picks. Had to take all enchanted ones out, and then enchanted would enchant the one in her inventory.
