### ISSUE TITLE
Butcher Issue: Butcher killing villager animals gains double the loot - Half Villager Half NonVillager

### ISSUE THREAD

**Issue by ialeed1** [TangoTek/TekTopia-Community#492]
**Describe the bug**
The butcher when they kill an animal they get double the loot:
-Villager items Example: 2 porkchop
-Nonvillager items Example: 2 non villager porkchop
The butcher essentially gets twice the amount but half is villager and the other not villager

The happens with feathers, wool, and leather as well although I have not seen villager leather in a while. 

**To Reproduce**
1. Get a butcher a butcher building and animal pens (filled with villager animals)
2. Butcher kills an animal ( villager animal)
3. See Butcher Inventory after killing animal
4. See double loot half villager half not villager

**Expected behavior**
Butcher should only get villager items from villager animals and not get duplicate items

**Screenshots**
![2019-06-22_00 59 31_2](https://user-images.githubusercontent.com/48269628/59959642-91db2780-9489-11e9-9ab9-37c92c0662a1.png)
![2019-06-22_00 57 43](https://user-images.githubusercontent.com/48269628/59959644-91db2780-9489-11e9-8730-24a88711815b.png)
![2019-06-22_00 57 44](https://user-images.githubusercontent.com/48269628/59959645-91db2780-9489-11e9-814e-034cd51e64bc.png)
![2019-06-22_00 59 31](https://user-images.githubusercontent.com/48269628/59959646-91db2780-9489-11e9-90ed-0580a72f0474.png)

** Server/Location **
Offline Survival  1.0.43

**Comment by Sobertron** [comment]
Noticed the same thing on Server 1. Thought it was one of my village mates but it happened when I was the only one online. There was 4 raw pork in a chest 2 were village 2 were normal.

**Comment by Grurim2k** [comment]
This explains why I keep having random bits of non villager meat show up.

**Comment by ialeed1** [comment]
seems to have been fixed in .44
