### ISSUE TITLE
Suggestion: Making villagers drop items they no longer need

### ISSUE THREAD

**Issue by Grurim2k** [TangoTek/TekTopia-Community#496]
With the new .43 update, we gained the ability to tell villagers not to do certain thing. My suggestion is to make them go put any items back into the storage chest they no longer will need. A good example is, if I tell my chef not to make golden carrots, they go put the gold back in the chest they are holding. Not only will it help clean up their inventories, it will allow for the villagers we actually have tasked with those things to use those materials, or for us to sell them to the merchant.

**Comment by TangoTek** [comment]
Fixed in 1.0.51
