### ISSUE TITLE
Villagers making Vanilla items again

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/TekTopia-Community#512]
Villagers producing white text vanilla items again from villager items. So far my chef has made vanilla baked potatoes from villager potatoes, and vanilla charcoal from villager wood. My chef is the only one making charcoal right now so it might just be chefs but I will keep an eye out.

**Comment by KeyokeDiacherus** [comment]
Same here.  The chef is taking villager charcoal and villager potatoes and turning it into vanilla baked potatoes. 

Edit: he does appear to be making villager charcoal.  

He makes villager baked potatoes with villager coal but makes non-villager baked potatoes with villager charcoal .

**Comment by SaltyJohnson94** [comment]
Same is happening with my Blacksmith. Villager fuel (charcoal) and villager ore (iron) is giving me vanilla iron bars.

**Comment by me2365** [comment]
Yeah this happens with the blacksmith to me and when all the steps to make an iron sword use villager tools and ingredients I still get vanilla swords, axes, etc.

**Comment by LOL-Nation** [comment]
Mine is not making villager charcoal from villager wood.

**Comment by LOL-Nation** [comment]
![2019-06-24_01 34 07](https://user-images.githubusercontent.com/51061066/59996548-4444f300-9620-11e9-9f5f-97d0a9b6a62d.png)
![2019-06-24_01 34 08](https://user-images.githubusercontent.com/51061066/59996549-4444f300-9620-11e9-9427-b70a6f1f3a97.png)
![2019-06-24_01 34 10](https://user-images.githubusercontent.com/51061066/59996550-4444f300-9620-11e9-9f4f-5b04dc2c4ab9.png)

**Comment by paspinall42** [comment]
Same, I cleared the blacksmith furnaces at night to be sure there was nothing in, and followed the blacksmith to make sure they didn't find a source of non villager items but villager coal and villager iron was still taken out by the blacksmith as non-villager iron

**Comment by LOL-Nation** [comment]
Since 1.0.46 this problem has not been resolved for me. Haven't tested every option, but my villagers only make normal charcoal.

**Comment by TheGreatNaj** [comment]
After the update it seems to be 50/50? lol Getting some vanilla baked tatoes and some villager

**Comment by Grurim2k** [comment]
Yeah, even after the most recent update, this is still occurring.

**Comment by paspinall42** [comment]
Yep still occurring :(

**Comment by Sobertron** [comment]
Just checked myself and it is happening. I removed all non villager fuel sources from storage. The chefs will make villager charcoal but all food they gather from the furnaces is non-villager food.

We have not provided out villagers with any cooked meats. 

![2019-06-26_17 54 04](https://user-images.githubusercontent.com/49371154/60199368-af1e4600-983b-11e9-9203-2810a4edb4f3.png)
![2019-06-26_17 54 05](https://user-images.githubusercontent.com/49371154/60199369-af1e4600-983b-11e9-975a-244f53f871d4.png)
![2019-06-26_17 54 06](https://user-images.githubusercontent.com/49371154/60199371-af1e4600-983b-11e9-86c5-7d99c6674a03.png)

**Comment by TangoTek** [comment]
This should be fixed in 1.0.51
