### ISSUE TITLE
Druids Only/Mostly Filling In Mines With Stone

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#517]
I have a level 63 druid and set him to only fill in mines. At first at thought it was fine but one day when I was making a new mine for my miners I watched the Druid fill in a previous made mine and I noticed all he was filling in was stone. So I dug up what he filled in to see if there were minerals around that but no, there was only stone. I thought I was just unlucky speaking I have a pretty high level Druid. So for a day I watched him as he filled in mines and all he did was fill in stone every time even around the parts that he filled in.

1: Have a Druid
2: Wait for Druid to fill in mines

That he fills in ores because he is pointless if he only fills stone as that is just wasting the durability on my miners pickaxes.

N/A

Server 1 Survival

I think a good idea would be to fill in the mines depending on his level by chance. For example, each time he fills in blocks there is a certain chance that it is an ore and the ores can be random. And that chance will be his level. So if he is level 4 there will be a 4% each time he fills in blocks and so on. However there will need to be some differences at level 100 to make sure this is not overpowered but I do believe it should be similar to this. Possibly their level - 5% or 10%.

**Comment by Hedkracka** [comment]
the druids are working as intended

**Comment by asgasgasg** [comment]
I've had a similar experience.
