### ISSUE TITLE
Some Villagers GUI says they have level 100 with 4 different skills when they don't

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#518]
For example if a Rancher is level 30 (actually) the GUI will sometimes say he is level 100 and not only that but level 100 with 4 different skills and sometimes skills he never had.

1: Have Villager
2: Open GUI

It should show the correct level of the skill he has and show the skills he actually does have.

<img width="1440" alt="Screen Shot 2019-06-23 at 10 09 34 PM" src="https://user-images.githubusercontent.com/52055365/59990344-5adf5000-9608-11e9-91e1-d757e3c962da.png">

Server 1 Survival
X:600 Z:600

**Comment by Amphibiangamer10** [comment]
I saw the same thing on my farmer - 
![Untitled 1551](https://user-images.githubusercontent.com/51340428/60029843-1e8b0e80-965f-11e9-8cac-05661c438f82.jpg)

**Comment by TheGreatNaj** [comment]
![2019-06-25_02 22 20](https://user-images.githubusercontent.com/25763105/60078272-9dcd2080-96f9-11e9-8410-0a3959623af3.png)
_I feel like theres another post open on this from forever ago but I couldnt find it._

**Comment by ghost** [comment]
And this is a CLeric
![2019-06-25_00 55 42](https://user-images.githubusercontent.com/51976349/60096349-a9692780-978b-11e9-8491-35763423af51.png)

**Comment by SaltyJohnson94** [comment]
On my Druid:
![Capture6](https://user-images.githubusercontent.com/52110462/60150358-39f43780-978d-11e9-82fa-eb98c6b8371e.PNG)

**Comment by TPdenhaag** [comment]
![image](https://user-images.githubusercontent.com/52247884/60188894-54332180-9830-11e9-8087-00df013d86ba.png)

![image](https://user-images.githubusercontent.com/52247884/60188903-585f3f00-9830-11e9-8163-b35f6f14acdc.png)

They only ever were farmers, so they shouldn't have these skills, they showed this as soon as I converted them to farmers

**Comment by TPdenhaag** [comment]
![image](https://user-images.githubusercontent.com/52247884/60189463-3b773b80-9831-11e9-8caf-236a9e6527c1.png)

He's had this job for like 2 (irl) days

**Comment by ravenclawnc12** [comment]
have the same. server 1 boop town 
![2019-06-28_01 02 01](https://user-images.githubusercontent.com/51100585/60320086-9ea6c200-9946-11e9-9d4f-6276f5e0dd5a.png)
![2019-06-28_01 08 24](https://user-images.githubusercontent.com/51100585/60320087-9f3f5880-9946-11e9-8b88-ce21e80724c7.png)

**Comment by ravenclawnc12** [comment]
so, i think this has to do with the cleric in some way 
![2019-06-28_02 04 24](https://user-images.githubusercontent.com/51100585/60320926-432a0380-9949-11e9-93d4-5bbc178e4f8e.png)
my clerics are in the 30s

**Comment by Shadows998** [comment]
For me it all started with the blessing of the cleric

**Comment by TangoTek** [comment]
Fixed in 1.0.57.  Unfortunately the damage is done and they do in fact have level 100. :-(
