### ISSUE TITLE
Locked trades

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#52]
**Describe the bug**
if you buy 7 items from the architect or tradesman at the same time they will lock this trade perminantly

**To Reproduce**
make a town hall
buy out all of a given token
lock the trade
wait forever

**Expected behavior**
trade never locks

**Screenshots**
![2019-05-26_19 25 32](https://user-images.githubusercontent.com/5202568/58385675-14d4a380-7fec-11e9-8ebd-35637207a4cc.png)

** Server/Location **
offline

**Additional context**
doesn't reset with game restart does reset with mod update

**Comment by TangoTek** [comment]
Thanks!  Fixed.
