### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by erragar** [TangoTek/TekTopia-Community#525]
Enchanted Villager Gear should give a small multiplier to the value of it to the Merchant over regular villager equipment.

Nothing grandiose, but a multiplier of between 1.25 and 1.5 times would probably be appropriate.

**Comment by Shamshalabim** [comment]
This was already suggested by Sobertron a while ago I believe.  I can't find the thread at a glance..

**Comment by erragar** [comment]
Oh, my apologies. I looked first I promise lol

**Comment by ThomasBerends** [comment]
It's in #288 , so this is a duplicate. @erragar You can close this issue if you want and add a :+1: to this issue.
