### ISSUE TITLE
Feature: Bartender

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#529]
Its as simple as it sounds, a bartender for the Tavern! I think this would be a cool job and bring more "life" to the Tavern. This of course wouldn't be required for a Tavern but if you were to have one it would attract more villagers to the Tavern as well as have them gain happiness faster!

**Comment by TangoTek** [comment]
I doubt this will ever be done.  I have many, many more things I'd do before this. I do appreciate the suggestion though!

**Comment by me2365** [comment]
Awww, when I saw priority 3 I thought it meant it was gonna happen soon.
