### ISSUE TITLE
Miners Cant Use Efficiency 5 Pickaxes

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#533]
I was lucky enough for my enchanter to make an Efficiency 5, Unbreaking 3 pickaxe when I soon discover he can't mine with it. He goes to the Mineshaft and begins his mining animation but doesn't break stone he just continues and repeats his animation over and over and over.

1: Give Miner Efficiency 5 Pickaxe

**Expected behavior**

N/A

Survival 1
X: 600 Z: 600

This is really effecting my supplies as I am down 1 miner and he also is taking up a mineshaft that has the potential of many ores.

**Comment by Grurim2k** [comment]
Same here. This has dropped my mining production by half :/

**Comment by pizzadino** [comment]
I can confirm that the picks my buggy miners are all using are eff5 and diamond. It also seems that the magic number at which they bug out is precisely level 64.

**Comment by Hedkracka** [comment]
Confirmed, all my miners with Eff 5 picks are going nowhere!
My lowest miner is 67, and she has a eff 5 pick and not digging.

**Comment by TangoTek** [comment]
Yep. Fixed this one today. It happens with very high level miners with high level picks.  Will be fixed in next patch.
