### ISSUE TITLE
Butchers do not craft leather armour

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#537]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
very simple, my butchers have never crafted leather armour, they have collected stacks of villager leather and have a crafting table

**Comment by Sobertron** [comment]
WE have the same problem. Since this was introduced our butchers have crafted nothing.

**Comment by Sobertron** [comment]
Upon further inspection it see,s like this problem might be related to charcoal. Not all charcoal is becoming a villager item. So if that is used to smelt ore or cook food the resulting item will also not be a villager item.

**Comment by TangoTek** [comment]
Fixed in 1.0.57
