### ISSUE TITLE
Chairs no longer has hitboxes and are indestructible.

### ISSUE THREAD

**Issue by JasperC88** [TangoTek/TekTopia-Community#538]
Exactly as the topic says, chairs no longer have hitboxes and are indestructible.

**To Reproduce**
1. Place a chair down
2. Can't remove it?
3. TNT doesn't work, maybe lava will?

**Expected behavior**
Unable to remove chairs at all.

**Screenshots**
![2019-06-26_17 12 04](https://user-images.githubusercontent.com/51308222/60167484-c4907180-9835-11e9-8125-ca538846bf8e.png)
What remains after 30,000 TNT explodes.

** Server/Location **
Individual creative world.

**Comment by Hedkracka** [comment]
Same as #514

**Comment by TangoTek** [comment]
This is fixed now
