### ISSUE TITLE
Miners go for same mineshaft, losers give up despite more available

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#547]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
I have above ground mines, 2 blocks apart, I tried 3 blocks apart with same result. In the morning all the miners go for the same mineshaft. Those who lose give up and walk away from the mines despite there being 19 other mineshafts available. The druids are also doing the same behavior except some will stay and try to regenerate the same mineshaft, others will lose interest and walk away. There will be 4 or more druids standing in front of the same mineshaft.

**Comment by me2365** [comment]
For me they both go to the same mineshaft but once one realizes the other is mining there he goes to a different mine.

**Comment by MetriCfan** [comment]
might be the fact I have 15 miners

**Comment by MetriCfan** [comment]
I made ALL the mineshafts have a buffer of 2 solid blocks between and this has helped

**Comment by MetriCfan** [comment]
seems I was wrong, it continues to happen, I started more underground mineshafts and the same result.
 If you fill the mineshaft up manually they will go in for one or two sessions then no interest
