### ISSUE TITLE
Guard not collecting gear upgrade

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#551]
Guard not collecting gear upgrade

I have several pieces of gear that are upgrades from the current stuff, but guard is not going to get any

Server #1

![2019-06-27_22 20 04](https://user-images.githubusercontent.com/20891568/60302098-e61f5500-992a-11e9-8bee-d3a6180a2388.png)
![2019-06-27_22 25 53](https://user-images.githubusercontent.com/20891568/60302099-e61f5500-992a-11e9-85ab-378a820d3624.png)

Its not just that guard, but others too, which need diamond legs and or chest.
![2019-06-27_22 31 19](https://user-images.githubusercontent.com/20891568/60302264-5af28f00-992b-11e9-8d5a-b80544577455.png)

**Comment by Grurim2k** [comment]
I also have this issue, have tried resetting village, resetting TH marker, everything I know of. The guard is also not eating.

**Comment by Curvn** [comment]
same issue haha

**Comment by Tonyafm** [comment]
I (TonyAFM) also am having the same issue.  Guards are not using player-made equipment that is left in storage area, Cleric also starved from not eating player made food in storage area.

**Comment by Hedkracka** [comment]
Fixed I believe

**Comment by treehugger667** [comment]
1.0.78 TekTopia mod server 'Leafytown' -860 3600

Guards have unenchanted diamond boots on and he will not upgrade to enchanted diamond boots in storage. Boots have prot 3 on them so they should be an upgrade that the guard will want.

![2019-07-27_23 54 14](https://user-images.githubusercontent.com/53134230/62002487-d41c0800-b0ca-11e9-9ea4-d806163090e6.png)

I have not kept tabs on the iron armor, but I believe all the guards still have un-enchanted versions on . The guards did upgrade the sword from non enchanted to enchanted.
