### ISSUE TITLE
Teachers Not Gaining Skill 

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#553]
I went AFK for 5 Minecraft days and before I left I remember checking my teacher and he had 28 skill. When I came back I checked my teacher as he was teaching children and he had 28 skill still.

1: Have teacher and school with Kids to teach
2: Wait

I think the teacher should gain skill constantly, multiple times per day if he does teach that day. It does affect my village when my kids don't learn from a high skilled teacher.

N/A

Survival 1 
X: 600 Z: 600

I think the teachers should be gaining skill, if I mistaken they should at least gain it a whole lot faster as I can *guarantee* he at least had 25 when I left.

**Comment by LadyGwynn** [comment]
I noticed this also... I started my school with a teacher at level 1. He taught at least a dozen students from birth through nitwit-hood and his skill level only advanced to 4.

**Comment by TangoTek** [comment]
Fixed in 1.0.52
