### ISSUE TITLE
Suggestion/Bug: Redstone price

### ISSUE THREAD

**Issue by me2365** [TangoTek/TekTopia-Community#554]
Earlier today there was an update including Redstone prices and quantities as the Merchant asks for Redstone in stacks of 32. However, the minimum price for Redstone did not change as it is still 2 emeralds like before. I believe that if I give him double the amount I should get double or at least a tiny bit more from it. Im not sure if this was intentional or you just forgot to add more to the price but I duo believe that it should be a higher minimum with the amount we give. I think the minimum should be at least 3.

**Comment by BlackDeath69AC** [comment]
it was intentional redstone profits were too high
