### ISSUE TITLE
Guards not eating

### ISSUE THREAD

**Issue by Grurim2k** [TangoTek/TekTopia-Community#557]
**Describe the bug**
Since the update today, none of my guards have eaten

**To Reproduce**
1. Have guards
2. Watch them not eat

**Expected behavior**
Guards don't decide to starve

** Server/Location **
Server 2, 4400, 4200

**Additional context**
At first I thought this was due to the sudden wave of foodies that hit my village, as once the miners started working, food vanished fast, but then I noticed that even when I filled it full of food, and increased food production, none of the guards were visiting the storage room for food. Now they are all getting low and I fear if I stay on, they'll all starve. The new guy is at 11 hunger and still just patrolling.

**Comment by SaltyJohnson94** [comment]
Same issue here. Mine all have villager food in their inventory but they are not eating it.

**Comment by me2365** [comment]
Same

**Comment by Annie8472** [comment]
I'm having the same problem. Lots of food is available, granted it's not villager food yet, but we have steak, mutton, and chicken all sitting in the store room for them. We have lost two guards to this today and are nervous about brining in more guards. I think more people are having this problem than are reporting. I also believe that "me2365" has a nitwit with the same problem. The guards refused to drop their diamond armor and weapons: 2 diamond helmets, 2 diamond leggings, 2 diamond boots, and 1 diamond sword... My third guard just died twice of starvation. As you can see in the attached screenshot, "me2365's" guard is down to one hunger so he/she logged out.
![2019-06-27_21 35 01](https://user-images.githubusercontent.com/51523021/60317360-8f624d00-9923-11e9-8d73-c6349ba110be.png)

**Comment by DocNox1408** [comment]
Guards arent the only ones being effected. Butchers and miners are dying of starve damage as well. I had 2 butchers die of starve damage in front of a single chest of golden carrots. The miner died in the storage room as well

**Comment by kennitha** [comment]
same problem here. logged off to keep them alive for now

**Comment by Grurim2k** [comment]
This appears to have been fixed in the most recent update. Closing thread.
