### ISSUE TITLE
Leads no longer work with children

### ISSUE THREAD

**Issue by pizzadino** [TangoTek/TekTopia-Community#562]
**Describe the bug**
Leads no longer work with children. They simply pop off after a second of connection. This is a problem because children don't seem to go to school of their own free will. It is necessary to be able to use leads on them in order to actually get them to go to school and to remove them from places they shouldn't be.

**To Reproduce**
1. Have children
2. Attempt to use a lead on a child
3. Watch lead pop off the child
4. Watch the child run up an down stairs all day for 5 days even when you st them to do nothing but go to school and they grow up to be int 1 nitwits.

**Expected behavior**
Children should be lead-able. The task algorithm should also be more forceful with actually having the children go to school in the short time before they grow up.

** Server/Location **
What if 2
-2790,6896

**Comment by TangoTek** [comment]
Leads work the same on all villagers now.  They get angry when leashed. If happiness reaches 0 the lead pops off. This is intentional.  Also, it should never be required to pull a child to school. If they aren't going as intended, then let's fix that bug rather than work around it.
