### ISSUE TITLE
Druid will starve himself

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#564]
The Druid will work him self to death by starvation rather than collecting food.  When he does get food he takes 2 pieces of meat, eats one, and puts the other one back.

![2019-06-28_19 52 11](https://user-images.githubusercontent.com/22623066/60377771-06105080-99df-11e9-89dd-839a2b61a3a6.png)
he's hungry but he keeps filling mines
![2019-06-28_19 52 17](https://user-images.githubusercontent.com/22623066/60377772-06a8e700-99df-11e9-81ad-b3ac4936766f.png)
![2019-06-28_19 52 26](https://user-images.githubusercontent.com/22623066/60377773-0872aa80-99df-11e9-8f86-fca2dc2ee5b7.png)
![2019-06-28_19 52 32](https://user-images.githubusercontent.com/22623066/60377774-09a3d780-99df-11e9-8067-b77c9b98eef0.png)
plenty of food in the chest
![2019-06-28_19 52 41](https://user-images.githubusercontent.com/22623066/60377775-0ad50480-99df-11e9-92dc-911e1d1368bf.png)
he ended up starving himself to death
![2019-06-28_19 53 12](https://user-images.githubusercontent.com/22623066/60377777-0c063180-99df-11e9-8185-d9304ae753c3.png)

**Comment by HexFlareheart** [comment]
Observing a similar problem with my rancher, although he has potatoes, carrots, etc. in his inventory and isn't consuming it. I've been abusing splash potions to keep him alive.

**Comment by TangoTek** [comment]
Should be fixed in 1.0.52
