### ISSUE TITLE
Bard not playing in tavern at night

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#568]
**Describe the bug**
Since the recent food update (.49) we have had an increase in unhappy villagers. Normally this would not be a problem as they all go to the tavern at night. However, the bard seems to not be playing in their at night anymore. He will stop his path finding when it is time to go to work in the tavern,

**Expected behavior**
The bard plays in the tavern at night. 

**Screenshots**
![2019-06-29_08 26 04](https://user-images.githubusercontent.com/49371154/60381163-27f1ed80-9a48-11e9-9667-d28f6c9bda7e.png)
![2019-06-29_08 26 22](https://user-images.githubusercontent.com/49371154/60381164-288a8400-9a48-11e9-9a5e-d908f0c023b5.png)
These images were taken less than 20 seconds apart. Tavern full of villagers but the bard is in the mines.

** Server/Location **
what if 1

**Comment by Hedkracka** [comment]
I have noticed this too, even tried leading bard to the tavern. He did nothing but left soon after and went to bed
![2019-06-29_22 28 56](https://user-images.githubusercontent.com/20891568/60389648-55c54980-9abd-11e9-9f16-24af0952a7a1.png)

**Comment by paspinall42** [comment]
I too have noticed this, I keep running in to my bards outside at night doing nothing

**Comment by LadyGwynn** [comment]
I noticed the same.
![2019-06-28_16 26 14](https://user-images.githubusercontent.com/42978079/60400971-c95c6a80-9b40-11e9-9f9b-3f251c32e858.png)

**Comment by TangoTek** [comment]
(!bard.isWorkTime() && bard.isSleepingTime())    

Yea... its hard to play songs only while you are sleeping.  #Idiot
Fixed in 1.0.52

**Comment by blackwellj** [comment]
This is still happening in .58
