### ISSUE TITLE
Miners using blacksmith

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#570]
Almost all my miners (12+)are travelling through my storeroom which has at least five furnaces available to travel to my blacksmith and use his furnaces to craft torches. Not sure if this is a bug but it sure looks funny when you see all the minors in the small blacksmiths trying  to use one or two furnaces.

I also observe the minors when they first go down the mineshaft asking to go for the same mineshaft have a little bit of an argument over who is it is and then the rest of the guys will just choose another mine shaft argue with that one a bit. 

The druids seem to do similar when they reform stone. Even when the mineshaft is fully reformed.

**Comment by TangoTek** [comment]
The storage structure will only register a single furnace. Any extras as ignored.  Miners also always prefer to work in the blacksmith.  This is all intentional.
