### ISSUE TITLE
Villagers Starving in 1.0.49

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#572]
**Describe the bug**
Keeping my Cleric alive with splash potions as she's starving, there is ample food in the storage

**To Reproduce**
no idea

**Expected behavior**
Eating when hunger bar reaches 0 is most important AI task

**Screenshots**
![2019-06-29_11 00 18](https://user-images.githubusercontent.com/5202568/60382644-f2f09580-9a5d-11e9-8fb7-4712a528f227.png)
![2019-06-29_11 00 27](https://user-images.githubusercontent.com/5202568/60382645-f2f09580-9a5d-11e9-9b88-f47048df6e2a.png)

** Server/Location **
Offline Creative 1.0.49

**Comment by Galarn20** [comment]
do you happen to have you food in a chest that is on the ground, also i had a guard that did this, he would not eat anything, i put some of my golden carrots in the chest and he ate them.

**Comment by TangoTek** [comment]
This should be fixed in 1.0.52
