### ISSUE TITLE
Chef not cooking

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#581]
I have 3 chefs and a lot of uncooked food, chicken and potatoes are just some of the foods.
But the chest i had that had cooked villager potatoes is now empty, so at some point the chefs stopped cooking, i have checked the GUI checkboxes, and have removed the ones that are pointless for me, and still no real joy

**Expected behavior**
I am expecting there to be an excess of food in my chests

**Screenshots**

** Server/Location **
On What if #1 
4257/9192

i do have a lot of wood for charcoal, (not much if any oak)
So that cant be an issue really

![2019-06-29_23 31 19](https://user-images.githubusercontent.com/20891568/60390089-60381100-9ac6-11e9-9a7e-953533f09bbc.png)
![2019-06-29_23 31 27](https://user-images.githubusercontent.com/20891568/60390090-60381100-9ac6-11e9-91d0-8bee233d3f0b.png)
![2019-06-29_23 32 41](https://user-images.githubusercontent.com/20891568/60390091-60381100-9ac6-11e9-8cc2-f9675c3013c6.png)
![2019-06-29_23 32 50](https://user-images.githubusercontent.com/20891568/60390092-60381100-9ac6-11e9-9ec1-c50920437a68.png)
![2019-06-29_23 33 08](https://user-images.githubusercontent.com/20891568/60390093-60d0a780-9ac6-11e9-9e85-ba5c3ef225b1.png)

**Comment by Hedkracka** [comment]
Still having issues, my chefs have got reduced tasks, and are still not cooking potatoes or meats.

**Comment by TangoTek** [comment]
I stopped by and your 3 chefs were cooking tons of chicken, steak, and potatoes.
