### ISSUE TITLE
My villagers wont eat carrots and I think I know why (its a bug)

### ISSUE THREAD

**Issue by silenthawk123** [TangoTek/TekTopia-Community#582]
**Describe the bug**
"my farmers were not eating and were also starving even know I had carrots, and I did some cheaty testing (on a singleplayer world) and found out that they would eat steak, and I've come to the conclusion that they only see carrots as seeds, not food."

**To Reproduce**
"1. have a village that only has a farmer and a carrot farm
2. make sure you have no other food apart from villager carrots in the stockpile
3. when the villager is hungry you should see that he won't eat the carrots
4. See error"

**Expected behavior**
"I expected the villager to eat the carrots when they were starving"

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?
"I'm in a singleplayer World"

**Additional context**
"not that I can think of."

**Comment by Hedkracka** [comment]
could also be this

Food Variety system! The happiness your villagers receive from food will now be dependent on how often they've eaten that food recently.
    Each villager keeps track of the last 5 foods they've eaten.  When evaluating potential next meals, they check how many times the food is on that recent list.
    The number of times they've recently eaten that food will modify the happiness they receive from that food.

    Times Eaten: Modifier
    0:5  1:0  2:-3  3:-7  4:-12  5:-18
from patch 1.0.49 notes

**Comment by Sobertron** [comment]
We have villagers who eat carrots all the time. As previously stated, they will eat food that provides both an increase in hunger for the appropriate of happiness they need.

It a villager is hungry but they have high happiness they will eat basic foods like carrots and potatoes. If they have low happiness they will go for those better quality foods.

**Comment by Annie8472** [comment]
We lost three druids and one cleric within a couple of minutes due to starvation today. We had a variety of food for them in the storeroom and happiness levels are all high every time I look. Naj suggested that we feed them pumpkin pie, so pumpkin pie I did make and the villagers came a running. They don't want the carrots, potatoes, and beets any more.

**Comment by TangoTek** [comment]
Should be fixed in 1.0.52
