### ISSUE TITLE
Druids all try to regrow the same mine

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#583]
All the druids in a village will all try to regrow the same mine.  While this is not a problem with 6 or so druids, it just means mines get filled 6 layers at a time.  However, any more than that will end up piling up outside of casting causing them to not regrow the mine at all.  Additionally the front druid can get forced in to the mine by the rest apparently tripping the "villager in mine dont fill" switch.
A solution could be to have druids "reserve" a mine as they are walking towards it that other druids will ignore.  A similar system could make miners work faster as well. (they also all walk to same mine before spliting off 1 in each mine)

**Comment by Makion65** [comment]
Mine are doing the same thing. But they'll only fill 2 or so mines, then go wander for a while. Not super helpful..

**Comment by Hedkracka** [comment]
#570 mentioned later in the report

**Comment by TangoTek** [comment]
Fixed in 1.0.58
