### ISSUE TITLE
Segestion: AI Module Menu drag and drop

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#594]
It would be cool to be able to drag and drop ai modules to re prioritize them, even the always on modules. (or to change collection amounts) I would like to be able to experiment with moving the "drop off crops" "plant crops" and "harvest crops" modules around to see if I could make my farmers spend less time walking back and forth to the storage.  Similarly for miners I would love to be able to tweek the number of torches they collect on each trip to the storage, or the amount of ore mined triggers a return to storrage for drop off.

**Comment by TangoTek** [comment]
Reordering task priorities is much more difficult than just putting an extra check in each of them. This is mostly just the way that Minecraft's entity AI system works.  I put some thought into this before I started the AI feature, but passed on it.  Sadly this isn't likely to happen.
