### ISSUE TITLE
Inter-Mod Compatibility - Replay Mod: Animation tempo appears to be tied to render FPS

### ISSUE THREAD

**Issue by gotnate** [TangoTek/TekTopia-Community#596]
Example video compositing a masked 60 fps video over a 30 fps background layer of the exact same replay-mod camera path:

https://youtu.be/GrBjWWWcmT8

**Comment by TangoTek** [comment]
The animation system I'm using bases everything off 60fps. This isn't really within my control to fix without rewriting my own animation system
