### ISSUE TITLE
"Sleep Walking" Villager

### ISSUE THREAD

**Issue by Coolkc456** [TangoTek/TekTopia-Community#598]
**Describe the bug**
Found this enchanter walking in a sleeping position.

**To Reproduce**
Not sure how to reproduce.

**Expected behavior**
Villager should walk upright.

**Screenshots**
https://media.giphy.com/media/VekwHzOwb9Jnac97e9/giphy.gif

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? What If #2
What are the world coordinates of your town hall marker? -64 71 4476

**Comment by TangoTek** [comment]
Fixed in 1.0.58
