### ISSUE TITLE
Villager sleeping in the storage room

### ISSUE THREAD

**Issue by Coolkc456** [TangoTek/TekTopia-Community#599]
**Describe the bug**
Found a villager sleeping in the storage room even though there's no beds near by. Could be linked to #598.

**To Reproduce**
Unsure how to reproduce.

**Expected behavior**
Villagers should sleep in their beds.

**Screenshots**
https://media.giphy.com/media/ZZqgEtaGFvMCGvMTvE/giphy.gif

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? What If #2
What are the world coordinates of your town hall marker? -64 71 4476

**Comment by TangoTek** [comment]
Fixed in 1.0.58
