### ISSUE TITLE
Villager tool not better than non-villager tool?

### ISSUE THREAD

**Issue by ThomasBerends** [TangoTek/TekTopia-Community#600]
**Describe the bug**
My butcher was not picking up a villager iron axe to replace his regular iron axe. It is a better tool for him, and would result in me getting villager items instead of regular items. Not sure if this is as intended.

**To Reproduce**
1. Give Butcher a regular iron axe
2. Get Blacksmith, let him make an iron axe
3. Butcher keeps using regular iron axe, creating non-villager items

**Expected behavior**
The Butcher replaces his regular iron axe for the iron axe that the blacksmith made, so that he makes villager items instead.

**Comment by TangoTek** [comment]
Good one. Fixed in 1.0.52
