### ISSUE TITLE
Cleric Bless/Heal Merchant, Nomad, Architect and Tradesman

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#602]
**Describe the bug**
The Cleric can bless the Merchant, Nomads, Architect and Tradesmen. No impact on trade prices. However, the Merchant is now speedier and even harder to catch in the village than he already was :')
Tested this on a single player world with only a cleric in the village, however, discovered it whilst playing my single player world with 50+ villagers and noticed I couldn't catch the Merchant...

![Blessed be the Merchant, speedy as hell](https://user-images.githubusercontent.com/52452881/60541688-13447c80-9d0a-11e9-9964-8044e6fe3ecd.png)

**To Reproduce**
Version 1.0.51
1. Have a Cleric
2. Have no other villages
3. Watch your Cleric bless (and heal if necessary) the Merchant, Nomads, Tradesmen and Architect.

**Expected behavior**
Cleric should not waste his bless on the Merchant, Nomad, Tradesman or Architect. 

**Screenshots**

** Server/Location **
Discovered in Single Player village with 50+ villagers, Cleric happened to choose the Merchant.
Tested on Single Player world with dirt hut town hall, egg spawned Cleric and naturally spawned Merchant and Nomads.

**Additional context**
The Merchant is hard enough to find/catch in a busy village already :')

Version 1.0.51.

**Comment by TangoTek** [comment]
Clerics will now only heal residents of the village.
