### ISSUE TITLE
Gamerule doMobLoot

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#605]
**Describe the bug**
If a player turns off gamerule doMobLoot, when the Butcher kills a Cow/Chicken/Sheep, the animal will drop the meat but will not drop the Leather/Feather/Wool.

**To Reproduce**
1. Go to singleplayer
2. Set gamerule doMobLoot false
3. Watch your level 100 butcher slaughter countless Chickens/Cows/Sheep with a diamond villager enchanted axe
4. Not a single Feather/Leather/Wool will drop for the Butcher

**Expected behavior**
- Gamerule doMobLoot should result in either no villager items dropping (including the meat), or drop both the meat and the feathers/leather/wool

**Screenshots**
No screenshots.

** Server/Location **
Single player confirmed 

**Additional context**
- To make the nights more challenging, I have always on command blocks insta-killing hostile mobs that don't target the villagers and guards don't target (enderman, creeper, skele, spider etc...) so that there are more Zombie spawns, making the guards job tougher. The side effect is that they drop loot, so I turned off the gamerule to avoid too many entities.

**Comment by TangoTek** [comment]
Fixed in 1.0.58
