### ISSUE TITLE
Teacher doesn't create name tags

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#608]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
might be same issue as butcher in not recognising the crafting table

**Comment by TangoTek** [comment]
Sure was.  Thanks!
