### ISSUE TITLE
Druid not regenerating mines

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#61]
**Describe the bug**
Druid doing their animation but it's not regenerating any part of the mine even a little.

**To Reproduce**
Set up a mine, watch a druid

**Expected behavior**
when the druid does his mine regeneration the whole mine should replenish with at least stone

** Server/Location **
Offline

**Comment by tomerorian** [comment]
@JohnyDL The druid replenishes only part of the mine (2 blocks from what I see). Whether that is the intended behavior or not I do not know

**Comment by JohnyDL** [comment]
Yup I see that in the newer update, I don't know if it's a fix or just me not being able to tell what they were doing but this is resolved
