### ISSUE TITLE
Chefs consume buckets and milk when making cake

### ISSUE THREAD

**Issue by Taggerung179** [TangoTek/TekTopia-Community#612]
**Describe the bug**
I was watching my chef make some cake. He had 3 buckets of milk, and after making the cake, he had only 1 empty bucket in his inventory.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by TangoTek** [comment]
Great catch!  Fixed in 1.0.58
