### ISSUE TITLE
Suggestion: Beer in tavern gives hunger points

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#619]
As stated it would be good if a villager who visits the tavern gains a few hunger point (5-10) to aid in surviving the after beer hangover, (waking up starving)

**Comment by JohnyDL** [comment]
Conversely drinking costs hunger but if you put food in a chest in the tavern the drinkers will eat it.

**Comment by TangoTek** [comment]
Not really interested in this feature, sorry.
