### ISSUE TITLE
Butchers can Harvest Baby Cows

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#621]
If a baby cow manages to find its way in to the butcher shop (saaaaay by accidentally positioning a cow farm directly above the shop so they calves cant help but fall in, (purely hypothetical of course)) The butcher will murder said baby cow and collect regular amounts of beef off of it thus eliminating any need to wait for the baby cow to grow up or consume food in any way.  Also, because of the villager animal mechanics the tank of "breeder" cows does not need to be villager since if the rancher feeds 2 non villager cows villager wheat a villager cow is born until fed player wheat, since that cow is murdered immediately, it never needed to be fed.

**Comment by TangoTek** [comment]
Fixed in 1.0.60
