### ISSUE TITLE
Guards don't actually sleep during the day

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#624]
**Describe the bug**
Guards who's sleep pattern are set to sleep during the day, don't actually go to sleep. They return to their houses and wander the house. When the player passes by they salute as usual. 

**To Reproduce**
1. Have multiple guards
2. Find a guard that is up at night
3. Follow them home

**Expected behavior**
Guards should remove armor and lay down in bed, sleep.

**Screenshots**
![Guards 1](https://user-images.githubusercontent.com/52452881/60730489-30ad5c80-9f3d-11e9-8b43-2dc5a06cc908.png)
![Guards 2](https://user-images.githubusercontent.com/52452881/60730490-30ad5c80-9f3d-11e9-9dc2-8d7fb49546e5.png)

** Server/Location **
Confirmed for single player, version 1.0.58

**Additional context**

**Comment by Nightshae** [comment]
I've also noted this issue.  About a third of my guards are actually sleeping during the night, the rest are up and on patrol.  The ones that are up all night are not sleeping at all.


![2019-07-02_19 55 48](https://user-images.githubusercontent.com/51100661/60735547-51a38c80-9f00-11e9-8625-1f8a991c4c5f.png)

**Comment by TangoTek** [comment]
Fixed in 1.0.59
