### ISSUE TITLE
Nitwit Skills

### ISSUE THREAD

**Issue by sarastar868** [TangoTek/TekTopia-Community#625]
**Describe the bug**
My level 30 intelligence nitwit had some low level skills like teaching and ranching from observing as a child. When I made him a farmer, he lost those skills and became a level 30 farmer. Becoming a level 30 farmer is expected, but losing his other skills is not.
**To Reproduce**
1. Have a kid
2. Let them level up by observing nearby adults level up
3. When they grow into a nitwit, give them a job. (It may only be farmers, idk.)

**Expected behavior**
I expected him to keep his other skills.

**Screenshots**
![2019-07-05_11 12 10](https://user-images.githubusercontent.com/52576104/60731604-f8deee80-9f15-11e9-9f9a-fe14980f6699.png)

** Server/Location **
I was playing on a single player world.

**Additional context**
He was born before I updated to the latest Jar file. There may have been some weird stuff going on because he straddled two versions.

**Comment by Snodderz** [comment]
**Nitwit

**Comment by BlackDeath69AC** [comment]
The other skills while villager is a nitwit is either a visual bug any profession you assign to the villager will be automatically put at said nitwits intelligence level

**Comment by Snodderz** [comment]
> The other skills while villager is a nitwit is either a visual bug any profession you assign to the villager will be automatically put at said nitwits intelligence level

It's not a visual bug, Children gain levels of skills whilst being in the vicinity of other villagers that level up. These skill levels are maintained when the child changes to a nitwit. This bug report is valid and correct.

Someone is going to ask the question, what is the point in children gaining skill levels whilst being in the vicinity of other villagers, when the child will likely grow up with a much higher intelligence level (thus first assigned skill level) anyway? The answer is that not everyone will have a school and/or teacher, certainly not in the early stages of a village.

**Comment by TangoTek** [comment]
Bug fixed in 1.0.59
