### ISSUE TITLE
Necromancer Wither Skelly Army

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/TekTopia-Community#629]
**Describe the bug**
Recently the Necromancer has not really been working. He will spawn in, summon a few things and then despawn, a lot of times before we can even find him. However, on occasion, he instantly summons a massive army of wither skeletons, didn't get an exact count but you can see them in the screen shots below.

**Expected behavior**
Necro will slowly summon in other mobs.

**Screenshots**
![2019-07-05_14 15 11](https://user-images.githubusercontent.com/49371154/60739184-e33ee880-9f58-11e9-9be1-2c36e8740a85.png)
An image from the ground as i battle them until my guards arrive.

![2019-07-05_14 16 51](https://user-images.githubusercontent.com/49371154/60739235-1aad9500-9f59-11e9-9a48-07c344f0c5cf.png)
![2019-07-05_14 17 34](https://user-images.githubusercontent.com/49371154/60739236-1aad9500-9f59-11e9-9c7d-a06a5c498a10.png)

Makani was online at the time, called her over and she was able to caputre this beautiful sight.

** Server/Location **
What If 1

**Additional context**
While our village has no issues with defending this attack, i imagine others might now be so lucky. Additionally, we are using this as a tactic to gather wither skulls. We have collected 16 thus far from attacks like this.

**Comment by TangoTek** [comment]
if ( village.owner == "Sobertron" )
     initiateInsaneMode();

**Comment by Shamshalabim** [comment]
if ( village.owner == "Pikachu" )
etc etc

**Comment by TangoTek** [comment]
Yea, looked at the formula. This is what should happen when you have a village your size.
So yea.  Working as intended :-)
