### ISSUE TITLE
BUG - Bard Sound

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#640]
**Describe the bug**
If the player is outside the range at which you can hear a Bard when the Bard starts a song, when the player moves closer/within range, the bard is still not heard. The Bard makes the playing song animation but no sound is heard. You can literally stand right next to them and nothing heard. This bug occurs whilst the Bard plays in both the Tavern and the Village.

**To Reproduce**
1. Have a bard
2. Move far away, watch the bard, wait until they start a song
3. When you see the Bard start a song, move close to the bard
4. See error (Hear error)

**Expected behavior**
The Bard song should begin to be heard whilst the player moves within range

**Screenshots**

** Server/Location **
Confirmed on Single Player

**Additional context**
Confirmed in version 1.0.58.

**Comment by TangoTek** [comment]
I can't really fix this due to Minecraft's audio system. Its not meant to play long songs.  Its annoying though I know.
