### ISSUE TITLE
Guard ignores zombies when going to bed or guard post

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#642]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
I have noticed that when a guard has decided to go to a guard post or to bed they will ignore a zombie even if it is right in front of them

**Comment by TangoTek** [comment]
Should be fixed in 1.0.59
