### ISSUE TITLE
Nomads still steal food 1.0.58

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#659]
in version 1.0.58 I caught multiple Nomads and the merchant stealing food from my supply 
![2019-07-08_17 39 34](https://user-images.githubusercontent.com/22623066/60847256-b6344500-a1a7-11e9-9d3a-07a05f5ecf51.png)
![2019-07-08_17 38 57](https://user-images.githubusercontent.com/22623066/60847257-b6344500-a1a7-11e9-99e6-6bcb11d935d0.png)

**Comment by TangoTek** [comment]
Yep. Fixed in 1.0.59. Thanks.
