### ISSUE TITLE
Suggestion: New Villager - Landscaper

### ISSUE THREAD

**Issue by UndeadFrog** [TangoTek/TekTopia-Community#661]
Suggestion:
New Villager Type: Landscaper

Clears and flattens the land around the village, this could be controlled through 4 markers (e.g. 4 villager made fence posts) where the landscaper clears and/or fills the land to match the y level within the markers.
This villager could also craft torches to light up the area similar to miners within their mine shafts, as well as create paths between the different buildings in your village (could potentially give other villagers a speed boost when they use these paths.)

benefits:
The addition of this villager would provide a use for the shovel where there currently is none (would also use other tools depending on what blocks must be cleared)
With the land slowly being cleared and paths being made, the village would start to feel more alive.
Potential outlet for renewable dirt, sand and gravel if combined with druids being able to regenerate the land similar to how they do so with mine shafts.
Provides more potential trades with the merchant.

**Comment by TangoTek** [comment]
Not likely to happen, sorry. I'm not really a fan of any villager that builds or changes the blocks drastically.
