### ISSUE TITLE
BUG - Crafting Bench/Furnace/Enchanting Table/Anvil

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#668]
**Describe the bug**
Villagers can all use a Crafting Bench/Furnace/Enchanting Table/Anvil at the same time. I've just witnessed x4 Blacksmiths hammering on the same Anvil. I've seen x2 Enchanters use the same Enchanting Table at the same time and I've seen x3 Enchanters use the same Crafting Bench to craft books at the same time.

**Suggestion** - If multiple Enchanters need an Enchanting Table, but there's only one in the Library, one Enchanter will use it, the others will wander the Library with an Enchanting Table symbol above their head, losing small amount of happiness every few seconds. Once the Enchanting Table becomes free, they use it. Same behavior for all villager types that require a utility block. Ensure structures recognize more than one utility block (like how the Blacksmiths and Kitchens recognize multiple furnaces).

**To Reproduce**
Have multiple of a villager type and only one Anvil/Enchanting Table/Crafting Table. It's regularly visible in the storage room.

**Expected behavior**
Only **one villager at a time** should be able to use a utility block.

**Screenshots**

** Server/Location **
Single Player

**Additional context**
Version 1.0.59, but has been in play since beginning.

**Comment by TangoTek** [comment]
good suggestion.  Added to 1.0.60
