### ISSUE TITLE
Crafting/Collecting Count Tweak

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#669]
**Idea**
So the UI for the turning on and off what you want villagers to do is fantastic but I have a feeling another extra tweak here could help: setting the number of stacks of these items that the villagers are to try to make available in the storage.

-1 is make this infinitely probably not something you want to do generally speaking, But might be something you set for farmers and miners and lumberjacks
0 is make the default amount of this item that Tango decided
n is make n stacks of this item available in the storage system

Some examples of how this might be set up

I might want to set all my farmers to make sure I have 5 stacks of each crop in storage at all time and then give each farmer a focus after that point, one might harvest infinite wheat, one might harvest infinite carrots, one might only go round planting seeds, one might make sure all the ground is tilled. Most of the time they'll be doing this focused task but when the storage is running low on say Carrots cause I just sold 5 stacks to the merchant, they all converge on carrot harvesting until the storage is back at 5 stacks. Some jobs I might decide only to stop doing them if there's less than 1 stack, for example making sure everything stays tilled if it's one villager's job is more important than getting crops for the merchant but if the village is at <1 stack then the village might be starving and that's more important than tilling. Other jobs maybe I want 10 stacks as a minimum so I want 10 stacks of carrots and wheat before a villager focuses 100% on sugarcane. And I might want it different per farmer so when it's at <1 stacks everyone pitches in but <5 stacks only half of the farmers help and <8 is a quarter and when at 10+ stacks it's only the farmers that have that as their focus will harvest that item

For say the Blacksmith I might have a few blacksmiths and I could want one to focus on guard stuff while the other makes everything else, but each could still help out the other in a pinch, the guard who makes armour and swords is maybe aiming for 6 peices of each of these in the storage with one of everything else, while the tool making guy might be the other way round he's set to make 10 hoes for the 10 farmers in case they all run out at the same time, 5 picks for the 5 miners, 10 buckets for milk, 2 sets of shears and again 1 set of armour and a sword so when this is 0 he helps pick up the slack. There could even be a smelting blacksmith that only makes 1 of each and otherwise is in charge of just smelting all the ores that come into the storage and keeping 9 stacks of charcoal and 9 stacks of torches available for the miners.

Miners could ignore a specific ore in shafts if the player doesn't want/need more of it
Lumberjacks could target trees in a wood farm when the storage is low and then focus on the player's favourite types for building
Enchanters can have their number of enchanted books made limited or have increased paper/unenchanted book to stock
Teachers can make nametags up to a limit defined by the player
Butchers could aim for specific animals based on needing more of that meat/leather/feather
Ranchers might stop sheering when they have enough wool in storage
And so on and so on.

By allowing the setting of how full the player wants each villager to make the storage with their item it basically allows some of these priorities to be a little more automated. The player doesn't have to check the main storage and shut down the items when there's enough of them in that player's eyes

**Comment by TangoTek** [comment]
While I agree this would be nice, there is almost no chance it'll be done any time soon.  Besides, it can all be achieved with a bit of micro managing of the AI filters.

**Comment by JohnyDL** [comment]
yeah the micromanaging is fine with small villages and small sorting systems but ... I should really record a typical day in my village at some point... it's more stress than fun right now
