### ISSUE TITLE
Zombie Pigmen auto-hostile to villagers

### ISSUE THREAD

**Issue by KeyokeDiacherus** [TangoTek/TekTopia-Community#67]
**Describe the bug**
A spawned zombie pigman from a nether portal immediately tracked and started attacking our villagers.  He was not angered.  

**Expected behavior**
Zombie pigmen are non-hostile until angered.

** Server/Location **
Main(Survival) - server 1
Town Hall: Donkey-Pichu

**Additional context**
This happened right before the 8:39 (tango time) crash.  It killed a villager, the game crashed, we rejoined, and were able to attack and kill it before it killed the villager.

**Comment by Mathking18** [comment]
Zombie Pigmen being hostile towards Villagers is a Vanilla interaction. Not surprised.

**Comment by KeyokeDiacherus** [comment]
> Zombie Pigmen being hostile towards Villagers is a Vanilla interaction. Not surprised.

Try going into a creative game and spawning villagers into the nether.  The Zombie Pigmen don't care.  However, as soon as you spawn in a TekTopia villager, the Pigmen attack

**Comment by TangoTek** [comment]
Fixed. Thank you.
