### ISSUE TITLE
Request: Butcher split kill task

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#675]
![butcher request](https://user-images.githubusercontent.com/20891568/61082067-9d829400-a420-11e9-8aab-e29fcc710dc0.PNG)

Current task Butcher animals

Request split this into animal types, so that you can specify which animals are butchered to aid you in rebuilding stock of animals

**Comment by TangoTek** [comment]
Good suggestion. Done in 1.0.60
I added Retrieve Cow/Sheep/Pig/Chickens and removed Retrieve Animals
