### ISSUE TITLE
Necromancer minions should not die with necromancer plus coal from Wither Skeletons to be villager coal

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#678]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
The necromancer is so easy to kill once you have a decent bow or sword. It's easy to skirt his minions and kill him and thus them. At advanced levels (say level 3 necro onwards or once you hit 40-50 villagers) that the minions don't die with the necro. Most people like a decent fight. Also the guards should pick up the coal from Wither Skeleton kills and it can be villager coal that they place in the storage.

**Comment by TangoTek** [comment]
The Necro summons the undead. He controls them.  When he dies nothing is left to keep them going.  

If its too easy to skirt his minions then he needs to be made harder.
