### ISSUE TITLE
dogs are killed by butches 

### ISSUE THREAD

**Issue by Minetrain2002** [TangoTek/TekTopia-Community#679]
**Describe the bug**
if a pet for example a dog is in the butcher shop it is killed by the butcher 

**To Reproduce**
put a pet dog in or near the butcher shop and wait for the butcher to kill it 

**Expected behavior**
the butcher will run the killing animation and the dog will die
**Screenshots**

** Server/Location **
What server were you playing on? 
Main(Survival) server 2 
What are the world coordinates of your town hall marker?
X,Y,Z -7326 , 73, -6020

**Additional context**

**Comment by TangoTek** [comment]
Fixed in 1.0.63

**Comment by Minetrain2002** [comment]
Thank you for your swift fix and responce
