### ISSUE TITLE
Suggestion: Creepers and Builders

### ISSUE THREAD

**Issue by toasterhead-master** [TangoTek/TekTopia-Community#683]
I want to share an idea that I had for TekTopia.
![necromancer's suicidal creeper](https://user-images.githubusercontent.com/36490163/61137208-c6149780-a4cd-11e9-9539-db752991bc2c.jpg)
### Idea:
The necromancer can now not only summon creepers but also use them in his own advantage. Summoned creepers become much more loyal to the necromancer and now blowing up obstacles that the necromancer is facing. They blow up buildings nearby him that interferes him from moving on. You better now build a wall around your village, otherwise, the creepers will blow up the buildings!
### Catch:
The summoned creepers will tend to blow up buildings only. I was playing with a mod that makes the creepers blow up as they run fast, and it wasn't fun at all as they blow up and you die instantly no matter what armor you have. I didn't know where they come from and I couldn't prepare for them. That's why the summoned creepers will tend to blow up buildings only and avoid villagers and mobs.
### When and where?:
I believe the necromancer will have this ability after level 3 in order to give the player time to build walls around the village.

Overall, you'll need to fix your buildings more often now. Or not? This leads us to the second Idea:
![builder villagers](https://user-images.githubusercontent.com/36490163/61137207-c6149780-a4cd-11e9-81ff-7d5f0fdc7f13.jpg)
For this, I'm gonna use the MineColonies mod. MineColonies has the same idea for creating a civilization mod for Minecraft, but it is different than TekTopia. The only common they have is the job choosing system (kind of) and the idea of different buildings for different professions. I'm not gonna explain in details about the mod, but basically, I got the idea of builders from there.

### Idea:
Bob the builder! I mean, builder villagers. The builders are gonna recreate the buildings the player has built so the player doesn't need to build the same building all over again. Moreover, they will fix the damage given by the creepers. They'll, of course, do all of that only if the player, as the mayor of the village,  gives them the task to. They will not decide what to build by themselves, but they have a list of tasks to do.

### Builder's job:
Overall I believe you get the point:
1) Check the list of buildings to build.
2) Select the first building on the list.
3) If the first building on the list has maximum builders, then move to the next task.
4) Take the resources from the storage room.
5) If the builder lacks some resources, then use the available ones until you don't have any. Then ask for more resources or continue the next task on the list.
6) Go to the building area.
7) Remove all the blocks inside the building area.
8) Build/Repair/Upgrade the building.

### Leveling:
The builder's building/crafting speed would depend on their level. The more level the much faster the builder builds.

### Instructions:
**New items:**
There will be 3 more items to the mod. Each of them you can buy from the Architect:
1) Building selector - selects the building you want to give to the builders to build.
2) Building placer - places the place where you want the builders to build the building (can change the direction of the building and depth).
3) Repair selector - selects the nearby place that the summoned creeper destroyed and gives the command to repair it to the builders.

**How to use these items:**
MineColonies has only two items, the building selector and the building placer. I'll use them in order to demonstrate the building process.

> 1) First of all, you have to select two points with the building selector item.

![tut1](https://user-images.githubusercontent.com/36490163/61137215-ca40b500-a4cd-11e9-9d88-3efb6864ef12.jpg)
![tut2](https://user-images.githubusercontent.com/36490163/61137216-ca40b500-a4cd-11e9-9e52-b85585f128a4.jpg)

> 2) Secondly, you choose where to place the building using the building placer item. You can turn the building in 4 directions and move it to the right, left, up, down.

![tut3](https://user-images.githubusercontent.com/36490163/61137217-ca40b500-a4cd-11e9-9873-a7b21a12f732.jpg)

> 3) After you placed the building, the borders of the building should appear so you can see where it is built. The MineColonies mod uses custom borders for that, but I think vanilla fences would be just fine.

![tut4](https://user-images.githubusercontent.com/36490163/61137219-ca40b500-a4cd-11e9-9478-1bb8c180dc8c.jpg)

> 4) After that, you'll see the builder goes right away building the house! Now, the way it works in MineColonies is that the builders stand in the corner spot all the time acting like they are building. The blocks appear one by one and it looks like something is being built! I believe they did that in order to not complex things. Anyways, it is actually satisfying to watch it being built like that.

![tut5](https://user-images.githubusercontent.com/36490163/61137220-cad94b80-a4cd-11e9-856b-3ec9a3d6f057.jpg)
_And no, I'm not using the blocks and building it by myself. I had to give the builder the resources in order for him to build._

![tut6](https://user-images.githubusercontent.com/36490163/61137221-cad94b80-a4cd-11e9-9af5-70ae8d66fc49.jpg)

> 5) And...its almost done! After it's done the border has to disappear, and you have a complete recreation of the building! Thanks, Grace for participating in this project!

![tut7](https://user-images.githubusercontent.com/36490163/61137222-cad94b80-a4cd-11e9-8a0e-a3d42636a544.jpg)

> 6) Oh no, the building got destroyed by a creeper! And I don't remember how it was built! No worries, because now you can select the place the creeper blew up and the builder will go fix it!
Now you want to use the repair selector item:

![tut8](https://user-images.githubusercontent.com/36490163/61137223-cad94b80-a4cd-11e9-8448-3eb81c63858c.jpg)

> 7) The way I thought it will work is by saving the destroyed blocks that the summoned creeper destroyed. Then you should be able to select areas with the repair selector without any trouble.

![tut9](https://user-images.githubusercontent.com/36490163/61137224-cb71e200-a4cd-11e9-8145-6b549f4959f3.jpg)

> 8) The MineColonies obviously didn't have that feature so I just copied the wall before I destroyed it. I believe that fixing areas don't need any borders or fences around it.

![tut10](https://user-images.githubusercontent.com/36490163/61137225-cb71e200-a4cd-11e9-933c-0c9dd8299e9e.jpg)

>9) And it's done! I just love how Catherine entered the building in order to fix it. Well done Catherine!

![tut11](https://user-images.githubusercontent.com/36490163/61137226-cb71e200-a4cd-11e9-9c6c-f1e7e3458607.jpg)

### Summarize:
**The summoned creepers:**
I think the summoned creepers will make the village more challenging to maintain and complete the necromancer as the most dangerous mob in the game. The walls around the village will become more important than ever and most importantly, it will look epic :D

**The builder:**
A new job that frees the player from repetitive building and completes the village for having all different kinds of routine jobs (From farming to mining). It enables the player to focus more on the economy of the village and to have more time to build unique buildings that are built only once. The player can now choose the same building to be built in different places around the village. It can be houses or it also can be walls and towers around the village!
But most importantly, they remember each detail on each building structures. They remember the blocks around a house that was damaged by creepers and eventually fix it!

**Thanks for reading:**
I had a lot of fun creating the images and having this idea in my mind. Even if this feature will not be in the final release of the TekTopia mod, that's fine ;). Anyways, good luck with TekTopia!

**Comment by SaltyJohnson94** [comment]
Love it! The builders would be a fun addition for sure! Especially if you could use your own designs that you made in creative or downloaded.

**Comment by TangoTek** [comment]
I don't want builders as part of the mod. Never have.  Sorry.

**Comment by toasterhead-master** [comment]
Ok. Why not tho? Is it gonna ruin the point of TekTopia or it's just gonna make things too easy?

**Comment by TangoTek** [comment]
I've always wanted the player to do the building.  If the villagers build then 1) all villages will look the same an 2) the player will have even less to do

**Comment by toasterhead-master** [comment]
Well, I never said they are gonna build custom structures within the mod, but I totally get that the player will have less to do. My Idea was basically that the builders can build only the structures that the player has already built. That's why the villages will not look the same, and the player still has to build the structures first. The question is whether or not the feature will ruin the fun of building, even if it's getting repetitive sometimes?
As I was typing it I came up with I think a brilliant solution. What if, the bigger structure for the builders to build, the more they charge for it? What if in order for the builders to work, you'll have to pay for it? That will have the player think twice before spending the emeralds for the buildings. Some might find it easier to build the same stuff over and over again by themselves, and the rich will have the ability to recreate their own building by buying the builders!
So if they want, let's say, copy some big and complex structure from their creative map. They will have to pay a lot of money. So that will be their goal, to save money in order to "buy" the building and the builders will recreate the building inside the village! It will still take time for the builders to build it tho.
Kind of fun solution. It might still take a while to make this feature tho, you decide.
