### ISSUE TITLE
Butcher Problems

### ISSUE THREAD

**Issue by Amphibiangamer10** [TangoTek/TekTopia-Community#684]
Describe the bug
There are two problems with the butcher. 1) The butcher has incorrect names for new ai (gathering specific animals). 2) The butchers will not craft axes, even though the axe icon appears above their head, there is a crafting table in the butcher shop, and there is wood in the storage building chests.

1)
1. Create a village
2. Get a butcher
3. Click on the AI tab, and scroll down.
2)
1. Create a village
2. Get a butcher, butcher shop with a crafting table, and stocked animal pens
3. Have the butcher break their axe

Expected behavior
1) There should be names such as Collect Chicken, Collect Pig, Collect Cow, and Collect Sheep.
2) The butcher should pick up wood from the storage, then craft wooden axes with it.

Screenshots 
![Untitled 1613](https://user-images.githubusercontent.com/51340428/61152835-b03fac00-a4a6-11e9-8cee-b05cdfb238f6.jpg)
![Untitled 1614](https://user-images.githubusercontent.com/51340428/61152836-b0d84280-a4a6-11e9-8af5-b726e71b1b26.jpg)
![Untitled 1612](https://user-images.githubusercontent.com/51340428/61152837-b0d84280-a4a6-11e9-9104-d47715f3b9b7.jpg)

Server/Location
I am playing on Main server 1
at 7805 / -8343

Additional context
The ai issue is new, the axe issue has persisted since village creation

**Comment by TangoTek** [comment]
Fixed both. Thanks!
