### ISSUE TITLE
Suggestion: Merchant max trade increase with village size

### ISSUE THREAD

**Issue by SaltyJohnson94** [TangoTek/TekTopia-Community#685]
I think a nice addition would be raising the max trades depending on the size of your village. I have found that I have more then enough supplies now that my village has around 150 villagers. It would be cool to have the merchant trades increase to 7-10 when your village gets above 100 villagers. The merchant could even have like a "reputation" system where the more times you trade with him and the more variety you have the higher the max trade number goes (with a limit of course).

**Comment by TangoTek** [comment]
The merchant normally generates 8 trades.  10 with a merchant stall.
But to be honest, its late game where emeralds come in way too easy. I don't think I want to make it even easier.
