### ISSUE TITLE
extra folder in 1.0.60.jar

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#689]
There is an empty folder only containing sub folders but no files in the 1.0.60.jar file, the root empty folder is `/assets/villagerplus`
there is also the folder `/assets/textures` folder which only contains a copy of tango's skin over riding steve that is probably net necessary in the final jar

**Comment by TangoTek** [comment]
I removed the skin.  Not sure why there is a villagerplus folder.
