### ISSUE TITLE
BUG - Items receiving same enchant multiple times

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#691]
**Describe the bug**
Since updating to 1.0.60, I've noticed a lot of enchanted items have the same enchant at different levels. Selection of images below. I watched my enchanters and they are only enchanting the item once. Its effecting iron and diamond gear.

Points to note 
- I have multiple enchanters, I couldn't sim a scenario where only one of them enchanted at once, so that may be a factor.
- I have x3 enchanting tables all side by side (recent change is that only one table can be used at once)
- All my enchanters are high level, 89, 86, 81, 78 and 68.  
- Noted to effect Sharpness, Efficiency, Protection, Multiple Protection types.
- Perhaps this is just because my enchanters are high level, but there is always atleast one other enchant with the 'bugged' enchant - e.g, its never just "Efficiency I & Efficiency IV", there's a Silk Touch or Unbreaking or something else in there aswell

**Steps to Reproduce**
When I have time I intend to:
1. Start a new creative world.
2. Spawn an enchanter and use /village skill 100 to make it lvl 100.
3. Put an axe in the storage room chest
4. See what the enchanter does...

And then repeat with a lvl 1 enchanter, multiple enchanters, multiple enchanting tables and multiple enchanting tables on adjacent blocks.

**Expected behavior**
Only one level of each enchant per item, multiple protections not possible in 1.12.2

**Screenshots**
![Iron Chest 1](https://user-images.githubusercontent.com/52452881/61169160-acb52f00-a551-11e9-814d-bcf6658b1e9f.png)
![Diamond Axe 1](https://user-images.githubusercontent.com/52452881/61169161-ad4dc580-a551-11e9-8b21-9cee0b87a3d0.png)
![Diamond Chest 1](https://user-images.githubusercontent.com/52452881/61169162-ad4dc580-a551-11e9-825c-d2ee222b57b4.png)
![Diamond Pick 1](https://user-images.githubusercontent.com/52452881/61169163-ad4dc580-a551-11e9-8051-6295c7a3309d.png)
![Diamond Pick 2](https://user-images.githubusercontent.com/52452881/61169164-ad4dc580-a551-11e9-85fb-2d478009ff2b.png)
![Diamond Pick 3](https://user-images.githubusercontent.com/52452881/61169165-ade65c00-a551-11e9-9510-9bf3e78f60b7.png)
![Diamond Sword 1](https://user-images.githubusercontent.com/52452881/61169166-ade65c00-a551-11e9-9257-cd8242a30163.png)
![Diamond Sword 2](https://user-images.githubusercontent.com/52452881/61169167-ade65c00-a551-11e9-989f-c6bdeaf5e3ec.png)
![Iron Axe 1](https://user-images.githubusercontent.com/52452881/61169168-ade65c00-a551-11e9-8c71-32869d887672.png)
![Iron Axe 2](https://user-images.githubusercontent.com/52452881/61169169-ade65c00-a551-11e9-930e-47ca79db14c7.png)
![Iron Axe 3](https://user-images.githubusercontent.com/52452881/61169170-ae7ef280-a551-11e9-8fd9-fb258208a48e.png)
![Iron Axe 4](https://user-images.githubusercontent.com/52452881/61169171-ae7ef280-a551-11e9-9656-2d4ded3dbb31.png)

** Server/Location **
Single Player

**Additional context**
Version 1.0.60 - OptiFine installed.

**Comment by TangoTek** [comment]
Fixed in 1.0.61
