### ISSUE TITLE
Suggestion: Change the way villagers collect storage items

### ISSUE THREAD

**Issue by mrhyde1st** [TangoTek/TekTopia-Community#692]
Suggestion that villagers can be set if collecting some of the stackable storage items to have 2 options, collect maximum of X (0-64) or max %age of stocks (0-100%) [Sliders and text box in GUI?] so you can decide how much you want to leave available to the merchant and how much they take.  It could also reduce on the visits to the storage room if they run down until they have below 10% of their maximum they collect more or do it if they visiting storage room to drop off thereby increasing efficiency and ensuring that they can do a lot of their functions without trapsing back and forth on needless journeys to the storage.

**Comment by TangoTek** [comment]
Too huge of a change at this point, sorry.
