### ISSUE TITLE
Crash in Classroom

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#694]
**Describe the bug**
twice in a row crashed while in a classroom watching kids learn

**To Reproduce**
no idea

**Expected behavior**
not crashing

**Server/Location**
Offline Creative 1.0.60

**Additional context**
[crash-2019-07-13_23.11.20-server.txt](https://github.com/TangoTek/TekTopia-Community/files/3389275/crash-2019-07-13_23.11.20-server.txt)
[crash-2019-07-13_23.12.50-server.txt](https://github.com/TangoTek/TekTopia-Community/files/3389276/crash-2019-07-13_23.12.50-server.txt)

**Comment by JohnyDL** [comment]
okay I think I found the secret sauce for crashes Looking at a Child while the teacher was reading a book

[crash-2019-07-13_23.18.04-server.txt](https://github.com/TangoTek/TekTopia-Community/files/3389279/crash-2019-07-13_23.18.04-server.txt)

**Comment by TangoTek** [comment]
Already fixed in 1.0.61.  Thanks
