### ISSUE TITLE
Feature request: adding Emerald Block recipes

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#695]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
when you reach the opulence stage it would be nice if emerald slabs and stairs and anything else you can think of be added to the recipes so one can exhibit ones wealth lol

**Comment by TangoTek** [comment]
That's not really the intent of this mod, sorry.

**Comment by toasterhead-master** [comment]
You can have Emerald mod for this - https://emerald-mod.fandom.com/wiki/Emerald_Mod_Wiki
