### ISSUE TITLE
Multiple of the same Enchantment on a Tool

### ISSUE THREAD

**Issue by MilesKid** [TangoTek/TekTopia-Community#696]
**Describe the bug**
An enchanter has put mulitple of the same enchants on a tool.  (see screen shot)

**To Reproduce**
I don't know what the likely-hood is.  I just discovered it on a pickax (see screen shot)

**Expected behavior**
I expect to see a single instance of any enchantment on the tool.

**Screenshots**
![Multi enchant bug](https://user-images.githubusercontent.com/51030776/61177592-6d193200-a5a7-11e9-8932-2c2e46e29618.png)

** Server/Location **
Server II
3808 / 87 / -2174
Tool is in the lower chest on the right side of the Trading Hall which is behind the TH.

**Comment by LadyGwynn** [comment]
I came across this on server 1 as well. I found that multiple tools had both Eff I and Eff V on them.

![2019-07-12_21 19 55](https://user-images.githubusercontent.com/42978079/61177975-e1ec6c00-a5a7-11e9-8a44-0441baf88a5d.png)

**Comment by TangoTek** [comment]
Fixed in 1.0.61
