### ISSUE TITLE
Structure registers "floor" spaces on different Y levels as being part of the same structure when sharing a roof.

### ISSUE THREAD

**Issue by ARocketEngineer** [TangoTek/TekTopia-Community#697]
The structure token is registering every block under a common ceiling as being part of that structure despite the floor being at a different Y level than those blocks at the door. 
![2019-07-13_19 28 34](https://user-images.githubusercontent.com/51294493/61177601-a2be1b00-a5a7-11e9-9541-aa89e1e17d67.png)
The farms in the center are at a lower Y level than the rest of the structure. However, the line of diorite blocks covering the farms causes the structure token to stop registering the building when the 501st block (3 short of the full row of diorite blocks) is placed.
![2019-07-13_19 28 26](https://user-images.githubusercontent.com/51294493/61177604-b23d6400-a5a7-11e9-9970-51ed044e3ac9.png)

According to the Wiki and Videos, "the floor must all be at the same Y level" when in fact, the code is reading the ceiling, and counting blocks under it instead. If only those blocks at the same Y level were counted, the area over the farms should be able to be covered over and the storage room token would still register the structure as valid.

**Comment by ARocketEngineer** [comment]
![2019-07-13_19 57 26](https://user-images.githubusercontent.com/51294493/61177643-81116380-a5a8-11e9-83ac-164d84e4d7f7.png)
![2019-07-13_19 57 33](https://user-images.githubusercontent.com/51294493/61177644-81116380-a5a8-11e9-9564-eabd4a94d957.png)

Here is the same structure with only 500 blocks of ceiling and the structure token lit.

**Comment by TangoTek** [comment]
Good catch.  Fixed in 1.0.61.  Thanks!

**Comment by JohnyDL** [comment]
this is exactly the same bug as #48 I'm glad it's fixed now
