### ISSUE TITLE
Curing Zombie Villagers

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#7]
**Describe the bug**
Curing Zombie Villagers gives vanilla villagers

**To Reproduce**
Spawn in zombie villagers
hit with weakness potion
give golden apple
wait

**Expected behavior**
not sure but I doubt it's meant to be a vanilla villager

** Server/Location **
tested on Dev (Creative) server

**Comment by TangoTek** [comment]
Intended.

**Comment by Plagiatus** [comment]
Suggestion: spawn a nitwit with a very low intelligence instead?
