### ISSUE TITLE
Balancing: Children gain levels to max of the level of the villager that leveled up

### ISSUE THREAD

**Issue by Inditorias** [TangoTek/TekTopia-Community#717]
Currently children have no cap to leveling, and can level to 100 from witnessing 100 level 1 villagers level up to level 2.  

The fix I am proposing is to allow the children to level only if their current level is lower than that of the villager that just leveled up, for example if a child has a level 20 farming skill and is near a farmer that just leveled up to level 16, the child will not level up.

**Comment by Snodderz** [comment]
As long as we are definately talking about the child's skill here and not the child's intelligence, I like this idea.

**Comment by TangoTek** [comment]
I like the idea and I'm implementing a check to make sure the child doesn't learn too much.

The real question here however, is how did you get a child with 20 farming skill?  Are kids learning that much from proximity?

**Comment by Snodderz** [comment]
If your school is in the middle of all your farmland, shouldn't be too difficult. My school is attached to my library and all my children grow up with decent enchanter skill.

Maybe if the child is in school, they shouldn't be able to learn by proximity? (There attention should be focused on the teacher, not what's going on out the window.... ;)

**Comment by TangoTek** [comment]
I like it. Done. Children will no longer proximity learn while in school now.
