### ISSUE TITLE
Suggestion: No more Hearts

### ISSUE THREAD

**Issue by CaptMacDuff** [TangoTek/TekTopia-Community#719]
I just don't think a city manager should tell people when they can have kids. it should be set back the normal way, where the kids just pop ready or not. maybe scale it way back like 1/10th as much as the hearts are popping now.

**Comment by toasterhead-master** [comment]
Maybe it's more fun playing with hearts? It's just a game bro, not everything should be realistic.

**Comment by Snodderz** [comment]
I like the hearts system, I enjoy stockpiling them. The teachers need minimum 3 kids in school before they use books to teach, so this would nullify that mechanic aswell. 

I would prefer for a villager to deliver hearts to storage, as in #674

**Comment by ghost** [comment]
With the hearts system you can play at your own pace. Is better if the player decide when to make kids/grow the population, otherway the player will have to build houses and buy jobs tokens almost every day.
However, i think that hearts should be more rare and spawn less.

**Comment by JohnyDL** [comment]
If you want to play with kids popping into existence whenever you could just place them on beds as soon as they spawn

**Comment by TangoTek** [comment]
Not planning on changing anything with hears at this point.
