### ISSUE TITLE
Children not growing up

### ISSUE THREAD

**Issue by HexFlareheart** [TangoTek/TekTopia-Community#72]
**Describe the bug**
I dropped a heart on a bed I estimate a minimum of an in-game week ago (I haven't exactly been keeping track, but it's been multiple days since I noticed it was taking a while), and haven't had the resulting child grow up yet. (At the very least, I've had the game open and running fairly consistently for several hours.)

**To Reproduce**
1. Get a heart.
2. Right-click on a bed.
3. Wait.

**Expected behavior**
From most estimates, the child should be growing in roughly 5-7 days. Numbers found in NBT data are consistent with these estimates.

**Server/Location**
Testing of this has been done in singleplayer, due to the known tps issues the servers have had. (And also because I've been testing mod compatibility. It's been doing surprisingly well so far!)

**Additional context**
The world (and game on a whole) has been loaded multiple times, mostly to fix spontaneous pathing failures.

**Comment by HexFlareheart** [comment]
Update regarding this issue- the child, after an extended period of not reloading the world (I started using zombies to get my villagers unstuck), has finally grown up, leading me to further believe this is most likely a persistence issue.

**Comment by Nevla1** [comment]
Same here, I also was able to give them profession token.

**Comment by TangoTek** [comment]
Fixed
