### ISSUE TITLE
Something wrong in the library

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#722]
**Describe the bug**
I have 34 villagers I should expect about 11 of them to go to the library in any given day right? It's a little after noon and I've seen 14 in there at one time and at least 17 villagers come to use the library in total and this isn't an unusually high use day, it seems to happen more often than not

**To Reproduce**
lots of villagers a big library and some name tags
watch the village count the number of villagers that come through by tagging them
work out the percentage

**Expected behavior**
closer to 1/3 of villagers use the library each day

**Server/Location**
Offline Creative 1.0.62

**Screenshots**
![2019-07-19_12 52 54](https://user-images.githubusercontent.com/5202568/61533937-2489ca80-aa26-11e9-8b85-b2b973a1e7ec.png)

**Additional context**
I think there's a 1/3 chance every time villagers check to go to the library and they do this check a few times per day

I could turn off the library all together or micro-manage the hell out of my village but then I lose out on increasing their intelligence since the game doesn't balance me turning off one villager by forcing another to go.

I'd like to see maybe the chance of going to the library based on their intelligence:
Perhaps villagers visit the library every 10/(intelligence + 10) days
And the lowest intelligence villager(s) visit every day to make the numbers up to 1/3 of the village visiting the library every day

Maybe also have a set number of reading tasks for the villagers like the guards have a set number of swings in the barracks every day

**Comment by TangoTek** [comment]
Yes, every villager has a 1/3 chance to visit the library every day
Teachers try to visit the library every day
Enchanters visit the library to do their jobs of course.

I took a look at the 'wantsLearning' code and didn't see anything abnormal. Getting 14 of 34 in the library at once time is perfectly reasonable.  You'd have to track many days together for this to be statistically sound.  I'll definitely keep my eye on this, but like I said I couldn't find anything now.

There already is a set number of book reads for each villager as you suggested. Its between 3-9

**Comment by JohnyDL** [comment]
like I said this seems to be the norm for me. I've not visited the library during library time in the past few updates and had less than 6 villagers in there and not every villager that needs to learn visits at exactly the same time the one time I catch most of them in there at once 

At the time of the screenshot I had
34 villagers 
-6 guards, that don't come at that time of day
-1 teacher, I turned off while I had children because she would constantly visit the library during teaching times
-1 enchanter that doesn't have a choice
=26 villagers that could have chosen to been in the library

14 were in the screenshot and at least 3 others had been to the library (walked out while getting the screenshot) or had come later after I'd taken the screenshot, at best that's 60% of my villagers visited my library at that time

It might be that it just feels like a little too much productivity is wasted in the library to me but I don't want to turn it off (or worse micromanage) every or even most villagers abilities to visit the library. 

*shrug* I guess it won't matter soon enough as my newest cohort of children are growing up
![2019-07-23_06 12 09](https://user-images.githubusercontent.com/5202568/61684303-e683f380-ad10-11e9-8ddd-f619967fe444.png)
