### ISSUE TITLE
Teacher Game Crash

### ISSUE THREAD

**Issue by IridescentShadow** [TangoTek/TekTopia-Community#724]
**Describe the bug**
The game crashes when the teacher teaches school

**To Reproduce**
1. Have a school, teacher and children
2. Wait for game crash

**Expected behavior**
Teaching should not cause a game crash

**Stack Trace**
19.07 17:33:11 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
19.07 17:33:11 [Server] INFO net.minecraft.util.ReportedException: Ticking entity
19.07 17:33:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
19.07 17:33:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
19.07 17:33:11 [Server] INFO Caused by: java.lang.IllegalArgumentException: bound must be positive
19.07 17:33:11 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_211]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.teachAll(EntityAISchoolTeach.java:126) ~[EntityAISchoolTeach.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.entities.ai.EntityAISchoolTeach.lambda$updateTask$2(EntityAISchoolTeach.java:110) ~[EntityAISchoolTeach.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.tickjob.TickJob.tick(TickJob.java:31) ~[TickJob.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.tickjob.TickJobQueue.tick(TickJobQueue.java:30) ~[TickJobQueue.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.entities.EntityVillageNavigator.func_70636_d(EntityVillageNavigator.java:314) ~[EntityVillageNavigator.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.tangotek.tektopia.entities.EntityVillagerTek.func_70636_d(EntityVillagerTek.java:699) ~[EntityVillagerTek.class:1.0.60]
19.07 17:33:11 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
19.07 17:33:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]

** Server/Location **
What server were you playing on? SP, but can share world files if needed

**Comment by Snodderz** [comment]
Please confirm which version you're on? There's a 1.0.60 in there...

**Comment by IridescentShadow** [comment]
It is 1.0.60, yes

**Comment by Snodderz** [comment]
Try updating to the latest version, 1.0.68. The issue may have already been fixed.

**Comment by TangoTek** [comment]
This was fixed. Please make sure you are playing on the current jar even in single player. Its extremely important.
