### ISSUE TITLE
Druids delete ores when doing earth regrow

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#726]
**Describe the bug**
Some ores that the druid regrows can't be seen by the miner are deleted in ore regrow
![2019-07-20_01 05 55](https://user-images.githubusercontent.com/5202568/61571331-9a278200-aa8a-11e9-8e2b-a6672e3e9122.png)
The druid can replenish the whole area but if the glass blocks aren't ores then any ore that's in the corners can't be seen.
The druid can come along and delete them.

**To Reproduce**
To best see it you need to watch ore regrow in x-ray

**Expected behavior**
I'd have thought that the hidden ores would be left untouched and over several replenishes those ores would eventually get mined by lucky ore next to them where the miner can see

**Screenshots**
Notice the Redstone ore here
![2019-07-20_01 02 18](https://user-images.githubusercontent.com/5202568/61571396-35205c00-aa8b-11e9-9318-9c86001e8bc9.png)
![2019-07-20_01 02 23](https://user-images.githubusercontent.com/5202568/61571397-35205c00-aa8b-11e9-9239-1d0c9fe9391f.png)
Notice the Coal ore here
![2019-07-20_01 01 37](https://user-images.githubusercontent.com/5202568/61571489-b7a91b80-aa8b-11e9-84c0-c023eec997bc.png)
![2019-07-20_01 01 40](https://user-images.githubusercontent.com/5202568/61571490-b7a91b80-aa8b-11e9-8bdb-7906b4b56b3d.png)

** Server/Location **
Offline Creative 1.0.69

**Additional context**
I've not yet observed this with diamond but I've seen Iron, Gold and Lapis deleted like this too

**Comment by Snodderz** [comment]
Confirmed in version 1.0.71 by using a mine above ground. Images below, they also tie in with bug #728. The circled block is at floor level.

![Miner 3](https://user-images.githubusercontent.com/52452881/61577926-46e31d00-aae6-11e9-8095-f2a886207c88.png)
![Miner 4](https://user-images.githubusercontent.com/52452881/61577927-46e31d00-aae6-11e9-8878-e40b5d804bbd.png)

The druid should check the 4 corner blocks aren't an ore before replacing it. Whilst the miner still won't be able to see the 4 corners, eventually, either a side or top will also be an ore and the miner will then see the corner.

**Comment by TangoTek** [comment]
Good report. Thanks!  Fixed in next patch.
