### ISSUE TITLE
day and night

### ISSUE THREAD

**Issue by Roxanne59** [TangoTek/TekTopia-Community#727]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by Roxanne59** [comment]
t's a day and night cycle on the server the same as vanilla because when I play in single-player it's longer

**Comment by TangoTek** [comment]
Nothing about day and night has changed
