### ISSUE TITLE
BUG - Druids refill area is one block too low

### ISSUE THREAD

**Issue by Snodderz** [TangoTek/TekTopia-Community#728]
**Describe the bug**
Druids refill a 3x4 square with the shaft centered. Since either 1.0.68 or 1.0.71 (unsure when it occurred) the druid's are not centering the mine shaft - the refill box is now lower, one block too low. Images below should explain. The cobby shaft was created by a miner, the stone and ore is what the druid has just refilled. You can see the top hasn't been refilled and one block lower has been refilled. Tested with a lvl 1 and a lvl 100 druid - both have the same result.

**To Reproduce**
1. Create an above ground, floating, mine shaft.
2. Set the druid loose on it.
3. Check bounding box of the refill area

**Expected behavior**
Druids refill bounding box should be one block higher.

**Screenshots**
![image](https://user-images.githubusercontent.com/52452881/61577832-9e808900-aae4-11e9-87c1-4f9c88e51532.png)

** Server/Location **
Single Player, Survival and Creative

**Additional context**
Found in version 1.0.71, unsure when it originated, either 1.0.71 or 1.0.68

**Comment by Snodderz** [comment]
Broken in 1.0.72 also

**Comment by TangoTek** [comment]
Excellent find! Fixed in next patch. Thank you!
