### ISSUE TITLE
Single Villagers can produce hearts

### ISSUE THREAD

**Issue by Jamcdonald120** [TangoTek/TekTopia-Community#738]
Villages with only a single villager (well, 3 if you count to base 2) will still make hearts from time to time

**Comment by TangoTek** [comment]
This is intended.  Is there a problem I'm not thinking of?

**Comment by Jamcdonald120** [comment]
not a problem as such, its just strange that 1 villager can have kids

**Comment by mrhyde1st** [comment]
Indeed as the saying goes It Takes Two To Tango 😈
