### ISSUE TITLE
Villager death message does not include profession

### ISSUE THREAD

**Issue by jade-lynx** [TangoTek/TekTopia-Community#74]
I'm told that the villager damage or death message in chat is supposed to indicate the profession, to help ID the villager. I had a villager die, where the death message was:

"Mia Valur has been killed by mob damage."

No profession listed, so I was uncertain which villager that was...

Survival 1, somewhere near my village "Tikkitavi's Hamlet",  x:7368, z:-5913

**Comment by TangoTek** [comment]
I've added the profession and the location in the chat message now.  Good idea!
