### ISSUE TITLE
Villager Happiness

### ISSUE THREAD

**Issue by Asher90** [TangoTek/TekTopia-Community#741]
**Describe the bug**
Villager Happiness (without Bard or Tavern) : Should reduce overtime and it does but at a extremely slow rate, most of the villagers I have at my village (Coordinates -5485, 7709) have high happiness without me actually having a bard or tavern I think this is a bug or something

look at villager happiness bar

** Server/Location **
Tektopia Server

**Comment by TangoTek** [comment]
I've put in reporting tools to let me know how villagers are doing with happiness, hunger, and average level gains.  More balancing will be coming
