### ISSUE TITLE
Insomnia debuff lasting a while

### ISSUE THREAD

**Issue by Magleose** [TangoTek/TekTopia-Community#742]
**Describe the bug**
I am not sure the of the duration of this debuff, but my farmer has had it for 2 nights in a row and I am starting to get worried he is just never going to sleep again. 

**To Reproduce**
1. Experience Zombie attack
2. Watch Villager go about his day until sunset
3. Watch as villager stands there with the emote for insomnia for more than one night

**Expected behavior**
I am not sure what to expect out of this debuff as I do not know how long it is supposed to last, I just worried it was lasting longer than intended

**Screenshots**
after the 2nd night of standing in the field
![2019-07-21_00 07 15](https://user-images.githubusercontent.com/37353615/61596209-a1f03f00-abce-11e9-83e9-5d1aa0e8e1c2.png)

** Server/Location **
Server: TekTopia Survival server
Town Hall Marker: -6586 / 74 / 1286
City Name: Ciudad Del Perro

**Comment by TangoTek** [comment]
Was that villager hurt by any chance?

**Comment by TangoTek** [comment]
If this villager was less than 50% health then it was a bug that I just fixed.
