### ISSUE TITLE
Perma-Insomnia

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/TekTopia-Community#744]
My villagers _never_ sleep. From my understanding the insomnia thing is villagers getting scared and then not sleeping for that night right? I had 1 night where the tradesman and architect were getting scared out of the town hall since it didnt have walls (which in itself may need a bug report because that caused multiple tradesmen/architects to be spawned at once but it was kinda funny), and since then all of my villagers have the insomnia eye above their head every night despite the whole are being lit up very well now with no zombies near by. Even new villagers who have never seen a zombie have insomnia. A few times it has caused the villagers to stand around outside and not go to their bedrooms (often standing at storage). All of this seems to be badly impacting their happiness too which is making it real hard to get the village moving.
Tried everything to fix it, unloading reloading chunks, removing and replacing tokens, _killing the tradesman and architect_, even a restart didnt fix it sadly.

**Comment by TheGreatNaj** [comment]
![2019-07-22_09 42 00](https://user-images.githubusercontent.com/25763105/61637132-fcd47580-ac64-11e9-9627-449be87c8b95.png)
Still happening as of 1.0.73

**Comment by anatharax** [comment]
i am having the same problem

**Comment by TheGreatNaj** [comment]
Roxann59 is having the same problem but 2 of her villagers were hurt. Since they cant go to bed they never heal and just stand in the same spot for days. Manually healing them with splash potions got them moving again but still not sleeping.

**Comment by TangoTek** [comment]
Fixed. Give your villagers some headroom! ;-)
