### ISSUE TITLE
Barracks OP

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#748]
**Describe the bug**
Barracks levels up guards far too fast

**To Reproduce**
watch guards in Barracks

**Expected behavior**
maybe limit guard levelling in barracks to intelligence level

**Screenshots**
![2019-07-22_20 23 16](https://user-images.githubusercontent.com/5202568/61659382-3fc33700-acbf-11e9-8c97-0592e7ca36c0.png)
![2019-07-22_20 23 19](https://user-images.githubusercontent.com/5202568/61659383-3fc33700-acbf-11e9-9ff3-c96e52f1799e.png)
![2019-07-22_20 23 29](https://user-images.githubusercontent.com/5202568/61659384-3fc33700-acbf-11e9-9e85-c388e42f0b20.png)
![2019-07-22_20 23 47](https://user-images.githubusercontent.com/5202568/61659385-3fc33700-acbf-11e9-8f32-43ea656172e2.png)
![2019-07-22_20 24 46](https://user-images.githubusercontent.com/5202568/61659386-3fc33700-acbf-11e9-8077-07e9705836fd.png)
![2019-07-22_20 25 28](https://user-images.githubusercontent.com/5202568/61659387-405bcd80-acbf-11e9-80ee-f07049e11ec4.png)

** Server/Location **
Offline Creative 1.0.73

**Additional context**
Guards should be able to level up above their intelligence through real experience but not through training
FYI when I promoted him my captain had the highest level at 69 and Rosmorne Sell the lowest as a fresh Guard about level 35-40

**Comment by TangoTek** [comment]
Good feedback. Good suggestion. Thanks
