### ISSUE TITLE
Feedback: Leveling

### ISSUE THREAD

**Issue by blondetheftauto** [TangoTek/TekTopia-Community#756]
I think the leveling may be a bit too quick?

I have a single farmer. When I first got him, he had no levels in farming, but had 28 intelligence. He leveled up to level 25 farmer very very quickly (within 2-4 irl hours). He's now level 38, after about more 6 hours.

I don't know if this is as intended, but the first set of leveling seemed to go by really, really quickly. The second feels fast too, but I don't really know.

TekTopia Server, blondeburg

**Comment by TangoTek** [comment]
I did just recently lower the overall level up rate of everyone a tad. But overall, if a villagers intelligence is much higher than their skill I do intend for them to level up quite quickly.  Once skill > intelligence it should slow down quite a bit.  Perhaps that falloff isn't fast enough right now. 
Keep me posted as you go. This is really helpful!
