### ISSUE TITLE
Ex-Guards sleep in barracks

### ISSUE THREAD

**Issue by binksayres** [TangoTek/TekTopia-Community#762]
**Describe the bug**
Accidentally used a guard token on a cook.  They immediately started acting like a guard (good).  Got another chef token and turned them back.  The villager was probably a guard for at most 2 minutes.  Long enough for a barracks bed to go green.  Started acting like a chef again (again, good).  However, at night, this once guard still sleeps in the barracks, even after a reset.

**To Reproduce**
0. Must have Barracks.
1. Pick a villager that's not already a guard
2. Change them to a Guard
3. Change them back to any other profession.
4. Wait until night.  They will sleep at the Barracks instead of any other house.

** Server/Location **
Single Player.  Running 1.0.73

**Comment by binksayres** [comment]
I see there is a new version out there.  I'll check if it persists with v75

**Comment by TangoTek** [comment]
Fixed in 1.0.77
