### ISSUE TITLE
Animal pens work inside butcher.

### ISSUE THREAD

**Issue by Shamshalabim** [TangoTek/TekTopia-Community#766]
**Describe the bug**
After a little testing, someone on the TekTopia server discovered that you can install your animal pens INSIDE your butcher structure. Obviously this makes for a very high level of butcher efficiency and effects the rancher too! This isn't really a bug, but Makani suggested I post it as a balancing issue.

**To Reproduce**
1. Create a large butcher structure.
2. Install one or more animal pens INSIDE your butcher structure.
3. Profit!

**Expected behavior**
I'm unclear if this is supposed to be possible. If so, I'm certainly going to start using this tactic as part of a min-maxer crew. (Tango - 2019) ;-)

**Screenshots**
As I didn't perform the test, I don't have any screenshots, but are they really needed??

** Server/Location **
TekTopia Server
N/A

**Additional context**
Is it a problem???? ;-)

**Comment by TraxKB** [comment]
I am the one who performed the test, so here are the additional details.

**Steps to reproduce**
1.  Go to a generated village and locate a butcher
2.  Partition half of the room off with a fence and gate
3. Place tokens for butcher and chicken pen, with the chicken pen gate and token inside the butcher building
4. Use spawn egg with "/villager item" command applied to spawn more chickens than allowed for the pen size
5. Have a butcher and a rancher

**Server/Location**
Test performed in Single Player Creative

**Version**
1.0.75 and 1.0.76

**Screenshots**
View of both tokens active at the same time
![2019-07-25_22 03 56](https://user-images.githubusercontent.com/52908012/61873086-620bbd80-af28-11e9-9db5-710481292e87.png)

Rancher feeding chickens:
![2019-07-25_22 04 45](https://user-images.githubusercontent.com/52908012/61873097-6a63f880-af28-11e9-8d4a-847320ea05c3.png)

Butcher leashing excess chicken:
![2019-07-25_22 04 59](https://user-images.githubusercontent.com/52908012/61873107-6f28ac80-af28-11e9-8e5d-2bf28fe33e4e.png)

Butcher killing chicken:
![2019-07-25_22 04 15](https://user-images.githubusercontent.com/52908012/61873108-72239d00-af28-11e9-9dd7-926464c6bd8e.png)

**Comment by JohnyDL** [comment]
Yeah the pen isn't actually "inside" the butcher there. Even though form a builder's perspective they share a roof
The butcher and the pen in effect share a wall or rather a fence and are two separate structures.
You can see this in how the Butcher brings the chicken out of the pen to kill it rather than killing the chickens inside their pen.

This is no different than having a bedroom token on a doorway inside another bedroom or a kitchen token on a doorway inside a tavern (both of which Tango has shown in his series)

The structures are separate they simply share boundaries.

**Comment by TangoTek** [comment]
I agree with Johny.  This is just  how structures work. The butcher is still moving the animal from the pen to the butcher structure. They just happen to be very close.
