### ISSUE TITLE
Miners dropping ore blocks

### ISSUE THREAD

**Issue by DocNox1408** [TangoTek/TekTopia-Community#774]
Miners are dropping ore blocks while mining and they dont have a silk touch pick or even an enchanter to create one. This is happening on the dev server cords are 1005/9/2358. not sure how this is even happening.
![2019-07-24_18 43 32](https://user-images.githubusercontent.com/51489959/61839674-54c8d300-ae43-11e9-9cd1-f43b3df9caf6.png)
![2019-07-24_18 43 32_2](https://user-images.githubusercontent.com/51489959/61839675-54c8d300-ae43-11e9-9ad0-eee21be4f25f.png)

**Comment by SaltyJohnson94** [comment]
Also happening to  me
![2019-07-24_19 27 58](https://user-images.githubusercontent.com/52110462/61841373-62815700-ae49-11e9-9030-71fd2d326f10.png)

Survival server -13342, 5183

**Comment by TangoTek** [comment]
Fixed now
