### ISSUE TITLE
Enchanter turning villager item to non villager item

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#777]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
My enchanter is turning villager diamond boots into non-villager enchanted diamomnd boots. Swords and pickaxes are not being converted. See pics. It happpened a second time so not a fluke.

**Comment by MetriCfan** [comment]
![image](https://user-images.githubusercontent.com/51779504/61847501-3e2b8600-aeee-11e9-8733-d145d9e72fca.png)
![image](https://user-images.githubusercontent.com/51779504/61847508-48e61b00-aeee-11e9-86c7-23145efb726e.png)

**Comment by TangoTek** [comment]
Was your lapis villager items? Was it gathered by miners?  My guess is it wasn't. That would cause the enchanted item to become non-villager

**Comment by MetriCfan** [comment]
the enchanter did have lapis I had given them, didn't know they used it for enchanting tools, I see now the lapis has decreased by one, sorry!
