### ISSUE TITLE
Jumping on a crop makes soil untilled but leaves the crop

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#778]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
just as described, the crop is still harvestable
![image](https://user-images.githubusercontent.com/51779504/61847965-d5dda400-aeef-11e9-82b2-51a076c8272f.png)

**Comment by TangoTek** [comment]
I just tested this and the crops popped off just fine.  Was there a farmer nearby? Can you reproduce it?

**Comment by MetriCfan** [comment]
ok looks like it was a temporary glitch, did it all day yesterday but acting properly now
