### ISSUE TITLE
children learning at night

### ISSUE THREAD

**Issue by gotnate** [TangoTek/TekTopia-Community#78]
the class of children stayed put in the classroom right into the night

![image](https://user-images.githubusercontent.com/69241/58397482-07c4ae00-8006-11e9-8d31-7246c8596ed2.png)

**Comment by TangoTek** [comment]
Was there a teacher in the school still?

**Comment by gotnate** [comment]
I believe the teacher went to bed. He certainly came back to the classroom at proper teaching time, with the kids sitting there the whole time.

**Comment by TangoTek** [comment]
Hmm. Looks like the teacher actually would never stop teaching. I'm guessing the teacher was still in the building.  The children stay as long as the teacher stays.  I fixed the teacher.   Great bug. Thanks.
