### ISSUE TITLE
Enchanting disrupted by villagers reading

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
Not sure how this happened but I did notice a lot of villagers hanging around inside the enchanting table bookshelves, I think the enchanter got moved about and lost this pair of pants. The enchanter left just before pic was taken.
![image](https://user-images.githubusercontent.com/51779504/61872646-3dfbac80-af27-11e9-8d7b-70eba65d5ff4.png)

**Comment by Snodderz** [comment]
I've had this before, I had x4 enchanting tables with items floating above them, no enchanters in sight. Some tables even had multiple items. However, it only occurred when I first logged in after a new JAR. The following day, when the enchanters got back to work, everything returned to normal ops. I assumed it was related to the JAR update.

**Comment by MetriCfan** [comment]
It's also better to spread out your bookshelves with the new one bookshelf per reader rule. I am now keeping my personal enchanting table and associated bookshelves out of the library. Not an issue now.
