### ISSUE TITLE
Rancher getting milk without stopping

### ISSUE THREAD

**Issue by TimoDonnermeyer** [TangoTek/TekTopia-Community#782]
In my village i now have more than a chest full of milk. And the Ranchers demand for more buckets and more milk without an end in sight. I do not know if it is intended, but I think there should be a limit after which the ranchers stop collecting milk.

**Comment by TangoTek** [comment]
Fixed in next patch. The rancher should no longer want to harvest milk if there are 4 or more milk buckets in storage.
