### ISSUE TITLE
Merchant Trades Stuck

### ISSUE THREAD

**Issue by PfluorescentZebra** [TangoTek/TekTopia-Community#783]
**Describe the bug**
After server updated to 1.0.76 the merchant trades stopped changing and decreased from 10 per day to 4.  Trades have been constant for 4+ in-game days (basemates report trades did not change at all for them either but they were not counting days).

**To Reproduce**
1. Go to Lite Town 
2. Click on Merchant
3. Trades will be golden carrot, beetroot, spruce, and birch.

**Expected behavior**
Merchant trades should randomize daily and have up to 10 trades.

**Screenshots**
![2019-07-25_14 01 59](https://user-images.githubusercontent.com/43716457/61901521-9611bf00-aee5-11e9-9b73-8b54b1852583.png)
![2019-07-25_14 02 00](https://user-images.githubusercontent.com/43716457/61901524-97db8280-aee5-11e9-9272-919b3879d884.png)
![2019-07-25_14 02 00_2](https://user-images.githubusercontent.com/43716457/61901527-99a54600-aee5-11e9-9496-553e7e7e263d.png)
![2019-07-25_14 02 01](https://user-images.githubusercontent.com/43716457/61901533-9ad67300-aee5-11e9-9345-dd434667ec3b.png)

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Main server
What are the world coordinates of your town hall marker? 3477 65 6245

**Comment by SaltyJohnson94** [comment]
I am having the same issue as well on the survival server. Even if I max out one of the trades he comes back with the same ones the next day.

**Comment by TangoTek** [comment]
Fixed in next build.  But, I should note....You are encouraged to trade the items offered.  If you do, you'll get your other items back eventually.  

I lessened this effect for lower cost items though.
