### ISSUE TITLE
Town Hall Shaking in Hand

### ISSUE THREAD

**Issue by PfluorescentZebra** [TangoTek/TekTopia-Community#784]
**Describe the bug**
When the Town Hall is held in your hand it shakes continuously.

**To Reproduce**
1. Hold Town Hall in Hand
2. Town Hall shakes

**Expected behavior**
Town Hall token should be steady when held.

**Screenshots**

![shakyTownHall](https://user-images.githubusercontent.com/43716457/61902075-dde51600-aee6-11e9-9dbb-b5082315f09f.gif)

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? Main Survival, LiteTown
What are the world coordinates of your town hall marker? 3477 65 6245

**Additional context**
Seems similar to how items behave when picking up XP while mending.

**Comment by TangoTek** [comment]
This is only happens with sponge. Spent 90 minutes looking into it. I no longer care.
