### ISSUE TITLE
Nomads won't become villagers

### ISSUE THREAD

**Issue by Dogez** [TangoTek/TekTopia-Community#785]
When I right click a nomad with a villager token, it opens up their skills, health, hunger, etc. I've tried every villager token I have, even the ones I bought, but nothing happens. I've tried everything.

**Comment by TangoTek** [comment]
You are trying to use a token from a different village than the one the nomad spawned for.  Either the nomad isn't from your village or your acquired the profession token from another village's tradesman.
Did you get the token from a different start chest perhaps?
