### ISSUE TITLE
Missing Merchant

### ISSUE THREAD

**Issue by Shiirmp** [TangoTek/TekTopia-Community#787]
The merchant wasn’t spawning for about 5 mc days and i got no messages telling me he couldn’t get to my town hall. Today he came and a mod told me to put this up so i did.

**Comment by TangoTek** [comment]
I just went to your village and the merchant showed up on the first day. You do have an extremely long path for him to follow to get to your village since you are underground.  He didn't arrive until the day was half over.  Maybe you had your access to the surface closed off for a few days?
