### ISSUE TITLE
Crafting Town Hall Token Bugged

### ISSUE THREAD

**Issue by AlethaPrime** [TangoTek/TekTopia-Community#789]
The token I received from the Startup Kit did not work, so I crafted one. While in the crafting table, it showed the typical "visual glitch" of the pink/black box, both in the recipe book and crafting table. When I pulled it from the crafting table, it was still glitched.

Out of curiosity, I put it in the town hall item frame and it didn't seem to work, but I'm not 100% sure. Makani came over and gave me a new one and I destroyed the broken one. I put together the materials again and when I went into the crafting table, it did the same thing.

**To Reproduce**
1. Go into crafting table UI
2. Select Town Hall from recipe book
3. Error will be visible, even after taking Town Hall Token from crafting table.

**Screenshots**

** Server/Location **
Survival TT Server

What are the world coordinates of your town hall marker? -9967 73 -1975

![2019-07-25_19 25 30](https://user-images.githubusercontent.com/53322611/61919876-c6bd1d00-af14-11e9-81aa-200e94a66dd4.png)
![2019-07-25_19 25 52](https://user-images.githubusercontent.com/53322611/61919888-ccb2fe00-af14-11e9-90f9-5cc4d3942cce.png)
![2019-07-25_19 29 37](https://user-images.githubusercontent.com/53322611/61919895-d0df1b80-af14-11e9-9541-7375d9216698.png)
![2019-07-25_19 37 45](https://user-images.githubusercontent.com/53322611/61919899-d3da0c00-af14-11e9-8dbf-9e5a85f17e02.png)

**Comment by MilesKid** [comment]
I have experienced the same in SP.

**Comment by TangoTek** [comment]
Fixed
