### ISSUE TITLE
blacksmith functioning properly without a crafting table

### ISSUE THREAD

**Issue by treehugger667** [TangoTek/TekTopia-Community#798]
**Describe the bug**
The wiki says the blacksmith needs a crafting table. Blacksmith room forms and blacksmith has created each tool and piece of armor without a crafting table in the building. There are crafting tables a bit outside the blacksmith room in the storage room but I have not seen him use these crafting tables.

**To Reproduce**
1. Make blacksmith room with at least one anvil and furnace.
2. watch balcksmith make all the iron items. (have not tested with all diamond)

**Expected behavior**
Expect the crafting table to be needed because it is listed in the wiki.

![2019-07-26_19 56 55](https://user-images.githubusercontent.com/53134230/61987940-af4b6600-afe0-11e9-80f5-7eb8d2bcebac.png)

** Server/Location **
What server were you playing on? 1.0.76 Tektopia mod server
What are the world coordinates of your town hall marker? 'LeafyTown' -860 3600

**Comment by JohnyDL** [comment]
They only need the crafting table to make torches for the miners they use the anvil to craft armour and tools
