### ISSUE TITLE
Attacked while sitting

### ISSUE THREAD

**Issue by JenesisDark** [TangoTek/TekTopia-Community#800]
**Describe the bug**
When sitting, if the villagers get attacked, they will continue to sit and ignore the attack.

**To Reproduce**

Have a sitting villager, introduce annoying baby zombie

** Server/Location **
**What server were you playing on?** 
1.0.76 Tektopia dev server
**What are the world coordinates of your town hall marker?** 
518, 74, 813

**Comment by Snodderz** [comment]
This also happens for me - it also prevents the villager from getting the insomnia debuff. I don't think the damage effects their happiness either.

**Comment by TangoTek** [comment]
I'm assuming this was inside the home. Villagers don't flee an enemy if they are inside their home and the home still has a door.  However, I forgot to check to see if the enemy was ALSO inside the house. So I added that check now.
