### ISSUE TITLE
Bug: Miner keeps making charcoal

### ISSUE THREAD

**Issue by Hedkracka** [TangoTek/TekTopia-Community#81]
**Describe the bug**
Miner has almost 3 stacks of charcoal on him but is waiting at furnace making more

**To Reproduce**

**Expected behavior**
I would expect him to at most have 8 charcoal to make torches

**Screenshots**
![2019-05-27_10 21 45](https://user-images.githubusercontent.com/20891568/58410427-18a70b00-806a-11e9-8b66-2c97102f01af.png)

** Server/Location **
Tektopia 1

**Additional context**

**Comment by TangoTek** [comment]
The issue was actually related to the Miner and blacksmith working in tandem to create an infinite charcoal supply. fixed.

**Comment by bhdavies** [comment]
This is not resolved for the blacksmith, he is still increasing in charcoal even though he now has 5 stacks. The miners have stopped.

**Comment by JohnyDL** [comment]
Might be fixed but not released yet since it wasn't included in the patch notes for 1.0.16 or 1.0.17
