### ISSUE TITLE
Update to TekTopia Startup Guide (Renaming Town Hall Marker Issue)

### ISSUE THREAD

**Issue by mrhyde1st** [TangoTek/TekTopia-Community#810]
As TheGreatNaj posted in the WhatIf Announcements (https://ptb.discordapp.com/channels/184801826103754752/581282206425808896/602288010595139604) there is an issue if you rename your TownHall marker before placing it...

The warning not to rename the marker before it is first placed should be added to the Renaimg Town Hall Marker and Village Creation section of the Startup Guide

**Comment by TangoTek** [comment]
That was 7 days ago and I'm pretty sure this was fixed.  Are you sure you are playing on the current version?
