### ISSUE TITLE
butcher getting villger item from non village animal

### ISSUE THREAD

**Issue by treehugger667** [TangoTek/TekTopia-Community#815]
**Describe the bug**
Butcher slaughters non village animal from animal pen and gets villager products.

**To Reproduce**
1. Have non villager animal in animal pen (any type of pen will do)
2. Watch butcher take non villager animal first (this priority is working)
3. butcher kills non villager animal
4. Drops in butcher UI are villager items.

**Expected behavior**
I expected animal products from non villager animals to be non villager items as discussed in the mod walk through. I only have one villager cow at this time and I watched the butcher take a different cow to get his bits.

**Screenshots**
Taken of cow product from butcher.
![2019-07-27_17 08 46](https://user-images.githubusercontent.com/53134230/61999966-51775680-b092-11e9-99c6-4255f624cb2d.png)

** Server/Location **
What server were you playing on? 1.0.78 Tektopia mod server
What are the world coordinates of your town hall marker? 'Leafytown' -860 3600

**Comment by TangoTek** [comment]
Wow not sure how this one lasted this one, but thanks!  Fixed in next build
