### ISSUE TITLE
Villagers Falling Through Beds

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/TekTopia-Community#816]
Just after the update to 1.0.78 I noticed like half my village is stuck in the ground in beds. Theres only 3 screenshots but 2 of them have multiple villagers stuck in the same spot. It looks like when the villager gets stuck they unclaim the bed bringing another villager to claim it and also get stuck. 
I know it was just figured out the other day that villagers were having problems with going to beds in 2 tall houses. I think thats still a problem lol
I actually managed to see one villager "sleeping" in a bed at night, but he appears for a moment standing, then laying down and then I think he very quickly drops underground, which seems to be how all the other villagers got stuck that way. Sadly its too fast to get a screenshot.

![2019-07-27_19 16 00](https://user-images.githubusercontent.com/25763105/62000442-0b77be00-b0a5-11e9-86fe-baef86252032.png)
![2019-07-27_19 16 53](https://user-images.githubusercontent.com/25763105/62000443-0b77be00-b0a5-11e9-89b8-e1ea13b78028.png)
![2019-07-27_19 17 22](https://user-images.githubusercontent.com/25763105/62000444-0b77be00-b0a5-11e9-8995-4faaeb70e979.png)

**Comment by TangoTek** [comment]
Fixed in next build.  Side effect of this is they will look 'dark' tinted because their head is technically stuck int he ceiling during sleep.  GG. Build taller ceilings :-)
