### ISSUE TITLE
guards killing animals when hungry

### ISSUE THREAD

**Issue by anatharax** [TangoTek/TekTopia-Community#817]
**Describe the bug**
when a guard is patrolling and gets hungry instead of eating what is in his pockets if there is a nearby chicken he kills that and eats it. i kept finding dead chickens all over in the taiga where my village is but no predators then after a neco raid i watched a guard kill a chicken and eat it.

**Comment by TangoTek** [comment]
He killed a chicken because it was soul linked with the necro.  The guard didn't eat the raw chicken he was probably just hungry at that time and ate what he had in his inventory.
