### ISSUE TITLE
Hearts with same NBT data not producing same named kids.

### ISSUE THREAD

**Issue by Takaarakat** [TangoTek/TekTopia-Community#820]
Sacred Cows just spawned several children.  We had 12 in total, split up into 6 sets of 2 each with the same NBT data.  None of the kids had the same last name and I don't think any of the last names matched any of the current villagers.

**Comment by TraxKB** [comment]
FYI: there is an existing bug logged on this: https://github.com/TangoTek/TekTopia-Community/issues/153

**Comment by Takaarakat** [comment]
Thanks I'll close this one out and add to the other
