### ISSUE TITLE
Nether portal AI

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#822]
My oh my....

Blacksmith suddenly got 1 hit for 19 damage and i had absolutely no clue why that was.
https://gyazo.com/8e5c2ac5359b7a1f178f9380e6024ed1

Then i noticed the coords aren't even close to my village and it hit me - it walked into the nether portal. I didn't know this was even possible.

Could it be made a part of the villagers AI to walk around portals instead of into them?

Hope the report helps.

**Comment by Annie8472** [comment]
Portals and villagers don't mix well. We put out portal just outside of our village for that reason but most people just barricade the portal against villagers.

**Comment by TangoTek** [comment]
Villagers no longer travel through nether portals.
