### ISSUE TITLE
Feature Request: Increased Heart buff

### ISSUE THREAD

**Issue by Chartech100** [TangoTek/TekTopia-Community#824]
Thoughts for different features that would increase the rate of hearts spawning:
1. If a villager heard a bard play recently, has a chance for a buff that will slightly increase the chance of a heart when it goes to bed.
2. Cleric buff increases the chance of a heart if the buff is active when going to bed.
3. If you survived a necro raid with no death has a one night chance for increased heart spawn because everyone is just so happy to have survived.
4. Alternatively, instead of no death, if you do have a death from necro could be increased chance because they are reminded of the ever-present possibility of their impending death [enjoy life while you can ;)]

Not saying they would all be in the game but one specific way to target growing your village from the inside even if its a small proc chance to happen.

**Comment by TangoTek** [comment]
If I needed to turn heart spawn rates up these are good ideas. However, I just had to lower the rates this week.
