### ISSUE TITLE
Bug report: convert item loss

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#827]
I changed one of my farmer, carrying items such as an iron hoe, the food harvested and seeds etc, into a miner. Upon change it instantly lost its inventory to be replaced with a spawning miner one.

Instead can't they just keep the item it has (perhaps +1 wooden pickaxe upon change) and then it's first job will be to store any items it no longer needs back into the storage? Feel like that'd make a bit more sense - besides it also loses food it could've used as a miner.

**Comment by TangoTek** [comment]
Fixed in next build. Converted villagers will retain their inventory.
