### ISSUE TITLE
Bug(?); threat cleared but villagers dont return

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#830]
**Describe the bug**
After a villager threat (zombie) has broken into a house the villager starts to run. After the zombies are cleared and it's safe again, they don't return to bed, so then you're stuck baby sitting it through the night as it in my case ran away from the centre of the village towards more darker spots.

**To Reproduce**
1. Go to a sleeping villager
2. spawn a zombie
3. kill the zombie
4. villager stays in run mode

**Expected behavior**
I'd expect him to go back to bed after the "event" is over. Now its low hp + all its happiness gone due to sleep loss.

**Screenshots**
https://gyazo.com/dec7106b7ab46c2175bee324098aa324

** Server/Location **
What server were you playing on? Main(Survival)

What are the world coordinates of your town hall marker?
6924, 64, 8304

**Comment by TangoTek** [comment]
Villagers only get to sleep once per night. This is by design.  
I did just make it so they will return to their homes afterwards though without sleeping.
