### ISSUE TITLE
non villager meat

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#831]
My cow pen consist 100% of only villager cows.
My butcher takes one to slaughter it and somehow manages to end up with regular raw meat, instead of villager one.

Possible cause; the use of a non villager axe? 

possible fix; don't let a butcher grab non villager items or make normal items work instead.

**Comment by TangoTek** [comment]
By putting a non-villager axe in storage you are saying its OK for the butcher to make non-villager meat and for the lumberjack to chop non-villager logs.
Villager items are a critical concept to village development.
