### ISSUE TITLE
Possible bug: Taught children all get ~50int regardless of teacher level

### ISSUE THREAD

**Issue by treehugger667** [TangoTek/TekTopia-Community#834]
**Describe the bug**
Each child is ending with about 50 intelligence after attending school whether taught by a lvl 20 teacher or a lvl 90 teacher. 

**To Reproduce**
1. Spawn child with heart.
2. have children go to school and be taught by any level teacher with no books.
3. Nitwits will all have 40-50 intelligence depending on their starting intelligence.

**Expected behavior**
I would have expected children to gain less intelligence with a lower level teacher. And a higher level teacher would have children reach 50-70 intelligence by the time they turn into a nitwit.

** Server/Location **
What server were you playing on? 1.0.78 Tektopia Mod Server
What are the world coordinates of your town hall marker? 'Leafytown' -860 3600

With the current code it seems like there is no reason as to what the level of the teacher does. I would have expected a level 70-100 to drastically reduce the amount of times that a child raises their hand because they didn't learn anything. If you need books to reach this level of intelligence then disregard this as I haven't tested what levels children get to with books.

There have been times when nitwits only had 30 intelligence but most of these instances seem to be because of my loading the village mostly during the night.

**Comment by TangoTek** [comment]
Looking through the code is looks like you are mostly right. 

The teachers skill does currently affect how often a 'school event' will happen. The event is an opportunity for the child to learn (succeed) or raise their hand (fail).  However, the chance of this success was fixed.  I've just change it to use the teachers skill here as well.

Please monitor this for me after the next patch and give feedback.

**Comment by treehugger667** [comment]
Homework! will do.
