### ISSUE TITLE
Farmer Doesn't Plan Beetroot

### ISSUE THREAD

**Issue by Ghazzy118** [TangoTek/TekTopia-Community#835]
My farmer Breanna Redraven isn't planting beetroot.

In her inventory she has around 7 or 8 seeds. I've set her task to only plant the seeds, but across the span of a few in-game days she's maybe planted two or three.

My town hall is located: 1428 x 70 x -2549

**Comment by TangoTek** [comment]
I just went to your village and immediately saw farmers planting beetroots.
https://i.gyazo.com/b46a30d113396488715fd3dfe90c948f.png
