### ISSUE TITLE
Bug: Inconsistent non-villager tool behaviour

### ISSUE THREAD

**Issue by TraxKB** [TangoTek/TekTopia-Community#843]
**Describe the bug**
Referencing the closing notes of https://github.com/TangoTek/TekTopia-Community/issues/831#issue-473808312
> 
> 
> By putting a non-villager axe in storage you are saying its OK for the butcher to make non-villager meat and for the lumberjack to chop non-villager logs.
> Villager items are a critical concept to village development.

This is not consistent across all villagers and the statement on lumberjacks contradicts the current state of the game.  Most villagers can successfully use non-villager tools to create villager items (eg lumberjacks, miners, farmers, ranchers shearing.)  The butcher is the standout where this is NOT the case.

**To Reproduce**
1. Provide functioning villagers with player-made stone tools to replace their default wood ones.
2. Observe which ones create vilalger items and which ones do not

**Expected behavior**
-Player can create tools such as stone and place in storage
-All villagers can use player-made tools to create villager items
-Player-made tools will degrade twice as fast as villager-made tools

**Server/Location**
Consistent across builds, game modes and servers

**Additional context**
I believe that the butcher should be changed to match the behaviour of the other villagers rather than the other way around.  There is still incentive to create a blacksmith and villager tools due to the improved durability but it allows stone tools to be a stepping stone until the blacksmith is established making iron tools.  Early game growth is slow and a blacksmith is not a tier 1 priority.

**Comment by JohnyDL** [comment]
yeah.... this could cause a bit of a problem where the lumberjack is concerned:
0 villager tools in the village + 0 villager wood in the village = gridlock => village can never get village tools and slowly becomes unable to get most of the things to the merchant
only farmer products off the top of my head will be available

**Comment by TraxKB** [comment]
Fixed in 1.0.92 according to patch notes
