### ISSUE TITLE
Guards not crafting wooden swords

### ISSUE THREAD

**Issue by Moose1356** [TangoTek/TekTopia-Community#844]
Whenever a guard's sword breaks, instead of crafting a new wooden one. They keep patrolling and wont craft a wooden sword

![2019-07-28_22 40 54](https://user-images.githubusercontent.com/53441737/62062169-1722cc00-b1ee-11e9-8ace-52a8909a52ed.png)

** Server/Location **
Singleplayer & Tektopia survival

**Comment by TangoTek** [comment]
Fixed
