### ISSUE TITLE
Buckets... Oh the Buckets... and Cake??

### ISSUE THREAD

**Issue by Takaarakat** [TangoTek/TekTopia-Community#849]
I'm not quite sure how to explain this one.  I've been trying to watch our Chef and our Ranchers when they're using buckets/milk buckets.  Sometimes it seems to work properly but others it does not and I can't really recreate the issue.  

But I've noticed that our chef will take Villager Milk and after creating a cake (sometimes villager sometimes not...) the empty milk buckets will return to being non villager items.

At one point I followed the rancher who took the non villager buckets and when he filled them, it went to being Villager milk.  Tho at a separate occasion, the non-villager bucket made non-villager milk.  All Buckets that have been put into storage had originally come from Villager Iron.  I've never given them a single bucket.  I've now had to remove maybe 12 of them as they keep showing up as non-villager.

As for the Cake issue.  He was making some Villager Cakes for a couple rounds, but then I lost track of him and when he was just finishing making a new on, I didn't get to check if the milk buckets were proper or not but the output was a non villager cake.  

I think the whole underlying issue is the buckets... So, please take a look at them? lol  If you need me to explain more, I will try!

**Comment by stickrai** [comment]
i've been running into the same issue but wasn't sure what caused it! This does explain how they somehow got their hands on 10 non villager buckets i had never made for them.

Hope this one gets fixed soon too - including the cake thing because mine never put out villager cake's and i can never find the issue as everythings a villager ingredient

**Comment by TangoTek** [comment]
Fixed! Great catch.  It was returning villager buckets if the cake was a villager cake.  However, I forgot the that milk bucket might have been a villager item even though the resulting cake isn't.
Thanks Takaara!

**Comment by Takaarakat** [comment]
Haha! Thank you for fixing it!  Just ask Reilly how crazy I was going trying to figure that one out haha! You're awesome! :D
