### ISSUE TITLE
Suggestion: Change to the armor/weapon selections on guards

### ISSUE THREAD

**Issue by ScreaminMonk** [TangoTek/TekTopia-Community#851]
**Suggestion:** Change to the armor/weapon selections on guards

**Problem:** Diamond gear can be equipped faster than the enchanter can do their job.

The upgrading system works correctly but the guards will upgrade their gear faster than the enchanter can get to it. This combined with no way yet to unequip the guards or "lock" the unenchanted gear until an enchanter can do their thing leaves the player with guards using said gear first. 

Only current solution is that the player is left to constantly monitor the smithy for when they produce the gear you don't want to be picked up by a guard and then remove it.

If guards auto upgrade their armor to say, an enchanted piece, then you'll be left with the unenchanted piece again yes, but then have a surplus of armor eventually that could have been used for other tools, etc instead. 

**Benefits:**
This would also help the higher level guards you may want to have first dibs on the better gear get to it first? (Not sure how the programming is for that part.)

**Possible Solutions:** 

1. Have a check box to tell guards to equip:
- [ ] enchanted gear
- [ ] leather gear
- [ ] iron gear
- [ ] diamond gear
all of which could be checked or not to allow mixed and matched to still happen.

2. Smithy has some sort of interaction with enchanter to deliver the "goods" for enchantment. (If the crafted item can be enchanted). Enchanter delivers enchanted or non enchanted goods to storage then.

**Comment by TangoTek** [comment]
I took your #1 suggestion. Good stuff! Thanks.
