### ISSUE TITLE
Bug needing fixed: Converted villagers do not retain their intelegence

### ISSUE THREAD

**Issue by Asher90** [TangoTek/TekTopia-Community#853]
**Describe the bug**
when a villager token is use to assign a villager a profession they do not retain their intelligence

**To Reproduce**
1. create baby villager
2. wait for baby to grow up to nitwit
3. look at intelligence prior to conversion to a profession
4. look at intelligence after conversion to a profession

**Expected behavior**
retention of intelligence

**Screenshots**
Before
![2019-07-29_21 45 47](https://user-images.githubusercontent.com/53152960/62096876-c3929b80-b24a-11e9-857f-c202606b9c08.png)
after
![2019-07-29_21 46 01](https://user-images.githubusercontent.com/53152960/62096881-c8efe600-b24a-11e9-97a4-fe93718c7f66.png)

** Server/Location **
TekTopia Playthrough

**Comment by Asher90** [comment]
could be older villager tokens, will test with new one

**Comment by Jamcdonald120** [comment]
![image](https://user-images.githubusercontent.com/22623066/62097100-7236dc00-b24b-11e9-9187-72726862f845.png)
Same, int was 40 ish

**Comment by Asher90** [comment]
Updated photo's first picks of two different villagers sry

Before Conversion with new token
![2019-07-29_21 55 18](https://user-images.githubusercontent.com/53152960/62097252-d659a000-b24b-11e9-843b-47b8d7096904.png)
After Conversion with new Token
![2019-07-29_21 55 30](https://user-images.githubusercontent.com/53152960/62097262-df4a7180-b24b-11e9-8c00-db09353b8f60.png)

**Comment by Asher90** [comment]
I swear those are the same villager, so they also do not retain their name

**Comment by Lleryn28** [comment]
I can confirm that the villagers change their names and lose all intelligence.  I had a child Zac raised up to intelligence 62.  After converting him to an enchanter, he changed names and his intelligence lowered to 9.  Luckily his enchanter level was 60, but this still is a huge decrease for their intelligence.

**Comment by TangoTek** [comment]
Yep. Sorry. Broken in 1.0.84. Fixed in next build.
