### ISSUE TITLE
Feedback: teacher raising students skills

### ISSUE THREAD

**Issue by Lleryn28** [TangoTek/TekTopia-Community#854]
Feedback only:

My teacher with 100 skill taught 12 children for a day.  The lowest intelligence increase for the children was 4 with the highest being 13.  The teacher did not have any books, villager or non-villager.  The average intelligence gain per student was: 7.5.  With the most common skill up amount being 9.  This is just feedback for Tango.  

In my opinion these are very nice numbers.  They might be a little high, but the teacher was at 100 skill the entire time (with druid blessing).

**Comment by TangoTek** [comment]
Much appreciated! That's right about where I want it
