### ISSUE TITLE
Nomad's name changes after conversion to villager

### ISSUE THREAD

**Issue by AnnaThePonderer** [TangoTek/TekTopia-Community#855]
**Describe the bug**
Nomad's name changes after conversion to villager.

**To Reproduce**
I purchased a blacksmith token from the Tradesman and applied it to a nomad.  The nomad's name changed from (Something) Pyncion to Norris Sol.

**Expected behavior**
Nomad should have retained his name.

**Screenshots**
![image](https://user-images.githubusercontent.com/53462593/62104386-ca6ced00-b2e2-11e9-9cf5-f9044463cc0d.png)

** Server/Location **
Main(Survival)
-800 72 -4530

**Comment by TangoTek** [comment]
Duplicated. Fixed in next build

**Comment by AnnaThePonderer** [comment]
Thanks Tango. It actually happens with nitwit conversions too.
