### ISSUE TITLE
Necromancer spawns not showing up

### ISSUE THREAD

**Issue by stickrai** [TangoTek/TekTopia-Community#857]
**Describe the bug**
A necromancer is supposed to spawn but doesn't

**To Reproduce**
Get a necromancer spawn message, to find out it isn't actually anywhere.

**Expected behavior**
I'd expect him to show up. This has happened twice now.

**Screenshots**
https://gyazo.com/76779ba2aa6516b825c5c3f68622793f

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**
2 Times i've gotten the message and nothing ever showing up. It's a bit sad because I am looking forward to that part of the mod to see how it is for myself. Unfortunately it doesn't seem to happen at this rate.
First spawn message was during daytime, this time during night.
Flew along my entire borders and it's NOWHERE to be found.

**Comment by TangoTek** [comment]
This was fixed in 1.0.87
