### ISSUE TITLE
Guards

### ISSUE THREAD

**Issue by IainJames** [TangoTek/TekTopia-Community#861]
My Guards Starving when there is food.
Sometimes the guards don't get food till there starving 
**Guards still training when starving**
It's happened 4 or 5 times over a week. 
Survival TekTopia 
![2019-07-30_20 39 40](https://user-images.githubusercontent.com/53226831/62130487-ae317600-b30b-11e9-9c4c-3bb21056ad84.png)

**Comment by Lleryn28** [comment]
Just to add to this, when my guard did it she was at 58 skill and an intelligence of 45 (Lleryn's Village: Guard name Elaine Paspinall).  I believe the guards are not supposed to train in the barracks if they are already above their intelligence in their guard skill.  To fix this, I had to break the armor stand and then she realized she was hungry and went and got food.

**Comment by TangoTek** [comment]
Guards will stop attacking anything once their hunger is below 10 now. This should give them plenty of time to eat and/or get food.

**Comment by IainJames** [comment]
Guards still starving btw.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
