### ISSUE TITLE
Skeletons spawned by necro shooting across map at player

### ISSUE THREAD

**Issue by Chartech100** [TangoTek/TekTopia-Community#869]
**Description**
Skeletons attempting to shoot at player way further than can even notice them causing them to shoot the other mobs around them and just stand there fighting each other.

**To Reproduce**
Stand 20-30+ blocks from skeletons spawned by the necro and they will attempt to shoot at you from completely impossible distances.

**Expected behavior**
Expected shots at the player once within range.

**Screenshots**
![2019-07-31_00 00 42](https://user-images.githubusercontent.com/51539278/62195018-ee0a5480-b32f-11e9-8ab9-289397ed1543.png)

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)? SP
What are the world coordinates of your town hall marker? N/A

**Comment by TangoTek** [comment]
Lowered this range from 64 to 32. It still needs to be increased because its the same value that allows the minion to follow the necromancer.
