### ISSUE TITLE
Skin turns Translucent next to village border

### ISSUE THREAD

**Issue by TimoDonnermeyer** [TangoTek/TekTopia-Community#872]
**Describe the bug**
If you come closer than 8 blocks to the village border the player skin becomes translucent.

**Screenshots**
Normal Skin
![2019-07-31_14 40 48](https://user-images.githubusercontent.com/45743293/62215533-711ac180-b3a7-11e9-80da-0a243adb4652.png)

If you come to close
![2019-07-31_14 40 43](https://user-images.githubusercontent.com/45743293/62215555-7972fc80-b3a7-11e9-9ade-e754277865a1.png)

**Comment by LadyGwynn** [comment]
Previously reported in #634
