### ISSUE TITLE
Suggestion: Golden Apples

### ISSUE THREAD

**Issue by SkystriderTAG** [TangoTek/TekTopia-Community#879]
allow chefs to make Golden Apples , it wont be considered food by villagers and would be used by guards.  If a guard reaches like 50-75% hp (Somewhere in that range) it will retreat 10-15 blocks , eat the gapple and if its a villager gapple it gains regeneration based on guard level (longer for higher level guards) as well as the normal 2 absorbion hearts..  It would make gold a bit more useful to the economy as well as make it so necro attacks are a bit less likely to result in killed guards for us.

**Comment by stickrai** [comment]
big yes!

**Comment by TangoTek** [comment]
Great Idea!  And super easy to implement.  Done!
