### ISSUE TITLE
Guard killing chickens

### ISSUE THREAD

**Issue by Tab-160** [TangoTek/TekTopia-Community#888]
**Describe the bug**
I brought over 3 chickens near my pen and temporarily placed them on a lead near the pen. My guard came over and killed 2 of them. 

**To Reproduce**
1. Bring three chickens to outside of a pen
2. Attach them to outside with leads
3. See error

**Expected behavior**
I expected my guard to leave the chicken alone

** Server/Location **
What server were you playing on? Main(Survival)
What are the world coordinates of your town hall marker? Tab's village at 4195 / 7309

**Additional context**
I have 2 guards and no butcher

**Comment by TangoTek** [comment]
They were soul linked by a necromancer.

**Comment by Tab-160** [comment]
There were no necromancers and they did not have the partial effects around them.
