### ISSUE TITLE
ranchers take mooshrooms but dont put them in a pen

### ISSUE THREAD

**Issue by ghost** [TangoTek/TekTopia-Community#899]
**Describe the bug**
A rancher will lead an mooshroom but never puts it in a pen

**To Reproduce**
have an rancher and an mooshroom in range.
the rancher will lead the mooshroom,
the rancher will keep walking with the mooshroom without putting it in a pen even when the pen was empty

**Expected behavior**
a few options.
the rancher does not lead the mooshroom.
the rancher does lead the mooshroom and puts it in the cow pen.
make a new pen for the mooshroom and put them there.

** Server/Location **
did it in creative in the latest version

**Comment by TangoTek** [comment]
Fixed in next patch. Thanks!
