### ISSUE TITLE
Blacksmith converts all iron ore to iron ingots

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#90]
**Describe the bug**
Regardless of the state of the village a blacksmith will convert all the mined iron ore into iron ingots despite the fact that the merchant will by the raw ore and he has several stacks of iron ingots to use on other things

**To Reproduce**
large mining set up and a blacksmith and tome

**Expected behavior**
Once the blacksmith has made some stacks of iron ingots he tries to keep a balance between iron ore blocks and iron ingots in storage not making more than he has to

** Server/Location **
Offline

**Comment by TangoTek** [comment]
Iron ore isn't purchased by the Merchant any longer.  The new AI customization should help this as well.
