### ISSUE TITLE
Butcher building name

### ISSUE THREAD

**Issue by Dogez** [TangoTek/TekTopia-Community#900]
Just like how the blacksmith building was recently changed to the Smithy, I feel like the butcher and butcher should have separate names. So, I have a small suggestion: Rename the butcher building. I have a idea of what it could be called, which is the Slaughterhouse. Idk, it might sound too gory. Just an idea. Thanks!

**Comment by TangoTek** [comment]
Yea, I don't like that the two names are the same, but I also don't like Slaughterhouse for the reason you mentioned.  I'm open to other names, but at this point I'm doubtful I'll think of one.

**Comment by JohnyDL** [comment]
I always call my butcher building the Abattoir since that's where the animals are killed rather than prepared for sale and it's not as gory sounding as slaughterhouse

**Comment by dyKrev** [comment]
Why not just call it a butchery?
