### ISSUE TITLE
Villager stuck on border + wood needed to make sword?

### ISSUE THREAD

**Issue by MetriCfan** [TangoTek/TekTopia-Community#904]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Server/Location **
What server were you playing on? Main(Survival) or Dev (Creative)?
What are the world coordinates of your town hall marker?

**Additional context**

**Comment by MetriCfan** [comment]
A nitwit wandered to the edge of the village where it is ice. probably slid over to the border and was stuck there. I tried a stone path but that didn't work I had to push the villager away to get them going.
Also I don't have lumberjacks and put wood in the storage and found that they use a log to make the iron sword. I observed this. Once I removed the wood I am not getting swords or axes made, possibly pickaxes too but I am supplying those. I assume that is is on purpose that they consume a log when making swords etc.? If so I'll get a lumberjcak, please advise.
![image](https://user-images.githubusercontent.com/51779504/62752784-36521100-baac-11e9-92dc-e5b250758e7b.png)
![image](https://user-images.githubusercontent.com/51779504/62752786-3c47f200-baac-11e9-9a5f-d384c73eaae7.png)

**Comment by JohnyDL** [comment]
This looks like #657 coming into play the grid doesn't path to all village boundaries.... I'd argue that the village boundary is where the villagers should be allowed to go through normal means but the grid should extend beyond that just in case. You should be able to nudge them back on or use a lead

**Comment by MetriCfan** [comment]
what an idiot of course they use wood for sword pickaxe and axe omg
