### ISSUE TITLE
Suggestion: Turn off sapling replanting

### ISSUE THREAD

**Issue by JenesisDark** [TangoTek/TekTopia-Community#905]
I think it would be nice if you could turn off sapling replanting. Just if you're in a wooded area and want it cleared, not replanted. :)

**Comment by JohnyDL** [comment]
You can pretty much do that by turning off sapling collection, if they can't collect the saplings they can't replant them

**Comment by JenesisDark** [comment]
Thats true, I always thought of sapling collection more like a farming tool, not a clearing tool. Thank you :)
