### ISSUE TITLE
Miner's wont mine

### ISSUE THREAD

**Issue by UltraHunter** [TangoTek/TekTopia-Community#927]
**Describe the bug**
So a couple hours ago my miners started to just not mine, even though they had torches, food, pickaxes, and happy

**To Reproduce**
I have no idea how this happened

These are my 2 mineshafts, and there's no lava or water behind it (I checked)
![Screenshot (87)](https://user-images.githubusercontent.com/53666531/63217859-1d340a80-c113-11e9-9767-5f937ddefe0a.png)
![Screenshot (88)](https://user-images.githubusercontent.com/53666531/63217860-1e653780-c113-11e9-8313-2c2fbbf4f992.png)
My coords
![Screenshot (91)](https://user-images.githubusercontent.com/53666531/63217873-553b4d80-c113-11e9-9c55-b3d3f2fd6e07.png)
These area my miner's inv's
![Screenshot (97)](https://user-images.githubusercontent.com/53666531/63217875-5f5d4c00-c113-11e9-9910-45000b7a954a.png)
![Screenshot (94)](https://user-images.githubusercontent.com/53666531/63217877-61270f80-c113-11e9-92f4-30c1b1bc8743.png)

** Server/Location **
I was playing on main survival tektopia 
cords above in the SS

**Additional context**
TheGreatNaj has tried to help, by replacing the tokens, replacing the villagers, reassigning professions, nothing has worked.

**Comment by owmee1** [comment]
it wont work for me
