### ISSUE TITLE
Nitwits don't get job levels

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#93]
**Describe the bug**
Nitwits always start at level 1 for their job even if they've been schooled

**To Reproduce**
School a nitwit, level them up

**Expected behavior**
Tango said the first job a Nitwit does should get some automatic levels depending on their schooling. So converting a nitwit to a job should give them some skills to make schooling and homegrown villagers better than nomads

** Server/Location **
Offline

**Comment by ghost** [comment]
They should get level one but they will level up faster if they went to school.

**Comment by TangoTek** [comment]
Villagers converted from a nitwit will now be granted an initial skill boost in their profession based on the nitwits education level
