### ISSUE TITLE
Druid makes mine invalid

### ISSUE THREAD

**Issue by ghost** [TangoTek/TekTopia-Community#97]
**Describe the bug**
tested in singleplayer
with multiple druids they will regen the mine all at the same time making the 2 blocks under the marker not air. And so making the structure invalid

**To Reproduce**
1. get multiple druids
2. get a mine
3. break some blocks in the mine
4. druids will place blocks to fill up the mine until the mine is invalid

**Expected behavior**
they should stop before making the structure invalid

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/43604273/58432988-94be4480-80a4-11e9-88c4-2330976d8aef.png)

** Server/Location **
singleplayer

**Additional context**
about 5 druids and 3 miners with 3 mines

**Comment by TangoTek** [comment]
Great find!  Druids will no longer Earth Reform on tunnels less than 3 blocks in length.  
Thank you!
