### ISSUE TITLE
Chef not Making food

### ISSUE THREAD

**Issue by tonicsense** [TangoTek/TekTopia-Community#972]
my chef does not make any food at all his inventory has items to make the food he requires yet he does not make that food. He has a kitchen in the tavern which is supplied with 5 oven and a workbench.
Instead he behaves like a nitwit and just wanders around the city wasting my food and bed space
Same with my Blacksmith

**Comment by tonicsense** [comment]
Nvm figured it out

**Comment by Creenel** [comment]
How did you figure it out?
My chefs aren't even going into the kitchen.

**Comment by tonicsense** [comment]
Is the Kitchen marked with a kitchen Token?
