### ISSUE TITLE
Golems ignore Necromancer

### ISSUE THREAD

**Issue by JohnyDL** [TangoTek/TekTopia-Community#99]
**Describe the bug**
Both Iron and snow Golems completely ignore this hostile mob

**To Reproduce**
place golems and spawn necromancer

**Expected behavior**
Golems attack hostile mobs

**Screenshots**
![2019-05-27_19 59 16](https://user-images.githubusercontent.com/5202568/58435813-49169580-80ba-11e9-8645-40866f7d2f6b.png)

** Server/Location **
Offline

**Comment by TangoTek** [comment]
Necromancer is now technically a mob.  Golems will attack it.
